package br.wsorpec.wscdlrio.empresarialTop;

import java.io.BufferedReader;
import java.io.ByteArrayInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.io.OutputStreamWriter;
import java.io.StringReader;
import java.net.HttpURLConnection;
import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.bind.JAXBContext;
import javax.xml.bind.JAXBException;
import javax.xml.bind.Unmarshaller;

import org.apache.commons.io.IOUtils;

import br.wsorpec.autenticacao.Autenticacao;
import br.wsorpec.cache.Cache;
import br.wsorpec.faturamento.Bilhetagem;
import br.wsorpec.log.Log;
import br.wsorpec.util.GlobalConstants;
import br.wsorpec.util.Util;

public class ExecutaEmpresarialTop {

	private static Log log;
	private static Cache cache = new Cache();
	private static String protocolo;
	private static String resposta;
	

	public ExecutaEmpresarialTop() {}
	
	public EmpresarialTop executar(EmpresarialTop empTop, boolean xml) {
		
		if (!critica(empTop)) {
			empTop.setSenha("");
			return empTop;
		}
		
		log = new Log(false, GlobalConstants.PASTALOG);
		protocolo = Util.geraProtocolo();	
		resposta = "";
		
		//Criptografa a senha;
		empTop.setSenha(Util.converteMD5(empTop.getSenha(), protocolo, log));
		
		String ipRemoto    = GlobalConstants.IPREMOTO;
		boolean isCache    = false;
		String codigo      = empTop.getCodigo();
        String senha       = empTop.getSenha();
		String produto     = "74";
		String solicitacao = "Produto="+produto+";Codigo="+empTop.getCodigo()+";Senha="+empTop.getSenha()+";CNPJ="+empTop.getCnpj();
						
		resposta = cache.cacheConsulta(solicitacao, protocolo, log); // Verifica cache
		
		if (resposta.trim().length() > 0) { // verifica se o cache respondeu
			isCache = true;
		}

		if (!isCache) { // Se nao foi respondido pelo cache da procedimento.
			log.registro(protocolo, "SND", solicitacao);
			
			//Fazer logon - verificar codigo, senha e se o produto pode ser consultado.
			Autenticacao aut = new Autenticacao();
			String strLogon = aut.logon(codigo, senha, produto, protocolo);
			if(!strLogon.equals("OK")) {
				cache.apagaCache(protocolo);
				log.registro(protocolo, "RCV", strLogon);
				empTop.setStatusRetorno((byte) 1);
				empTop.setMensagemRetorno(strLogon);				
				return empTop;
			}
						
			//Fazer a consulta nos BUREAU 			
			empTop = consultaCDLRio(empTop);	
			
			if(empTop.getSpcaxml().getRESPOSTA().getRESPOSTARETORNO().getSTATUSRESPOSTA()==0) {
				//Fazer a bilhetagem					
				Bilhetagem bilhetar = new Bilhetagem();
				bilhetar.bilhetar(GlobalConstants.idCliente, empTop.getCnpj(), produto, ipRemoto, protocolo);
			}
									
			//Atualizo a mensagem que veio do CDLRio para o WSOrpec
			empTop.setStatusRetorno(empTop.getSpcaxml().getRESPOSTA().getRESPOSTARETORNO().getSTATUSRESPOSTA());
			empTop.setMensagemRetorno(empTop.getSpcaxml().getRESPOSTA().getRESPOSTARETORNO().getMENSAGEMRESPOSTA());
			
			//Limpo as tag <S-CODIGO>, <S-SENHA>, <S-SOLICITANTE> e <ASSOCIADO-SOLICITANTE> 
			resposta = Util.gravaTag("<S-CODIGO>", "0", resposta);
			resposta = Util.gravaTag("<S-SENHA>", "0", resposta);
			resposta = Util.gravaTag("<S-SOLICITANTE>", "", resposta);
			resposta = Util.gravaTag("<ASSOCIADO-SOLICITANTE>", "", resposta);
						
			//Retiro informacoes da tag <SPCA-XML>
			resposta = Util.limpaXML(resposta);
			
			if(xml){empTop.setXml(resposta);}// Quando a resposta retorna só o xml
			cache.cacheResposta(resposta, protocolo);
			log.registro(protocolo, "RCV", resposta);
		}else{// Se foi respondido pelo cache
			InputStream is = null;
			BufferedReader br = null;
			SPCAXML obj = new SPCAXML();
			try {				
				is = new ByteArrayInputStream(resposta.getBytes());
				br = new BufferedReader(new InputStreamReader(is));

				// Faco o parse aqui xml->classe java
				JAXBContext jaxbContext = JAXBContext.newInstance(SPCAXML.class);
				Unmarshaller jaxbUnmarshaller = jaxbContext.createUnmarshaller();
				obj = (SPCAXML) jaxbUnmarshaller.unmarshal(br);

				empTop.setSpcaxml(obj);
				if (xml) {
					empTop.setXml(resposta);
				} // Quando a resposta retorna só o xml

				// Atualizo a mensagem que veio do CDLRio para o WSOrpec
				empTop.setStatusRetorno(empTop.getSpcaxml().getRESPOSTA().getRESPOSTARETORNO().getSTATUSRESPOSTA());
				empTop.setMensagemRetorno(empTop.getSpcaxml().getRESPOSTA().getRESPOSTARETORNO().getMENSAGEMRESPOSTA());

				is.close();
				br.close();
			} catch (JAXBException e) {
				e.printStackTrace();
				log.registro(protocolo, "ERRO", e.getMessage());
				empTop.setStatusRetorno((byte) 1);
				empTop.setMensagemRetorno("Erro no parse do cache para o objeto");
			} catch (IOException e) {
				log.registro(protocolo, "ERRO", e.getMessage());
				empTop.setStatusRetorno((byte) 1);
				empTop.setMensagemRetorno("Erro no parse do cache para o objeto");
			}
		}
		return empTop;
	}

	public boolean critica(EmpresarialTop empTop){
		
		if(Util.Empty(empTop.getCodigo())){
			empTop.setStatusRetorno((byte) 1);
			empTop.setMensagemRetorno("Codigo nao informado");
			return false;
		}else{
			if(!Util.isdigit(empTop.getCodigo())){
				empTop.setStatusRetorno((byte) 1);
				empTop.setMensagemRetorno("Codigo invalido");				
				return false;
			}
		}
		if(Util.Empty(empTop.getSenha())){
			empTop.setStatusRetorno((byte) 1);
			empTop.setMensagemRetorno("Senha nao informada");				
			return false;
		}
		if (Util.Empty(empTop.getCnpj())) {
			empTop.setStatusRetorno((byte) 1);
			empTop.setMensagemRetorno("CNPJ nao informado");				
			return false;			
		}else {
			if (!Util.IsCNPJ(empTop.getCnpj())) {
				empTop.setStatusRetorno((byte) 1);
				empTop.setMensagemRetorno("CNPJ invalido");				
				return false;
			}
		}
		return true;
	}
	
	public EmpresarialTop consultaCDLRio(EmpresarialTop empTop) {
		URL url;
		HttpURLConnection con;
		BufferedReader br = null;
		SPCAXML obj = new SPCAXML();
		String solicitacao = "";
		int HTTP_COD_SUCESSO = 200;
		
		solicitacao = "<SPCA-XML xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xsi:noNamespaceSchemaLocation=\"http://www.scpc.inf.br/spcn/spcaxmlefx.xsd\">" + 
				  "	<VERSAO>20151030</VERSAO>" + 
				  "	<SOLICITACAO>" + 
				  "		<S-CODIGO>"+GlobalConstants.USRCDLRIO+"</S-CODIGO>" + 
				  "		<S-SENHA>"+GlobalConstants.PWRCDLRIO+"</S-SENHA>" + 
				  "		<S-CONSULTA>623</S-CONSULTA>" + 
				  "		<S-SOLICITANTE>RJ001</S-SOLICITANTE>" + 
				  "		<S-CNPJ>"+empTop.getCnpj()+"</S-CNPJ>"+
				  "     <S-NUMERO-RESPOSTA>0</S-NUMERO-RESPOSTA>" +				  
				  "		<S-DEFINE-PRODUTO>" + 
				  "			<S-DEF-QUADRO-SOCIAL>S</S-DEF-QUADRO-SOCIAL>" + 
				  "			<S-DEF-PARTICIPACOES>S</S-DEF-PARTICIPACOES>" + 
				  "		</S-DEFINE-PRODUTO>" + 
				  "	</SOLICITACAO>" + 
				  "</SPCA-XML>";
	
		try {
			url = new URL(GlobalConstants.URLCDLRIO);
			con = (HttpURLConnection) url.openConnection();
			
			// specify that we will send output and accept input
			con.setDoInput(true);
			con.setDoOutput(true);
			// con.setConnectTimeout(15000); //long timeout, but not infinite
			// con.setReadTimeout(15000);
			con.setUseCaches(false);
			con.setDefaultUseCaches(false);
			// Tell the web server what we are sending
			//con.setRequestProperty("Content-Type", "text/xml;charset=ISO-8859-1");

			OutputStreamWriter writer = new OutputStreamWriter(con.getOutputStream());
			writer.write(solicitacao);
			writer.flush();
			writer.close();

			if (con.getResponseCode() != HTTP_COD_SUCESSO) {
				log.registro(protocolo, "ERRO", "HTTP error code : " + con.getResponseCode());
				empTop.setStatusRetorno((byte) 1);
				empTop.setMensagemRetorno("Erro na comunicacao com o Fornecedor 1");
				cache.apagaCache(protocolo);
				log.registro(protocolo.trim(), "INF", "Apaga cache, "+empTop.getMensagemRetorno());
				return empTop;
			}
			
			//Aqui o encolde eh ISO-8859-1
			byte[] imageBytes = IOUtils.toByteArray(con.getInputStream());
			resposta = new String(imageBytes, "ISO-8859-1");
			resposta = resposta.trim().replace("\n", "");
			resposta = resposta.trim().replace("    ", "");
			

			//resposta = "<SPCA-XML><VERSAO>20151030</VERSAO><SOLICITACAO><S-REGIONAL>0</S-REGIONAL><S-CODIGO>00001</S-CODIGO><S-SENHA></S-SENHA><S-CONSULTA>74</S-CONSULTA><S-SOLICITANTE></S-SOLICITANTE><S-CNPJ>33014556000196</S-CNPJ><S-BANCO>0</S-BANCO><S-AGENCIA>0</S-AGENCIA><S-CONTA-CORRENTE>0</S-CONTA-CORRENTE><S-CONTA-DIGITO>0</S-CONTA-DIGITO><S-CHEQUE>0</S-CHEQUE><S-CHEQUE-DIGITO>0</S-CHEQUE-DIGITO><S-CMC7/><S-CHEQUE-ORIGEM/><S-NUMERO-RESPOSTA>0</S-NUMERO-RESPOSTA><S-DEFINE-PRODUTO><S-DEF-QUADRO-SOCIAL>S</S-DEF-QUADRO-SOCIAL><S-DEF-QUADRO-COMRESTRICAO/><S-DEF-PARTICIPACOES>S</S-DEF-PARTICIPACOES><S-DEF-PART-COMRESTRICAO/><S-DEF-DECISAO/><S-DEF-FAT-PRESUMIDO/><S-DEF-LIMITE-CREDITO/><S-DEF-SCORE-EMPRESARIAL/><S-DEF-ANVISA/><S-DEF-EMPR-MESMO-ENDERECO/><S-DEF-CADASTRO-BASICO/><S-DEF-CADASTRO-COMPLETO/><S-DEF-RESTRITIVO-BASICO/><S-DEF-RESTRITIVO-COMPLETO/><S-DEF-COMPORTAMENTO/><S-DEF-CHEQUE/></S-DEFINE-PRODUTO></SOLICITACAO><RESPOSTA><RESPOSTA-RETORNO><STATUS-RESPOSTA>0</STATUS-RESPOSTA><MENSAGEM-RESPOSTA>CONSULTA CONCLUIDA</MENSAGEM-RESPOSTA></RESPOSTA-RETORNO><NUMERO-RESPOSTA>281987127-9</NUMERO-RESPOSTA><ASSOCIADO-SOLICITANTE></ASSOCIADO-SOLICITANTE><NOME-CONSULTA>Define Risco</NOME-CONSULTA><IP-SOLICITANTE>129.0.0.1</IP-SOLICITANTE><DEFINE-RESPOSTA><DEF-IDENTIFICACAO-BASICO><DEF-CNPJ>33014556000196</DEF-CNPJ><DEF-UF-INSCRICAO-ESTADUAL>RJ</DEF-UF-INSCRICAO-ESTADUAL><DEF-DATA-FUNDACAO>01/08/1966</DEF-DATA-FUNDACAO><DEF-CODIGO-NATUREZA-JURIDICA>2046</DEF-CODIGO-NATUREZA-JURIDICA><DEF-NATUREZA-JURIDICA>SOCIEDADE ANONIMA ABERTA</DEF-NATUREZA-JURIDICA><DEF-RAZAO-SOCIAL>LOJAS AMERICANAS S/A</DEF-RAZAO-SOCIAL><DEF-SITUACAO-CNPJ>Ativo</DEF-SITUACAO-CNPJ><DEF-DATA-SITUACAO-CNPJ>03/11/2005</DEF-DATA-SITUACAO-CNPJ><DEF-DATA-CONSULTA-RECEITA-FEDERAL>10/07/2020</DEF-DATA-CONSULTA-RECEITA-FEDERAL><DEF-NUMERO-NIRE>33300028170</DEF-NUMERO-NIRE><DEF-UF-NIRE>RJ</DEF-UF-NIRE><DEF-INSCRICAO-ESTADUAL>00000081579393</DEF-INSCRICAO-ESTADUAL><DEF-RAMO-ATIVIDADE><DEF-ATIVIDADE>COM VAREJ MERC GERAL PRED PRODS ALIMENT</DEF-ATIVIDADE><DEF-CNAE>4711-3/02</DEF-CNAE></DEF-RAMO-ATIVIDADE></DEF-IDENTIFICACAO-BASICO><DEF-LOCALIZACAO-BASICO><DEF-LOGRADOURO>R SACADURA CABRAL, 102</DEF-LOGRADOURO><DEF-BAIRRO>SAUDE</DEF-BAIRRO><DEF-CEP>20081902</DEF-CEP><DEF-CIDADE>RIO DE JANEIRO</DEF-CIDADE><DEF-UF>RJ</DEF-UF></DEF-LOCALIZACAO-BASICO><DEF-SCORE><DEF-SCORE-PJ><DEF-PROBABILIDADE>0.0</DEF-PROBABILIDADE><DEF-TEXTO>O risco não se aplica a esse porte de empresa. Analisar demais informações do relatório.</DEF-TEXTO><DEF-SCORE>2</DEF-SCORE><DEF-MODELO-SCORE>38</DEF-MODELO-SCORE><DEF-CLASSIFICACAO-NUMERICA>17</DEF-CLASSIFICACAO-NUMERICA><DEF-CLASSIFICACAO-ALFABETICA>G</DEF-CLASSIFICACAO-ALFABETICA></DEF-SCORE-PJ></DEF-SCORE><DEF-SOCIOS><DEF-HABILITA>true</DEF-HABILITA><DEF-SOCIO><DEF-NOME-EMPRESA>OUTROS</DEF-NOME-EMPRESA><DEF-CPF-CNPJ>00000000000000</DEF-CPF-CNPJ><DEF-TIPO-DOCUMENTO>0</DEF-TIPO-DOCUMENTO><DEF-SITUACAO-DOCUMENTO>-</DEF-SITUACAO-DOCUMENTO><DEF-PARTICIPACAO>046,58</DEF-PARTICIPACAO><DEF-ASSINA-EMPRESA>N</DEF-ASSINA-EMPRESA><DEF-INDICADOR-DEBITO>Não</DEF-INDICADOR-DEBITO><DEF-INDICADOR-FRAUDE>Não</DEF-INDICADOR-FRAUDE></DEF-SOCIO><DEF-SOCIO><DEF-NOME-EMPRESA>BRC S.A.R.L.</DEF-NOME-EMPRESA><DEF-CPF-CNPJ>00000000000000</DEF-CPF-CNPJ><DEF-TIPO-DOCUMENTO>0</DEF-TIPO-DOCUMENTO><DEF-SITUACAO-DOCUMENTO>-</DEF-SITUACAO-DOCUMENTO><DEF-PARTICIPACAO>016,92</DEF-PARTICIPACAO><DEF-ASSINA-EMPRESA>N</DEF-ASSINA-EMPRESA><DEF-INDICADOR-DEBITO>Não</DEF-INDICADOR-DEBITO><DEF-INDICADOR-FRAUDE>Não</DEF-INDICADOR-FRAUDE></DEF-SOCIO><DEF-SOCIO><DEF-NOME-EMPRESA>INVESCO LTD</DEF-NOME-EMPRESA><DEF-CPF-CNPJ>00000000000000</DEF-CPF-CNPJ><DEF-TIPO-DOCUMENTO>0</DEF-TIPO-DOCUMENTO><DEF-SITUACAO-DOCUMENTO>-</DEF-SITUACAO-DOCUMENTO><DEF-PARTICIPACAO>007,95</DEF-PARTICIPACAO><DEF-ASSINA-EMPRESA>N</DEF-ASSINA-EMPRESA><DEF-INDICADOR-DEBITO>Não</DEF-INDICADOR-DEBITO><DEF-INDICADOR-FRAUDE>Não</DEF-INDICADOR-FRAUDE></DEF-SOCIO><DEF-SOCIO><DEF-NOME-EMPRESA>BLACKROCK. INC.</DEF-NOME-EMPRESA><DEF-CPF-CNPJ>00000000000000</DEF-CPF-CNPJ><DEF-TIPO-DOCUMENTO>0</DEF-TIPO-DOCUMENTO><DEF-SITUACAO-DOCUMENTO>-</DEF-SITUACAO-DOCUMENTO><DEF-PARTICIPACAO>003,30</DEF-PARTICIPACAO><DEF-ASSINA-EMPRESA>N</DEF-ASSINA-EMPRESA><DEF-INDICADOR-DEBITO>Não</DEF-INDICADOR-DEBITO><DEF-INDICADOR-FRAUDE>Não</DEF-INDICADOR-FRAUDE></DEF-SOCIO><DEF-SOCIO><DEF-NOME-EMPRESA>CEDAR TRADE LLC</DEF-NOME-EMPRESA><DEF-CPF-CNPJ>00000000000000</DEF-CPF-CNPJ><DEF-TIPO-DOCUMENTO>0</DEF-TIPO-DOCUMENTO><DEF-SITUACAO-DOCUMENTO>-</DEF-SITUACAO-DOCUMENTO><DEF-PARTICIPACAO>000,33</DEF-PARTICIPACAO><DEF-ASSINA-EMPRESA>N</DEF-ASSINA-EMPRESA><DEF-INDICADOR-DEBITO>Não</DEF-INDICADOR-DEBITO><DEF-INDICADOR-FRAUDE>Não</DEF-INDICADOR-FRAUDE></DEF-SOCIO><DEF-SOCIO><DEF-NOME-EMPRESA>ACOES TESOURARIA</DEF-NOME-EMPRESA><DEF-CPF-CNPJ>00000000000000</DEF-CPF-CNPJ><DEF-TIPO-DOCUMENTO>0</DEF-TIPO-DOCUMENTO><DEF-SITUACAO-DOCUMENTO>-</DEF-SITUACAO-DOCUMENTO><DEF-PARTICIPACAO>000,14</DEF-PARTICIPACAO><DEF-ASSINA-EMPRESA>N</DEF-ASSINA-EMPRESA><DEF-INDICADOR-DEBITO>Não</DEF-INDICADOR-DEBITO><DEF-INDICADOR-FRAUDE>Não</DEF-INDICADOR-FRAUDE></DEF-SOCIO><DEF-SOCIO><DEF-NOME-EMPRESA>S VELAME ADM DE RECURSOS E PARTICIPACOES SA</DEF-NOME-EMPRESA><DEF-CPF-CNPJ>07048386000150</DEF-CPF-CNPJ><DEF-TIPO-DOCUMENTO>2</DEF-TIPO-DOCUMENTO><DEF-SITUACAO-DOCUMENTO>Ativo</DEF-SITUACAO-DOCUMENTO><DEF-PARTICIPACAO>018,16</DEF-PARTICIPACAO><DEF-ASSINA-EMPRESA>N</DEF-ASSINA-EMPRESA><DEF-INDICADOR-DEBITO>Não</DEF-INDICADOR-DEBITO><DEF-INDICADOR-FRAUDE>Não</DEF-INDICADOR-FRAUDE></DEF-SOCIO><DEF-SOCIO><DEF-NOME-EMPRESA>LTS TRADING COMPANY LLC</DEF-NOME-EMPRESA><DEF-CPF-CNPJ>11847660000129</DEF-CPF-CNPJ><DEF-TIPO-DOCUMENTO>2</DEF-TIPO-DOCUMENTO><DEF-SITUACAO-DOCUMENTO>Ativo</DEF-SITUACAO-DOCUMENTO><DEF-PARTICIPACAO>000,02</DEF-PARTICIPACAO><DEF-ASSINA-EMPRESA>N</DEF-ASSINA-EMPRESA><DEF-INDICADOR-DEBITO>Não</DEF-INDICADOR-DEBITO><DEF-INDICADOR-FRAUDE>Não</DEF-INDICADOR-FRAUDE></DEF-SOCIO><DEF-SOCIO><DEF-NOME-EMPRESA>CARLOS ALBERTO DA VEIGA SICUPIRA</DEF-NOME-EMPRESA><DEF-CPF-CNPJ>00004189531715</DEF-CPF-CNPJ><DEF-TIPO-DOCUMENTO>1</DEF-TIPO-DOCUMENTO><DEF-SITUACAO-DOCUMENTO>Regular</DEF-SITUACAO-DOCUMENTO><DEF-PARTICIPACAO>002,96</DEF-PARTICIPACAO><DEF-DATA-ENTRADA>18/06/1998</DEF-DATA-ENTRADA><DEF-ASSINA-EMPRESA>N</DEF-ASSINA-EMPRESA><DEF-INDICADOR-DEBITO>Não</DEF-INDICADOR-DEBITO><DEF-INDICADOR-FRAUDE>Não</DEF-INDICADOR-FRAUDE></DEF-SOCIO><DEF-SOCIO><DEF-NOME-EMPRESA>TOBIAS CEPELOWICZ</DEF-NOME-EMPRESA><DEF-CPF-CNPJ>00000652733700</DEF-CPF-CNPJ><DEF-TIPO-DOCUMENTO>1</DEF-TIPO-DOCUMENTO><DEF-SITUACAO-DOCUMENTO>Regular</DEF-SITUACAO-DOCUMENTO><DEF-PARTICIPACAO>002,04</DEF-PARTICIPACAO><DEF-ASSINA-EMPRESA>N</DEF-ASSINA-EMPRESA><DEF-INDICADOR-DEBITO>Não</DEF-INDICADOR-DEBITO><DEF-INDICADOR-FRAUDE>Não</DEF-INDICADOR-FRAUDE></DEF-SOCIO></DEF-SOCIOS><DEF-ADMINISTRADORES><DEF-HABILITA>true</DEF-HABILITA><DEF-ADMINISTRADOR><DEF-NOME>MARCELO PINTO</DEF-NOME><DEF-CPF>00080664059791</DEF-CPF><DEF-ENTRADA>05/09/2018</DEF-ENTRADA><DEF-MANDATO>Indeterminado</DEF-MANDATO><DEF-CARGO>DIRETOR</DEF-CARGO><DEF-SITUACAO-CPF>Regular</DEF-SITUACAO-CPF><DEF-INDICADOR-DEBITO>Não</DEF-INDICADOR-DEBITO><DEF-INDICADOR-FRAUDE>Não</DEF-INDICADOR-FRAUDE></DEF-ADMINISTRADOR><DEF-ADMINISTRADOR><DEF-NOME>ANDREA SILVA BARRA</DEF-NOME><DEF-CPF>00056383894587</DEF-CPF><DEF-ENTRADA>05/09/2018</DEF-ENTRADA><DEF-MANDATO>Indeterminado</DEF-MANDATO><DEF-CARGO>DIRETOR</DEF-CARGO><DEF-SITUACAO-CPF>Regular</DEF-SITUACAO-CPF><DEF-INDICADOR-DEBITO>Não</DEF-INDICADOR-DEBITO><DEF-INDICADOR-FRAUDE>Não</DEF-INDICADOR-FRAUDE></DEF-ADMINISTRADOR><DEF-ADMINISTRADOR><DEF-NOME>MILENA DE ANDRADE SACRAMENTO</DEF-NOME><DEF-CPF>00011681170701</DEF-CPF><DEF-ENTRADA>15/05/2018</DEF-ENTRADA><DEF-MANDATO>Indeterminado</DEF-MANDATO><DEF-CARGO>DIRETOR</DEF-CARGO><DEF-SITUACAO-CPF>Regular</DEF-SITUACAO-CPF><DEF-INDICADOR-DEBITO>Não</DEF-INDICADOR-DEBITO><DEF-INDICADOR-FRAUDE>Não</DEF-INDICADOR-FRAUDE></DEF-ADMINISTRADOR><DEF-ADMINISTRADOR><DEF-NOME>JOAO GUERRA DUARTE NETO</DEF-NOME><DEF-CPF>00087263289768</DEF-CPF><DEF-ENTRADA>14/10/2013</DEF-ENTRADA><DEF-MANDATO>Indeterminado</DEF-MANDATO><DEF-CARGO>DIRETOR</DEF-CARGO><DEF-SITUACAO-CPF>Regular</DEF-SITUACAO-CPF><DEF-INDICADOR-DEBITO>Não</DEF-INDICADOR-DEBITO><DEF-INDICADOR-FRAUDE>Não</DEF-INDICADOR-FRAUDE></DEF-ADMINISTRADOR><DEF-ADMINISTRADOR><DEF-NOME>WELINGTON DE ALMEIDA SOUZA</DEF-NOME><DEF-CPF>00084805307749</DEF-CPF><DEF-ENTRADA>14/10/2013</DEF-ENTRADA><DEF-MANDATO>Indeterminado</DEF-MANDATO><DEF-CARGO>DIRETOR</DEF-CARGO><DEF-SITUACAO-CPF>Regular</DEF-SITUACAO-CPF><DEF-INDICADOR-DEBITO>Não</DEF-INDICADOR-DEBITO><DEF-INDICADOR-FRAUDE>Não</DEF-INDICADOR-FRAUDE></DEF-ADMINISTRADOR><DEF-ADMINISTRADOR><DEF-NOME>CARLOS EDUARDO ROSALBA PADILHA</DEF-NOME><DEF-CPF>00002394252782</DEF-CPF><DEF-ENTRADA>19/07/2012</DEF-ENTRADA><DEF-MANDATO>Indeterminado</DEF-MANDATO><DEF-CARGO>DIRETOR</DEF-CARGO><DEF-SITUACAO-CPF>Regular</DEF-SITUACAO-CPF><DEF-INDICADOR-DEBITO>Não</DEF-INDICADOR-DEBITO><DEF-INDICADOR-FRAUDE>Não</DEF-INDICADOR-FRAUDE></DEF-ADMINISTRADOR><DEF-ADMINISTRADOR><DEF-NOME>MARIA CHRISTINA FERREIRA NASCIMENTO</DEF-NOME><DEF-CPF>00073993018753</DEF-CPF><DEF-ENTRADA>08/04/2011</DEF-ENTRADA><DEF-MANDATO>Indeterminado</DEF-MANDATO><DEF-CARGO>DIRETOR</DEF-CARGO><DEF-SITUACAO-CPF>Regular</DEF-SITUACAO-CPF><DEF-INDICADOR-DEBITO>Não</DEF-INDICADOR-DEBITO><DEF-INDICADOR-FRAUDE>Não</DEF-INDICADOR-FRAUDE></DEF-ADMINISTRADOR><DEF-ADMINISTRADOR><DEF-NOME>MARCIO CRUZ MEIRELLES</DEF-NOME><DEF-CPF>00002532597704</DEF-CPF><DEF-ENTRADA>19/08/2009</DEF-ENTRADA><DEF-MANDATO>Indeterminado</DEF-MANDATO><DEF-CARGO>DIRETOR</DEF-CARGO><DEF-SITUACAO-CPF>Regular</DEF-SITUACAO-CPF><DEF-INDICADOR-DEBITO>Não</DEF-INDICADOR-DEBITO><DEF-INDICADOR-FRAUDE>Não</DEF-INDICADOR-FRAUDE></DEF-ADMINISTRADOR><DEF-ADMINISTRADOR><DEF-NOME>JOSE TIMOTHEO DE BARROS</DEF-NOME><DEF-CPF>00000326412735</DEF-CPF><DEF-ENTRADA>19/08/2009</DEF-ENTRADA><DEF-MANDATO>Indeterminado</DEF-MANDATO><DEF-CARGO>DIRETOR</DEF-CARGO><DEF-SITUACAO-CPF>Regular</DEF-SITUACAO-CPF><DEF-INDICADOR-DEBITO>Não</DEF-INDICADOR-DEBITO><DEF-INDICADOR-FRAUDE>Não</DEF-INDICADOR-FRAUDE></DEF-ADMINISTRADOR><DEF-ADMINISTRADOR><DEF-NOME>CELSO ALVES FERREIRA LOURO</DEF-NOME><DEF-CPF>00039619273753</DEF-CPF><DEF-ENTRADA>03/06/2004</DEF-ENTRADA><DEF-MANDATO>Indeterminado</DEF-MANDATO><DEF-CARGO>DIRETOR</DEF-CARGO><DEF-SITUACAO-CPF>Regular</DEF-SITUACAO-CPF><DEF-INDICADOR-DEBITO>Não</DEF-INDICADOR-DEBITO><DEF-INDICADOR-FRAUDE>Não</DEF-INDICADOR-FRAUDE></DEF-ADMINISTRADOR></DEF-ADMINISTRADORES><DEF-PARTICIPACOES-SOCIOS-ADM-OUTRAS-EMPRESAS><DEF-HABILITA>true</DEF-HABILITA><DEF-SOCIO><DEF-NOME-SOCIO>CARLOS ALBERTO DA VEIGA SICUPIRA</DEF-NOME-SOCIO><DEF-CPF-CNPJ>00004189531715</DEF-CPF-CNPJ><DEF-TIPO-DOCUMENTO>1</DEF-TIPO-DOCUMENTO><DEF-SOCIOS-PARTICIPANTES><DEF-RAZAO-SOCIAL>OCEAN EXPLORER DO BRASIL LTDA</DEF-RAZAO-SOCIAL><DEF-CNPJ>04169436000160</DEF-CNPJ><DEF-SITUACAO-CNPJ>Ativo</DEF-SITUACAO-CNPJ><DEF-PARTICIPACAO>099,99</DEF-PARTICIPACAO><DEF-ENTRADA>11/08/2020</DEF-ENTRADA><DEF-INDICADOR-DEBITO>Não</DEF-INDICADOR-DEBITO><DEF-INDICADOR-FRAUDE>Não</DEF-INDICADOR-FRAUDE></DEF-SOCIOS-PARTICIPANTES><DEF-SOCIOS-PARTICIPANTES><DEF-RAZAO-SOCIAL>SANTA EDWIGES PARTICIPACOES LTDA</DEF-RAZAO-SOCIAL><DEF-CNPJ>07752691000129</DEF-CNPJ><DEF-SITUACAO-CNPJ>Ativo</DEF-SITUACAO-CNPJ><DEF-PARTICIPACAO>099,99</DEF-PARTICIPACAO><DEF-ENTRADA>28/12/2006</DEF-ENTRADA><DEF-INDICADOR-DEBITO>Não</DEF-INDICADOR-DEBITO><DEF-INDICADOR-FRAUDE>Não</DEF-INDICADOR-FRAUDE></DEF-SOCIOS-PARTICIPANTES><DEF-SOCIOS-PARTICIPANTES><DEF-RAZAO-SOCIAL>ANGRAMAR PARTICIPACOES LTDA</DEF-RAZAO-SOCIAL><DEF-CNPJ>05617495000116</DEF-CNPJ><DEF-SITUACAO-CNPJ>Ativo</DEF-SITUACAO-CNPJ><DEF-PARTICIPACAO>033,33</DEF-PARTICIPACAO><DEF-ENTRADA>26/03/2003</DEF-ENTRADA><DEF-INDICADOR-DEBITO>Não</DEF-INDICADOR-DEBITO><DEF-INDICADOR-FRAUDE>Não</DEF-INDICADOR-FRAUDE></DEF-SOCIOS-PARTICIPANTES><DEF-SOCIOS-PARTICIPANTES><DEF-RAZAO-SOCIAL>FIGAR GESTAO DE BENS LTDA</DEF-RAZAO-SOCIAL><DEF-CNPJ>32230245000100</DEF-CNPJ><DEF-SITUACAO-CNPJ>Ativo</DEF-SITUACAO-CNPJ><DEF-PARTICIPACAO>005,91</DEF-PARTICIPACAO><DEF-ENTRADA>20/11/1998</DEF-ENTRADA><DEF-INDICADOR-DEBITO>Não</DEF-INDICADOR-DEBITO><DEF-INDICADOR-FRAUDE>Não</DEF-INDICADOR-FRAUDE></DEF-SOCIOS-PARTICIPANTES><DEF-SOCIOS-PARTICIPANTES><DEF-RAZAO-SOCIAL>MAURITI ADMINISTRADORA DE ATIVOS LTDA</DEF-RAZAO-SOCIAL><DEF-CNPJ>71726517000100</DEF-CNPJ><DEF-SITUACAO-CNPJ>Ativo</DEF-SITUACAO-CNPJ><DEF-PARTICIPACAO>000,04</DEF-PARTICIPACAO><DEF-ENTRADA>01/07/2005</DEF-ENTRADA><DEF-INDICADOR-DEBITO>Não</DEF-INDICADOR-DEBITO><DEF-INDICADOR-FRAUDE>Não</DEF-INDICADOR-FRAUDE></DEF-SOCIOS-PARTICIPANTES><DEF-SOCIOS-PARTICIPANTES><DEF-RAZAO-SOCIAL>INSTITUTO BRAVA</DEF-RAZAO-SOCIAL><DEF-CNPJ>08103026000177</DEF-CNPJ><DEF-SITUACAO-CNPJ>Ativo</DEF-SITUACAO-CNPJ><DEF-PARTICIPACAO>000,00</DEF-PARTICIPACAO><DEF-ENTRADA>01/07/2005</DEF-ENTRADA><DEF-INDICADOR-DEBITO>Sim</DEF-INDICADOR-DEBITO><DEF-INDICADOR-FRAUDE>Não</DEF-INDICADOR-FRAUDE></DEF-SOCIOS-PARTICIPANTES><DEF-SOCIOS-PARTICIPANTES><DEF-RAZAO-SOCIAL>LASA TAXI AEREO LTDA</DEF-RAZAO-SOCIAL><DEF-CNPJ>39109038000132</DEF-CNPJ><DEF-SITUACAO-CNPJ>Baixado</DEF-SITUACAO-CNPJ><DEF-PARTICIPACAO>075,00</DEF-PARTICIPACAO><DEF-ENTRADA>05/09/1990</DEF-ENTRADA><DEF-INDICADOR-DEBITO>Não</DEF-INDICADOR-DEBITO><DEF-INDICADOR-FRAUDE>Não</DEF-INDICADOR-FRAUDE></DEF-SOCIOS-PARTICIPANTES><DEF-SOCIOS-PARTICIPANTES><DEF-RAZAO-SOCIAL>GGP COMERCIO E INDUSTRIA LTDA</DEF-RAZAO-SOCIAL><DEF-CNPJ>32230260000140</DEF-CNPJ><DEF-SITUACAO-CNPJ>Baixado</DEF-SITUACAO-CNPJ><DEF-PARTICIPACAO>050,00</DEF-PARTICIPACAO><DEF-ENTRADA>28/10/1992</DEF-ENTRADA><DEF-INDICADOR-DEBITO>Não</DEF-INDICADOR-DEBITO><DEF-INDICADOR-FRAUDE>Não</DEF-INDICADOR-FRAUDE></DEF-SOCIOS-PARTICIPANTES><DEF-SOCIOS-PARTICIPANTES><DEF-RAZAO-SOCIAL>E55 EMPREENDIMENTOS LTDA</DEF-RAZAO-SOCIAL><DEF-CNPJ>04876803000165</DEF-CNPJ><DEF-SITUACAO-CNPJ>Baixado</DEF-SITUACAO-CNPJ><DEF-PARTICIPACAO>000,01</DEF-PARTICIPACAO><DEF-ENTRADA>05/08/2002</DEF-ENTRADA><DEF-INDICADOR-DEBITO>Não</DEF-INDICADOR-DEBITO><DEF-INDICADOR-FRAUDE>Não</DEF-INDICADOR-FRAUDE></DEF-SOCIOS-PARTICIPANTES><DEF-SOCIOS-PARTICIPANTES><DEF-RAZAO-SOCIAL>SANTA ESTELA PARTICIPACOES S/A</DEF-RAZAO-SOCIAL><DEF-CNPJ>04007374000190</DEF-CNPJ><DEF-SITUACAO-CNPJ>Baixado</DEF-SITUACAO-CNPJ><DEF-PARTICIPACAO>000,00</DEF-PARTICIPACAO><DEF-ENTRADA>25/05/2004</DEF-ENTRADA><DEF-INDICADOR-DEBITO>Não</DEF-INDICADOR-DEBITO><DEF-INDICADOR-FRAUDE>Não</DEF-INDICADOR-FRAUDE></DEF-SOCIOS-PARTICIPANTES></DEF-SOCIO></DEF-PARTICIPACOES-SOCIOS-ADM-OUTRAS-EMPRESAS><DEF-PARTICIPACOES-EMPRESAS-CONSULTADAS><DEF-HABILITA>false</DEF-HABILITA><DEF-PARTICIPACAO-EMPRESA-CONSULTADA><DEF-RAZAO-SOCIAL-PARTICIPADA>FREIJO ADMINISTRACAO E PARTICIPACOES LTDA</DEF-RAZAO-SOCIAL-PARTICIPADA><DEF-CNPJ-PARTICIPADA>08596150000111</DEF-CNPJ-PARTICIPADA><DEF-SITUACAO-CNPJ>Ativo</DEF-SITUACAO-CNPJ><DEF-PARTICIPACAO>099,99</DEF-PARTICIPACAO><DEF-ENTRADA>17/11/2010</DEF-ENTRADA><DEF-INDICADOR-DEBITO>Não</DEF-INDICADOR-DEBITO><DEF-INDICADOR-FRAUDE>Não</DEF-INDICADOR-FRAUDE></DEF-PARTICIPACAO-EMPRESA-CONSULTADA><DEF-PARTICIPACAO-EMPRESA-CONSULTADA><DEF-RAZAO-SOCIAL-PARTICIPADA>B2W COMPANHIA DIGITAL</DEF-RAZAO-SOCIAL-PARTICIPADA><DEF-CNPJ-PARTICIPADA>00776574000156</DEF-CNPJ-PARTICIPADA><DEF-SITUACAO-CNPJ>Ativo</DEF-SITUACAO-CNPJ><DEF-PARTICIPACAO>061,47</DEF-PARTICIPACAO><DEF-INDICADOR-DEBITO>Sim</DEF-INDICADOR-DEBITO><DEF-INDICADOR-FRAUDE>Não</DEF-INDICADOR-FRAUDE></DEF-PARTICIPACAO-EMPRESA-CONSULTADA><DEF-PARTICIPACAO-EMPRESA-CONSULTADA><DEF-RAZAO-SOCIAL-PARTICIPADA>QSM DISTRIBUIDORA E LOGISTICA LTDA</DEF-RAZAO-SOCIAL-PARTICIPADA><DEF-CNPJ-PARTICIPADA>08060852000186</DEF-CNPJ-PARTICIPADA><DEF-SITUACAO-CNPJ>Ativo</DEF-SITUACAO-CNPJ><DEF-PARTICIPACAO>000,00</DEF-PARTICIPACAO><DEF-ENTRADA>11/07/2013</DEF-ENTRADA><DEF-INDICADOR-DEBITO>Não</DEF-INDICADOR-DEBITO><DEF-INDICADOR-FRAUDE>Não</DEF-INDICADOR-FRAUDE></DEF-PARTICIPACAO-EMPRESA-CONSULTADA><DEF-PARTICIPACAO-EMPRESA-CONSULTADA><DEF-RAZAO-SOCIAL-PARTICIPADA>ST IMPORTACOES LTDA</DEF-RAZAO-SOCIAL-PARTICIPADA><DEF-CNPJ-PARTICIPADA>02867220000142</DEF-CNPJ-PARTICIPADA><DEF-SITUACAO-CNPJ>Ativo</DEF-SITUACAO-CNPJ><DEF-PARTICIPACAO>000,00</DEF-PARTICIPACAO><DEF-ENTRADA>24/10/2006</DEF-ENTRADA><DEF-INDICADOR-DEBITO>Não</DEF-INDICADOR-DEBITO><DEF-INDICADOR-FRAUDE>Não</DEF-INDICADOR-FRAUDE></DEF-PARTICIPACAO-EMPRESA-CONSULTADA><DEF-PARTICIPACAO-EMPRESA-CONSULTADA><DEF-RAZAO-SOCIAL-PARTICIPADA>LOJAS AMERICANAS HOME SHOPPING LTDA</DEF-RAZAO-SOCIAL-PARTICIPADA><DEF-CNPJ-PARTICIPADA>29775079000104</DEF-CNPJ-PARTICIPADA><DEF-SITUACAO-CNPJ>Baixado</DEF-SITUACAO-CNPJ><DEF-PARTICIPACAO>099,90</DEF-PARTICIPACAO><DEF-ENTRADA>22/10/1985</DEF-ENTRADA><DEF-INDICADOR-DEBITO>Não</DEF-INDICADOR-DEBITO><DEF-INDICADOR-FRAUDE>Não</DEF-INDICADOR-FRAUDE></DEF-PARTICIPACAO-EMPRESA-CONSULTADA><DEF-PARTICIPACAO-EMPRESA-CONSULTADA><DEF-RAZAO-SOCIAL-PARTICIPADA>REPORT ADMINISTRACAO E PARTICIPACOES LTDA</DEF-RAZAO-SOCIAL-PARTICIPADA><DEF-CNPJ-PARTICIPADA>01783889000193</DEF-CNPJ-PARTICIPADA><DEF-SITUACAO-CNPJ>Baixado</DEF-SITUACAO-CNPJ><DEF-PARTICIPACAO>099,00</DEF-PARTICIPACAO><DEF-ENTRADA>19/02/1997</DEF-ENTRADA><DEF-INDICADOR-DEBITO>Não</DEF-INDICADOR-DEBITO><DEF-INDICADOR-FRAUDE>Não</DEF-INDICADOR-FRAUDE></DEF-PARTICIPACAO-EMPRESA-CONSULTADA><DEF-PARTICIPACAO-EMPRESA-CONSULTADA><DEF-RAZAO-SOCIAL-PARTICIPADA>LASA TAXI AEREO LTDA</DEF-RAZAO-SOCIAL-PARTICIPADA><DEF-CNPJ-PARTICIPADA>39109038000132</DEF-CNPJ-PARTICIPADA><DEF-SITUACAO-CNPJ>Baixado</DEF-SITUACAO-CNPJ><DEF-PARTICIPACAO>025,00</DEF-PARTICIPACAO><DEF-ENTRADA>05/09/1990</DEF-ENTRADA><DEF-INDICADOR-DEBITO>Não</DEF-INDICADOR-DEBITO><DEF-INDICADOR-FRAUDE>Não</DEF-INDICADOR-FRAUDE></DEF-PARTICIPACAO-EMPRESA-CONSULTADA><DEF-PARTICIPACAO-EMPRESA-CONSULTADA><DEF-RAZAO-SOCIAL-PARTICIPADA>AGRO LASA COMERCIO LTDA</DEF-RAZAO-SOCIAL-PARTICIPADA><DEF-CNPJ-PARTICIPADA>36073955000116</DEF-CNPJ-PARTICIPADA><DEF-SITUACAO-CNPJ>Baixado</DEF-SITUACAO-CNPJ><DEF-PARTICIPACAO>000,00</DEF-PARTICIPACAO><DEF-ENTRADA>16/02/1990</DEF-ENTRADA><DEF-INDICADOR-DEBITO>Não</DEF-INDICADOR-DEBITO><DEF-INDICADOR-FRAUDE>Não</DEF-INDICADOR-FRAUDE></DEF-PARTICIPACAO-EMPRESA-CONSULTADA></DEF-PARTICIPACOES-EMPRESAS-CONSULTADAS><DEF-CONSULTAS><DEF-QUANTIDADE-TOTAL>1566</DEF-QUANTIDADE-TOTAL><DEF-PERIODO-INICIAL>01/08/2019</DEF-PERIODO-INICIAL><DEF-PERIODO-FINAL>01/08/2020</DEF-PERIODO-FINAL><DEF-CONSULTAS-MES><DEF-MES-ANO>082020</DEF-MES-ANO><DEF-QUANTIDADE>17</DEF-QUANTIDADE></DEF-CONSULTAS-MES><DEF-CONSULTAS-MES><DEF-MES-ANO>072020</DEF-MES-ANO><DEF-QUANTIDADE>113</DEF-QUANTIDADE></DEF-CONSULTAS-MES><DEF-CONSULTAS-MES><DEF-MES-ANO>062020</DEF-MES-ANO><DEF-QUANTIDADE>35</DEF-QUANTIDADE></DEF-CONSULTAS-MES><DEF-CONSULTAS-MES><DEF-MES-ANO>052020</DEF-MES-ANO><DEF-QUANTIDADE>24</DEF-QUANTIDADE></DEF-CONSULTAS-MES><DEF-CONSULTAS-MES><DEF-MES-ANO>042020</DEF-MES-ANO><DEF-QUANTIDADE>33</DEF-QUANTIDADE></DEF-CONSULTAS-MES><DEF-CONSULTAS-MES><DEF-MES-ANO>032020</DEF-MES-ANO><DEF-QUANTIDADE>25</DEF-QUANTIDADE></DEF-CONSULTAS-MES><DEF-CONSULTAS-MES><DEF-MES-ANO>022020</DEF-MES-ANO><DEF-QUANTIDADE>21</DEF-QUANTIDADE></DEF-CONSULTAS-MES><DEF-CONSULTAS-MES><DEF-MES-ANO>012020</DEF-MES-ANO><DEF-QUANTIDADE>43</DEF-QUANTIDADE></DEF-CONSULTAS-MES><DEF-CONSULTAS-MES><DEF-MES-ANO>122019</DEF-MES-ANO><DEF-QUANTIDADE>63</DEF-QUANTIDADE></DEF-CONSULTAS-MES><DEF-CONSULTAS-MES><DEF-MES-ANO>112019</DEF-MES-ANO><DEF-QUANTIDADE>380</DEF-QUANTIDADE></DEF-CONSULTAS-MES><DEF-CONSULTAS-MES><DEF-MES-ANO>102019</DEF-MES-ANO><DEF-QUANTIDADE>629</DEF-QUANTIDADE></DEF-CONSULTAS-MES><DEF-CONSULTAS-MES><DEF-MES-ANO>092019</DEF-MES-ANO><DEF-QUANTIDADE>70</DEF-QUANTIDADE></DEF-CONSULTAS-MES><DEF-CONSULTAS-MES><DEF-MES-ANO>082019</DEF-MES-ANO><DEF-QUANTIDADE>113</DEF-QUANTIDADE></DEF-CONSULTAS-MES><DEF-ULTIMAS-CONSULTAS><DEF-HABILITA>true</DEF-HABILITA><DEF-CONSULTA><DEF-DATA>19/08/2020</DEF-DATA><DEF-RAZAO-SOCIAL>NAOR DISTR DE GENEROS ALIMENTICIOS L</DEF-RAZAO-SOCIAL><DEF-CNPJ>04083947000164</DEF-CNPJ></DEF-CONSULTA><DEF-CONSULTA><DEF-DATA>19/08/2020</DEF-DATA><DEF-RAZAO-SOCIAL>JB FIRE</DEF-RAZAO-SOCIAL><DEF-CNPJ>27233695000108</DEF-CNPJ></DEF-CONSULTA><DEF-CONSULTA><DEF-DATA>19/08/2020</DEF-DATA><DEF-RAZAO-SOCIAL>SC-PAC/SHOPPINHG VIA CATARINA</DEF-RAZAO-SOCIAL><DEF-CNPJ>12202724000105</DEF-CNPJ></DEF-CONSULTA><DEF-CONSULTA><DEF-DATA>17/08/2020</DEF-DATA><DEF-RAZAO-SOCIAL>CREDITSAFE UK</DEF-RAZAO-SOCIAL><DEF-CNPJ>05648842000178</DEF-CNPJ></DEF-CONSULTA><DEF-CONSULTA><DEF-DATA>12/08/2020</DEF-DATA><DEF-RAZAO-SOCIAL>BEL FIX IMP LTDA</DEF-RAZAO-SOCIAL><DEF-CNPJ>01972193000105</DEF-CNPJ></DEF-CONSULTA></DEF-ULTIMAS-CONSULTAS></DEF-CONSULTAS><DEF-PENDENCIAS-RESTRICOES><DEF-TOTAL-PENDENCIAS>16</DEF-TOTAL-PENDENCIAS><DEF-HABILITA>true</DEF-HABILITA><DEF-TOTAL-CREDORES>9</DEF-TOTAL-CREDORES><DEF-VALOR>316833,89</DEF-VALOR><DEF-PERIODO-INICIAL>30/06/2017</DEF-PERIODO-INICIAL><DEF-PERIODO-FINAL>06/04/2020</DEF-PERIODO-FINAL><DEF-VALOR-PRIMEIRO>37,89</DEF-VALOR-PRIMEIRO><DEF-DATA-PRIMEIRO>30/06/2017</DEF-DATA-PRIMEIRO><DEF-VALOR-MAIOR>156460,92</DEF-VALOR-MAIOR><DEF-DATA-MAIOR>15/02/2018</DEF-DATA-MAIOR><DEF-ULTIMAS-OCORRENCIAS><DEF-PENDENCIA-RESTRICAO><DEF-INFORMANTE>PR-CTA/HDS SISTEMAS DE ENER</DEF-INFORMANTE><DEF-TIPO>DP</DEF-TIPO><DEF-CIDADE>CURITIBA</DEF-CIDADE><DEF-UF>PR</DEF-UF><DEF-DOCUMENTO-ORIGEM>20354</DEF-DOCUMENTO-ORIGEM><DEF-DATA-DEBITO>06/04/2020</DEF-DATA-DEBITO><DEF-DISPONIVEL-EM>04/06/2020</DEF-DISPONIVEL-EM><DEF-VALOR>1675,78</DEF-VALOR></DEF-PENDENCIA-RESTRICAO><DEF-PENDENCIA-RESTRICAO><DEF-INFORMANTE>PR-CTA/HDS SISTEMAS DE ENER</DEF-INFORMANTE><DEF-TIPO>DP</DEF-TIPO><DEF-CIDADE>CURITIBA</DEF-CIDADE><DEF-UF>PR</DEF-UF><DEF-DOCUMENTO-ORIGEM>19157</DEF-DOCUMENTO-ORIGEM><DEF-DATA-DEBITO>09/01/2020</DEF-DATA-DEBITO><DEF-DISPONIVEL-EM>26/01/2020</DEF-DISPONIVEL-EM><DEF-VALOR>762,8</DEF-VALOR></DEF-PENDENCIA-RESTRICAO><DEF-PENDENCIA-RESTRICAO><DEF-INFORMANTE>COMPANHIA DE SANEAMENTO DO PARA</DEF-INFORMANTE><DEF-TIPO>XX</DEF-TIPO><DEF-CIDADE>SCPC SAO PAULO</DEF-CIDADE><DEF-UF>SP</DEF-UF><DEF-DOCUMENTO-ORIGEM>3711030</DEF-DOCUMENTO-ORIGEM><DEF-DATA-DEBITO>14/07/2019</DEF-DATA-DEBITO><DEF-DISPONIVEL-EM>15/08/2019</DEF-DISPONIVEL-EM><DEF-VALOR>5463,09</DEF-VALOR></DEF-PENDENCIA-RESTRICAO><DEF-PENDENCIA-RESTRICAO><DEF-INFORMANTE>SP-LRA/LINKMAIS INTERNET</DEF-INFORMANTE><DEF-TIPO>DP</DEF-TIPO><DEF-CIDADE>LIMEIRA</DEF-CIDADE><DEF-UF>SP</DEF-UF><DEF-DOCUMENTO-ORIGEM>22597MP</DEF-DOCUMENTO-ORIGEM><DEF-DATA-DEBITO>22/04/2019</DEF-DATA-DEBITO><DEF-DISPONIVEL-EM>07/10/2019</DEF-DISPONIVEL-EM><DEF-VALOR>167,4</DEF-VALOR></DEF-PENDENCIA-RESTRICAO><DEF-PENDENCIA-RESTRICAO><DEF-INFORMANTE>SP-LRA/LINKMAIS INTERNET</DEF-INFORMANTE><DEF-TIPO>DP</DEF-TIPO><DEF-CIDADE>LIMEIRA</DEF-CIDADE><DEF-UF>SP</DEF-UF><DEF-DOCUMENTO-ORIGEM>22597</DEF-DOCUMENTO-ORIGEM><DEF-DATA-DEBITO>22/03/2019</DEF-DATA-DEBITO><DEF-DISPONIVEL-EM>07/10/2019</DEF-DISPONIVEL-EM><DEF-VALOR>279</DEF-VALOR></DEF-PENDENCIA-RESTRICAO></DEF-ULTIMAS-OCORRENCIAS></DEF-PENDENCIAS-RESTRICOES><DEF-CHEQUES-SEM-FUNDO><DEF-MENSAGEM>Nada Consta.</DEF-MENSAGEM></DEF-CHEQUES-SEM-FUNDO><DEF-CHEQUES-SUSTADOS><DEF-MENSAGEM>Nada Consta.</DEF-MENSAGEM></DEF-CHEQUES-SUSTADOS><DEF-CHEQUES-DEVOLVIDOS-INFORMADOS-USUARIO><DEF-MENSAGEM>Nada Consta.</DEF-MENSAGEM></DEF-CHEQUES-DEVOLVIDOS-INFORMADOS-USUARIO><DEF-PROTESTOS><DEF-TOTAL-PROTESTOS>219</DEF-TOTAL-PROTESTOS><DEF-VALOR-TOTAL>165187,81</DEF-VALOR-TOTAL><DEF-DATA-PRIMEIRO>11/07/2018</DEF-DATA-PRIMEIRO><DEF-VALOR-PRIMEIRO>675,34</DEF-VALOR-PRIMEIRO><DEF-DATA-MAIOR>10/03/2020</DEF-DATA-MAIOR><DEF-VALOR-MAIOR>51000</DEF-VALOR-MAIOR><DEF-HABILITA>true</DEF-HABILITA><DEF-ULTIMAS-OCORRENCIAS><DEF-PROTESTO><DEF-DATA>30/06/2020</DEF-DATA><DEF-VENCIMENTO>08/06/2020</DEF-VENCIMENTO><DEF-CARTORIO>1</DEF-CARTORIO><DEF-CIDADE>RIO DE JANEIRO</DEF-CIDADE><DEF-ESTADO>RJ</DEF-ESTADO><DEF-VALOR>7776</DEF-VALOR></DEF-PROTESTO><DEF-PROTESTO><DEF-DATA>25/06/2020</DEF-DATA><DEF-VENCIMENTO>09/04/2020</DEF-VENCIMENTO><DEF-CARTORIO>3</DEF-CARTORIO><DEF-CIDADE>NILOPOLIS</DEF-CIDADE><DEF-ESTADO>RJ</DEF-ESTADO><DEF-VALOR>5065</DEF-VALOR></DEF-PROTESTO><DEF-PROTESTO><DEF-DATA>16/06/2020</DEF-DATA><DEF-VENCIMENTO>06/04/2020</DEF-VENCIMENTO><DEF-CARTORIO>1</DEF-CARTORIO><DEF-CIDADE>TUTOIA</DEF-CIDADE><DEF-ESTADO>MA</DEF-ESTADO><DEF-VALOR>1279,83</DEF-VALOR></DEF-PROTESTO><DEF-PROTESTO><DEF-DATA>17/03/2020</DEF-DATA><DEF-VENCIMENTO>03/03/2020</DEF-VENCIMENTO><DEF-CARTORIO>3</DEF-CARTORIO><DEF-CIDADE>RIO DE JANEIRO</DEF-CIDADE><DEF-ESTADO>RJ</DEF-ESTADO><DEF-VALOR>140,28</DEF-VALOR></DEF-PROTESTO><DEF-PROTESTO><DEF-DATA>17/03/2020</DEF-DATA><DEF-VENCIMENTO>03/03/2020</DEF-VENCIMENTO><DEF-CARTORIO>3</DEF-CARTORIO><DEF-CIDADE>RIO DE JANEIRO</DEF-CIDADE><DEF-ESTADO>RJ</DEF-ESTADO><DEF-VALOR>837,99</DEF-VALOR></DEF-PROTESTO></DEF-ULTIMAS-OCORRENCIAS></DEF-PROTESTOS></DEFINE-RESPOSTA></RESPOSTA></SPCA-XML>";
			
			br = new BufferedReader(new StringReader(resposta));
			
			//Faco o parse aqui xml->classe java				
			JAXBContext jaxbContext = JAXBContext.newInstance(SPCAXML.class);
			Unmarshaller jaxbUnmarshaller = jaxbContext.createUnmarshaller();
			obj = (SPCAXML) jaxbUnmarshaller.unmarshal(br);

			empTop.setSpcaxml(obj);

			br.close();
			con.disconnect();
		} catch (MalformedURLException e) {
			cache.apagaCache(protocolo);
			log.registro(protocolo, "ERRO", e.getMessage());
			empTop.setStatusRetorno((byte) 1);
			empTop.setMensagemRetorno("Erro na comunicacao com o Fornecedor 1");			
		} catch (IOException e) {
			cache.apagaCache(protocolo);
			log.registro(protocolo, "ERRO", e.getMessage());
			empTop.setStatusRetorno((byte) 1);
			empTop.setMensagemRetorno("Erro na comunicacao com o Fornecedor 1");			
		} catch (JAXBException e) {
			cache.apagaCache(protocolo);
			log.registro(protocolo, "ERRO", e.getMessage());
			empTop.setStatusRetorno((byte) 1);
			empTop.setMensagemRetorno("Erro na comunicacao com o Fornecedor 1");						
		}
		return empTop;
	}	
		
	
}
