//
// Este arquivo foi gerado pela Arquitetura JavaTM para Implementação de Referência (JAXB) de Bind XML, v2.2.8-b130911.1802 
// Consulte <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Todas as modificações neste arquivo serão perdidas após a recompilação do esquema de origem. 
// Gerado em: 2018.08.23 às 06:00:38 PM BRT 
//


package br.wsorpec.wscdlrio.buscaEndTelefoneCnpj;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generated package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SPCAXML }
     * 
     */
    public SPCAXML createSPCAXML() {
        return new SPCAXML();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA }
     * 
     */
    public SPCAXML.RESPOSTA createSPCAXMLRESPOSTA() {
        return new SPCAXML.RESPOSTA();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.DEFINERESPOSTA }
     * 
     */
    public SPCAXML.RESPOSTA.DEFINERESPOSTA createSPCAXMLRESPOSTADEFINERESPOSTA() {
        return new SPCAXML.RESPOSTA.DEFINERESPOSTA();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFSEGMENTOEMPRESARIAL }
     * 
     */
    public SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFSEGMENTOEMPRESARIAL createSPCAXMLRESPOSTADEFINERESPOSTADEFSEGMENTOEMPRESARIAL() {
        return new SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFSEGMENTOEMPRESARIAL();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFSEGMENTOEMPRESARIAL.DEFEMPRESASGRUPOREGISTRANDOSOBRECNPJ }
     * 
     */
    public SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFSEGMENTOEMPRESARIAL.DEFEMPRESASGRUPOREGISTRANDOSOBRECNPJ createSPCAXMLRESPOSTADEFINERESPOSTADEFSEGMENTOEMPRESARIALDEFEMPRESASGRUPOREGISTRANDOSOBRECNPJ() {
        return new SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFSEGMENTOEMPRESARIAL.DEFEMPRESASGRUPOREGISTRANDOSOBRECNPJ();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFSEGMENTOEMPRESARIAL.DEFCOMPORTAMENTOPAGAMENTOSGRUPO }
     * 
     */
    public SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFSEGMENTOEMPRESARIAL.DEFCOMPORTAMENTOPAGAMENTOSGRUPO createSPCAXMLRESPOSTADEFINERESPOSTADEFSEGMENTOEMPRESARIALDEFCOMPORTAMENTOPAGAMENTOSGRUPO() {
        return new SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFSEGMENTOEMPRESARIAL.DEFCOMPORTAMENTOPAGAMENTOSGRUPO();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFSEGMENTOEMPRESARIAL.DEFCOMPORTAMENTOPAGAMENTOSGRUPO.DEFDATAATUAL }
     * 
     */
    public SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFSEGMENTOEMPRESARIAL.DEFCOMPORTAMENTOPAGAMENTOSGRUPO.DEFDATAATUAL createSPCAXMLRESPOSTADEFINERESPOSTADEFSEGMENTOEMPRESARIALDEFCOMPORTAMENTOPAGAMENTOSGRUPODEFDATAATUAL() {
        return new SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFSEGMENTOEMPRESARIAL.DEFCOMPORTAMENTOPAGAMENTOSGRUPO.DEFDATAATUAL();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFSEGMENTOEMPRESARIAL.DEFCOMPORTAMENTOPAGAMENTOSGRUPO.DEFDATAATUALMENOS1MES }
     * 
     */
    public SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFSEGMENTOEMPRESARIAL.DEFCOMPORTAMENTOPAGAMENTOSGRUPO.DEFDATAATUALMENOS1MES createSPCAXMLRESPOSTADEFINERESPOSTADEFSEGMENTOEMPRESARIALDEFCOMPORTAMENTOPAGAMENTOSGRUPODEFDATAATUALMENOS1MES() {
        return new SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFSEGMENTOEMPRESARIAL.DEFCOMPORTAMENTOPAGAMENTOSGRUPO.DEFDATAATUALMENOS1MES();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFSEGMENTOEMPRESARIAL.DEFCOMPORTAMENTOPAGAMENTOSGRUPO.DEFDATAATUALMENOS2MESES }
     * 
     */
    public SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFSEGMENTOEMPRESARIAL.DEFCOMPORTAMENTOPAGAMENTOSGRUPO.DEFDATAATUALMENOS2MESES createSPCAXMLRESPOSTADEFINERESPOSTADEFSEGMENTOEMPRESARIALDEFCOMPORTAMENTOPAGAMENTOSGRUPODEFDATAATUALMENOS2MESES() {
        return new SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFSEGMENTOEMPRESARIAL.DEFCOMPORTAMENTOPAGAMENTOSGRUPO.DEFDATAATUALMENOS2MESES();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFSEGMENTOEMPRESARIAL.DEFCOMPORTAMENTOPAGAMENTOSGRUPO.DEFDATAATUALMENOS3MESES }
     * 
     */
    public SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFSEGMENTOEMPRESARIAL.DEFCOMPORTAMENTOPAGAMENTOSGRUPO.DEFDATAATUALMENOS3MESES createSPCAXMLRESPOSTADEFINERESPOSTADEFSEGMENTOEMPRESARIALDEFCOMPORTAMENTOPAGAMENTOSGRUPODEFDATAATUALMENOS3MESES() {
        return new SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFSEGMENTOEMPRESARIAL.DEFCOMPORTAMENTOPAGAMENTOSGRUPO.DEFDATAATUALMENOS3MESES();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFSEGMENTOEMPRESARIAL.DEFCOMPORTAMENTOPAGAMENTOSGRUPO.DEFDATAATUALMENOS4MESES }
     * 
     */
    public SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFSEGMENTOEMPRESARIAL.DEFCOMPORTAMENTOPAGAMENTOSGRUPO.DEFDATAATUALMENOS4MESES createSPCAXMLRESPOSTADEFINERESPOSTADEFSEGMENTOEMPRESARIALDEFCOMPORTAMENTOPAGAMENTOSGRUPODEFDATAATUALMENOS4MESES() {
        return new SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFSEGMENTOEMPRESARIAL.DEFCOMPORTAMENTOPAGAMENTOSGRUPO.DEFDATAATUALMENOS4MESES();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFSEGMENTOEMPRESARIAL.DEFCOMPORTAMENTOPAGAMENTOSGRUPO.DEFDTATUALMENOS5M1ANODTATUALMENOS5M }
     * 
     */
    public SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFSEGMENTOEMPRESARIAL.DEFCOMPORTAMENTOPAGAMENTOSGRUPO.DEFDTATUALMENOS5M1ANODTATUALMENOS5M createSPCAXMLRESPOSTADEFINERESPOSTADEFSEGMENTOEMPRESARIALDEFCOMPORTAMENTOPAGAMENTOSGRUPODEFDTATUALMENOS5M1ANODTATUALMENOS5M() {
        return new SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFSEGMENTOEMPRESARIAL.DEFCOMPORTAMENTOPAGAMENTOSGRUPO.DEFDTATUALMENOS5M1ANODTATUALMENOS5M();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFSEGMENTOEMPRESARIAL.DEFCOMPORTAMENTOPAGAMENTOSGRUPO.DEFMEDIATITULOSCOMPORTAMENTO }
     * 
     */
    public SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFSEGMENTOEMPRESARIAL.DEFCOMPORTAMENTOPAGAMENTOSGRUPO.DEFMEDIATITULOSCOMPORTAMENTO createSPCAXMLRESPOSTADEFINERESPOSTADEFSEGMENTOEMPRESARIALDEFCOMPORTAMENTOPAGAMENTOSGRUPODEFMEDIATITULOSCOMPORTAMENTO() {
        return new SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFSEGMENTOEMPRESARIAL.DEFCOMPORTAMENTOPAGAMENTOSGRUPO.DEFMEDIATITULOSCOMPORTAMENTO();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFSEGMENTOEMPRESARIAL.DEFCOMPORTAMENTOPAGAMENTOSGRUPO.DEFTOTALTITULOSCOMPORTAMENTO }
     * 
     */
    public SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFSEGMENTOEMPRESARIAL.DEFCOMPORTAMENTOPAGAMENTOSGRUPO.DEFTOTALTITULOSCOMPORTAMENTO createSPCAXMLRESPOSTADEFINERESPOSTADEFSEGMENTOEMPRESARIALDEFCOMPORTAMENTOPAGAMENTOSGRUPODEFTOTALTITULOSCOMPORTAMENTO() {
        return new SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFSEGMENTOEMPRESARIAL.DEFCOMPORTAMENTOPAGAMENTOSGRUPO.DEFTOTALTITULOSCOMPORTAMENTO();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFSEGMENTOEMPRESARIAL.DEFCOMPORTAMENTOPAGAMENTOSGRUPO.DEFTOTALCOMPORTAMENTO }
     * 
     */
    public SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFSEGMENTOEMPRESARIAL.DEFCOMPORTAMENTOPAGAMENTOSGRUPO.DEFTOTALCOMPORTAMENTO createSPCAXMLRESPOSTADEFINERESPOSTADEFSEGMENTOEMPRESARIALDEFCOMPORTAMENTOPAGAMENTOSGRUPODEFTOTALCOMPORTAMENTO() {
        return new SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFSEGMENTOEMPRESARIAL.DEFCOMPORTAMENTOPAGAMENTOSGRUPO.DEFTOTALCOMPORTAMENTO();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFSEGMENTOEMPRESARIAL.DEFCOMPORTAMENTOPAGAMENTOSGRUPO.DEFCLASSIFICACAORANKING }
     * 
     */
    public SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFSEGMENTOEMPRESARIAL.DEFCOMPORTAMENTOPAGAMENTOSGRUPO.DEFCLASSIFICACAORANKING createSPCAXMLRESPOSTADEFINERESPOSTADEFSEGMENTOEMPRESARIALDEFCOMPORTAMENTOPAGAMENTOSGRUPODEFCLASSIFICACAORANKING() {
        return new SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFSEGMENTOEMPRESARIAL.DEFCOMPORTAMENTOPAGAMENTOSGRUPO.DEFCLASSIFICACAORANKING();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFSCORE }
     * 
     */
    public SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFSCORE createSPCAXMLRESPOSTADEFINERESPOSTADEFSCORE() {
        return new SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFSCORE();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFLOCALIZACAOCOMPLETO }
     * 
     */
    public SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFLOCALIZACAOCOMPLETO createSPCAXMLRESPOSTADEFINERESPOSTADEFLOCALIZACAOCOMPLETO() {
        return new SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFLOCALIZACAOCOMPLETO();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFLOCALIZACAOCOMPLETO.DEFFILIAL }
     * 
     */
    public SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFLOCALIZACAOCOMPLETO.DEFFILIAL createSPCAXMLRESPOSTADEFINERESPOSTADEFLOCALIZACAOCOMPLETODEFFILIAL() {
        return new SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFLOCALIZACAOCOMPLETO.DEFFILIAL();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFLOCALIZACAOCOMPLETO.DEFMATRIZ }
     * 
     */
    public SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFLOCALIZACAOCOMPLETO.DEFMATRIZ createSPCAXMLRESPOSTADEFINERESPOSTADEFLOCALIZACAOCOMPLETODEFMATRIZ() {
        return new SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFLOCALIZACAOCOMPLETO.DEFMATRIZ();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFEXTRASINTEGRA }
     * 
     */
    public SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFEXTRASINTEGRA createSPCAXMLRESPOSTADEFINERESPOSTADEFEXTRASINTEGRA() {
        return new SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFEXTRASINTEGRA();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFIDENTIFICACAOCOMPLETO }
     * 
     */
    public SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFIDENTIFICACAOCOMPLETO createSPCAXMLRESPOSTADEFINERESPOSTADEFIDENTIFICACAOCOMPLETO() {
        return new SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFIDENTIFICACAOCOMPLETO();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFIDENTIFICACAOCOMPLETO.DEFDEMAISRAMOSATIVIDADE }
     * 
     */
    public SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFIDENTIFICACAOCOMPLETO.DEFDEMAISRAMOSATIVIDADE createSPCAXMLRESPOSTADEFINERESPOSTADEFIDENTIFICACAOCOMPLETODEFDEMAISRAMOSATIVIDADE() {
        return new SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFIDENTIFICACAOCOMPLETO.DEFDEMAISRAMOSATIVIDADE();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFFALENCIASRECUPERACAOJUDICIAL }
     * 
     */
    public SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFFALENCIASRECUPERACAOJUDICIAL createSPCAXMLRESPOSTADEFINERESPOSTADEFFALENCIASRECUPERACAOJUDICIAL() {
        return new SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFFALENCIASRECUPERACAOJUDICIAL();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFFALENCIASRECUPERACAOJUDICIAL.DEFULTIMASOCORRENCIAS }
     * 
     */
    public SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFFALENCIASRECUPERACAOJUDICIAL.DEFULTIMASOCORRENCIAS createSPCAXMLRESPOSTADEFINERESPOSTADEFFALENCIASRECUPERACAOJUDICIALDEFULTIMASOCORRENCIAS() {
        return new SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFFALENCIASRECUPERACAOJUDICIAL.DEFULTIMASOCORRENCIAS();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFACOESCIVEIS }
     * 
     */
    public SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFACOESCIVEIS createSPCAXMLRESPOSTADEFINERESPOSTADEFACOESCIVEIS() {
        return new SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFACOESCIVEIS();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFACOESCIVEIS.DEFULTIMASOCORRENCIAS }
     * 
     */
    public SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFACOESCIVEIS.DEFULTIMASOCORRENCIAS createSPCAXMLRESPOSTADEFINERESPOSTADEFACOESCIVEISDEFULTIMASOCORRENCIAS() {
        return new SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFACOESCIVEIS.DEFULTIMASOCORRENCIAS();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFPROTESTOS }
     * 
     */
    public SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFPROTESTOS createSPCAXMLRESPOSTADEFINERESPOSTADEFPROTESTOS() {
        return new SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFPROTESTOS();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFPROTESTOS.DEFULTIMASOCORRENCIAS }
     * 
     */
    public SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFPROTESTOS.DEFULTIMASOCORRENCIAS createSPCAXMLRESPOSTADEFINERESPOSTADEFPROTESTOSDEFULTIMASOCORRENCIAS() {
        return new SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFPROTESTOS.DEFULTIMASOCORRENCIAS();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFCHEQUESDEVOLVIDOSINFORMADOSUSUARIO }
     * 
     */
    public SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFCHEQUESDEVOLVIDOSINFORMADOSUSUARIO createSPCAXMLRESPOSTADEFINERESPOSTADEFCHEQUESDEVOLVIDOSINFORMADOSUSUARIO() {
        return new SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFCHEQUESDEVOLVIDOSINFORMADOSUSUARIO();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFCHEQUESDEVOLVIDOSINFORMADOSUSUARIO.DEFULTIMASOCORRENCIAS }
     * 
     */
    public SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFCHEQUESDEVOLVIDOSINFORMADOSUSUARIO.DEFULTIMASOCORRENCIAS createSPCAXMLRESPOSTADEFINERESPOSTADEFCHEQUESDEVOLVIDOSINFORMADOSUSUARIODEFULTIMASOCORRENCIAS() {
        return new SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFCHEQUESDEVOLVIDOSINFORMADOSUSUARIO.DEFULTIMASOCORRENCIAS();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFCHEQUESSUSTADOS }
     * 
     */
    public SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFCHEQUESSUSTADOS createSPCAXMLRESPOSTADEFINERESPOSTADEFCHEQUESSUSTADOS() {
        return new SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFCHEQUESSUSTADOS();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFCHEQUESSUSTADOS.DEFULTIMASOCORRENCIAS }
     * 
     */
    public SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFCHEQUESSUSTADOS.DEFULTIMASOCORRENCIAS createSPCAXMLRESPOSTADEFINERESPOSTADEFCHEQUESSUSTADOSDEFULTIMASOCORRENCIAS() {
        return new SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFCHEQUESSUSTADOS.DEFULTIMASOCORRENCIAS();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFCHEQUESSEMFUNDO }
     * 
     */
    public SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFCHEQUESSEMFUNDO createSPCAXMLRESPOSTADEFINERESPOSTADEFCHEQUESSEMFUNDO() {
        return new SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFCHEQUESSEMFUNDO();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFCHEQUESSEMFUNDO.DEFULTIMASOCORRENCIAS }
     * 
     */
    public SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFCHEQUESSEMFUNDO.DEFULTIMASOCORRENCIAS createSPCAXMLRESPOSTADEFINERESPOSTADEFCHEQUESSEMFUNDODEFULTIMASOCORRENCIAS() {
        return new SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFCHEQUESSEMFUNDO.DEFULTIMASOCORRENCIAS();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFIDENTIFICACAOBASICO }
     * 
     */
    public SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFIDENTIFICACAOBASICO createSPCAXMLRESPOSTADEFINERESPOSTADEFIDENTIFICACAOBASICO() {
        return new SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFIDENTIFICACAOBASICO();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFPENDENCIASRESTRICOES }
     * 
     */
    public SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFPENDENCIASRESTRICOES createSPCAXMLRESPOSTADEFINERESPOSTADEFPENDENCIASRESTRICOES() {
        return new SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFPENDENCIASRESTRICOES();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFPENDENCIASRESTRICOES.DEFULTIMASOCORRENCIAS }
     * 
     */
    public SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFPENDENCIASRESTRICOES.DEFULTIMASOCORRENCIAS createSPCAXMLRESPOSTADEFINERESPOSTADEFPENDENCIASRESTRICOESDEFULTIMASOCORRENCIAS() {
        return new SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFPENDENCIASRESTRICOES.DEFULTIMASOCORRENCIAS();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFENDERECOTELEFONESAGENCIABANCARIA }
     * 
     */
    public SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFENDERECOTELEFONESAGENCIABANCARIA createSPCAXMLRESPOSTADEFINERESPOSTADEFENDERECOTELEFONESAGENCIABANCARIA() {
        return new SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFENDERECOTELEFONESAGENCIABANCARIA();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFHISTORICOCONTACORRENTES }
     * 
     */
    public SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFHISTORICOCONTACORRENTES createSPCAXMLRESPOSTADEFINERESPOSTADEFHISTORICOCONTACORRENTES() {
        return new SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFHISTORICOCONTACORRENTES();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFHISTORICOCHEQUEINFORMADOS }
     * 
     */
    public SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFHISTORICOCHEQUEINFORMADOS createSPCAXMLRESPOSTADEFINERESPOSTADEFHISTORICOCHEQUEINFORMADOS() {
        return new SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFHISTORICOCHEQUEINFORMADOS();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFANVISA }
     * 
     */
    public SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFANVISA createSPCAXMLRESPOSTADEFINERESPOSTADEFANVISA() {
        return new SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFANVISA();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFANVISA.DEFPETICOES }
     * 
     */
    public SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFANVISA.DEFPETICOES createSPCAXMLRESPOSTADEFINERESPOSTADEFANVISADEFPETICOES() {
        return new SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFANVISA.DEFPETICOES();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFANVISA.DEFDISTRIBUIDORES }
     * 
     */
    public SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFANVISA.DEFDISTRIBUIDORES createSPCAXMLRESPOSTADEFINERESPOSTADEFANVISADEFDISTRIBUIDORES() {
        return new SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFANVISA.DEFDISTRIBUIDORES();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFANVISA.DEFDISTRIBUIDORES.DEFAUTORIZACOES }
     * 
     */
    public SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFANVISA.DEFDISTRIBUIDORES.DEFAUTORIZACOES createSPCAXMLRESPOSTADEFINERESPOSTADEFANVISADEFDISTRIBUIDORESDEFAUTORIZACOES() {
        return new SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFANVISA.DEFDISTRIBUIDORES.DEFAUTORIZACOES();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFANVISA.DEFFARMACIADROGARIA }
     * 
     */
    public SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFANVISA.DEFFARMACIADROGARIA createSPCAXMLRESPOSTADEFINERESPOSTADEFANVISADEFFARMACIADROGARIA() {
        return new SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFANVISA.DEFFARMACIADROGARIA();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFANVISA.DEFFARMACIADROGARIA.DEFAUTORIZACOES }
     * 
     */
    public SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFANVISA.DEFFARMACIADROGARIA.DEFAUTORIZACOES createSPCAXMLRESPOSTADEFINERESPOSTADEFANVISADEFFARMACIADROGARIADEFAUTORIZACOES() {
        return new SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFANVISA.DEFFARMACIADROGARIA.DEFAUTORIZACOES();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFPRINCIPAISFORNECEDORES }
     * 
     */
    public SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFPRINCIPAISFORNECEDORES createSPCAXMLRESPOSTADEFINERESPOSTADEFPRINCIPAISFORNECEDORES() {
        return new SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFPRINCIPAISFORNECEDORES();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFPRINCIPAISFORNECEDORES.DEFFORNECEDOR }
     * 
     */
    public SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFPRINCIPAISFORNECEDORES.DEFFORNECEDOR createSPCAXMLRESPOSTADEFINERESPOSTADEFPRINCIPAISFORNECEDORESDEFFORNECEDOR() {
        return new SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFPRINCIPAISFORNECEDORES.DEFFORNECEDOR();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFTITULOSAVENCER }
     * 
     */
    public SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFTITULOSAVENCER createSPCAXMLRESPOSTADEFINERESPOSTADEFTITULOSAVENCER() {
        return new SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFTITULOSAVENCER();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFREFERENCIAISNEGOCIOS }
     * 
     */
    public SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFREFERENCIAISNEGOCIOS createSPCAXMLRESPOSTADEFINERESPOSTADEFREFERENCIAISNEGOCIOS() {
        return new SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFREFERENCIAISNEGOCIOS();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFCOMPORTAMENTOPAGAMENTOS }
     * 
     */
    public SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFCOMPORTAMENTOPAGAMENTOS createSPCAXMLRESPOSTADEFINERESPOSTADEFCOMPORTAMENTOPAGAMENTOS() {
        return new SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFCOMPORTAMENTOPAGAMENTOS();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFCOMPORTAMENTOCOMSUAEMPRESA }
     * 
     */
    public SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFCOMPORTAMENTOCOMSUAEMPRESA createSPCAXMLRESPOSTADEFINERESPOSTADEFCOMPORTAMENTOCOMSUAEMPRESA() {
        return new SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFCOMPORTAMENTOCOMSUAEMPRESA();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFULTIMASCONSULTAS }
     * 
     */
    public SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFULTIMASCONSULTAS createSPCAXMLRESPOSTADEFINERESPOSTADEFULTIMASCONSULTAS() {
        return new SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFULTIMASCONSULTAS();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFCONSULTAS }
     * 
     */
    public SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFCONSULTAS createSPCAXMLRESPOSTADEFINERESPOSTADEFCONSULTAS() {
        return new SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFCONSULTAS();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFCONSULTAS.DEFULTIMASCONSULTAS }
     * 
     */
    public SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFCONSULTAS.DEFULTIMASCONSULTAS createSPCAXMLRESPOSTADEFINERESPOSTADEFCONSULTASDEFULTIMASCONSULTAS() {
        return new SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFCONSULTAS.DEFULTIMASCONSULTAS();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFPARTICIPACOESEMPRESASCONSULTADAS }
     * 
     */
    public SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFPARTICIPACOESEMPRESASCONSULTADAS createSPCAXMLRESPOSTADEFINERESPOSTADEFPARTICIPACOESEMPRESASCONSULTADAS() {
        return new SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFPARTICIPACOESEMPRESASCONSULTADAS();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFPARTICIPACOESEMPRESASCONSULTADAS.DEFPARTICIPACAOEMPRESACONSULTADA }
     * 
     */
    public SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFPARTICIPACOESEMPRESASCONSULTADAS.DEFPARTICIPACAOEMPRESACONSULTADA createSPCAXMLRESPOSTADEFINERESPOSTADEFPARTICIPACOESEMPRESASCONSULTADASDEFPARTICIPACAOEMPRESACONSULTADA() {
        return new SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFPARTICIPACOESEMPRESASCONSULTADAS.DEFPARTICIPACAOEMPRESACONSULTADA();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFPARTICIPACOESEMPRESASCONSULTADAS.DEFPARTICIPACAOEMPRESACONSULTADA.DEFRESTRICOESDOCUMENTO }
     * 
     */
    public SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFPARTICIPACOESEMPRESASCONSULTADAS.DEFPARTICIPACAOEMPRESACONSULTADA.DEFRESTRICOESDOCUMENTO createSPCAXMLRESPOSTADEFINERESPOSTADEFPARTICIPACOESEMPRESASCONSULTADASDEFPARTICIPACAOEMPRESACONSULTADADEFRESTRICOESDOCUMENTO() {
        return new SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFPARTICIPACOESEMPRESASCONSULTADAS.DEFPARTICIPACAOEMPRESACONSULTADA.DEFRESTRICOESDOCUMENTO();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFPARTICIPACOESSOCIOSADMOUTRASEMPRESAS }
     * 
     */
    public SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFPARTICIPACOESSOCIOSADMOUTRASEMPRESAS createSPCAXMLRESPOSTADEFINERESPOSTADEFPARTICIPACOESSOCIOSADMOUTRASEMPRESAS() {
        return new SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFPARTICIPACOESSOCIOSADMOUTRASEMPRESAS();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFPARTICIPACOESSOCIOSADMOUTRASEMPRESAS.DEFSOCIO }
     * 
     */
    public SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFPARTICIPACOESSOCIOSADMOUTRASEMPRESAS.DEFSOCIO createSPCAXMLRESPOSTADEFINERESPOSTADEFPARTICIPACOESSOCIOSADMOUTRASEMPRESASDEFSOCIO() {
        return new SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFPARTICIPACOESSOCIOSADMOUTRASEMPRESAS.DEFSOCIO();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFPARTICIPACOESSOCIOSADMOUTRASEMPRESAS.DEFSOCIO.DEFSOCIOSPARTICIPANTES }
     * 
     */
    public SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFPARTICIPACOESSOCIOSADMOUTRASEMPRESAS.DEFSOCIO.DEFSOCIOSPARTICIPANTES createSPCAXMLRESPOSTADEFINERESPOSTADEFPARTICIPACOESSOCIOSADMOUTRASEMPRESASDEFSOCIODEFSOCIOSPARTICIPANTES() {
        return new SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFPARTICIPACOESSOCIOSADMOUTRASEMPRESAS.DEFSOCIO.DEFSOCIOSPARTICIPANTES();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFPARTICIPACOESSOCIOSADMOUTRASEMPRESAS.DEFSOCIO.DEFSOCIOSPARTICIPANTES.DEFRESTRICOESDOCUMENTO }
     * 
     */
    public SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFPARTICIPACOESSOCIOSADMOUTRASEMPRESAS.DEFSOCIO.DEFSOCIOSPARTICIPANTES.DEFRESTRICOESDOCUMENTO createSPCAXMLRESPOSTADEFINERESPOSTADEFPARTICIPACOESSOCIOSADMOUTRASEMPRESASDEFSOCIODEFSOCIOSPARTICIPANTESDEFRESTRICOESDOCUMENTO() {
        return new SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFPARTICIPACOESSOCIOSADMOUTRASEMPRESAS.DEFSOCIO.DEFSOCIOSPARTICIPANTES.DEFRESTRICOESDOCUMENTO();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFADMINISTRADORES }
     * 
     */
    public SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFADMINISTRADORES createSPCAXMLRESPOSTADEFINERESPOSTADEFADMINISTRADORES() {
        return new SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFADMINISTRADORES();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFADMINISTRADORES.DEFADMINISTRADOR }
     * 
     */
    public SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFADMINISTRADORES.DEFADMINISTRADOR createSPCAXMLRESPOSTADEFINERESPOSTADEFADMINISTRADORESDEFADMINISTRADOR() {
        return new SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFADMINISTRADORES.DEFADMINISTRADOR();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFADMINISTRADORES.DEFADMINISTRADOR.DEFRESTRICOESDOCUMENTO }
     * 
     */
    public SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFADMINISTRADORES.DEFADMINISTRADOR.DEFRESTRICOESDOCUMENTO createSPCAXMLRESPOSTADEFINERESPOSTADEFADMINISTRADORESDEFADMINISTRADORDEFRESTRICOESDOCUMENTO() {
        return new SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFADMINISTRADORES.DEFADMINISTRADOR.DEFRESTRICOESDOCUMENTO();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFSOCIOS }
     * 
     */
    public SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFSOCIOS createSPCAXMLRESPOSTADEFINERESPOSTADEFSOCIOS() {
        return new SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFSOCIOS();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFSOCIOS.DEFSOCIO }
     * 
     */
    public SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFSOCIOS.DEFSOCIO createSPCAXMLRESPOSTADEFINERESPOSTADEFSOCIOSDEFSOCIO() {
        return new SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFSOCIOS.DEFSOCIO();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFSOCIOS.DEFSOCIO.DEFRESTRICOESDOCUMENTO }
     * 
     */
    public SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFSOCIOS.DEFSOCIO.DEFRESTRICOESDOCUMENTO createSPCAXMLRESPOSTADEFINERESPOSTADEFSOCIOSDEFSOCIODEFRESTRICOESDOCUMENTO() {
        return new SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFSOCIOS.DEFSOCIO.DEFRESTRICOESDOCUMENTO();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFEMPRESASSITUADANOMESMOENDERECO }
     * 
     */
    public SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFEMPRESASSITUADANOMESMOENDERECO createSPCAXMLRESPOSTADEFINERESPOSTADEFEMPRESASSITUADANOMESMOENDERECO() {
        return new SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFEMPRESASSITUADANOMESMOENDERECO();
    }

    /**
     * Create an instance of {@link SPCAXML.SOLICITACAO }
     * 
     */
    public SPCAXML.SOLICITACAO createSPCAXMLSOLICITACAO() {
        return new SPCAXML.SOLICITACAO();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.RESPOSTARETORNO }
     * 
     */
    public SPCAXML.RESPOSTA.RESPOSTARETORNO createSPCAXMLRESPOSTARESPOSTARETORNO() {
        return new SPCAXML.RESPOSTA.RESPOSTARETORNO();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFDECISAO }
     * 
     */
    public SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFDECISAO createSPCAXMLRESPOSTADEFINERESPOSTADEFDECISAO() {
        return new SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFDECISAO();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFFATURAMENTOPRESUMIDO }
     * 
     */
    public SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFFATURAMENTOPRESUMIDO createSPCAXMLRESPOSTADEFINERESPOSTADEFFATURAMENTOPRESUMIDO() {
        return new SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFFATURAMENTOPRESUMIDO();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFPARTICIPACOESEMOUTRASEMPRESAS }
     * 
     */
    public SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFPARTICIPACOESEMOUTRASEMPRESAS createSPCAXMLRESPOSTADEFINERESPOSTADEFPARTICIPACOESEMOUTRASEMPRESAS() {
        return new SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFPARTICIPACOESEMOUTRASEMPRESAS();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFLIMITECREDITO }
     * 
     */
    public SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFLIMITECREDITO createSPCAXMLRESPOSTADEFINERESPOSTADEFLIMITECREDITO() {
        return new SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFLIMITECREDITO();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFTEMPORELACIONAMENTOFORNECEDORES }
     * 
     */
    public SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFTEMPORELACIONAMENTOFORNECEDORES createSPCAXMLRESPOSTADEFINERESPOSTADEFTEMPORELACIONAMENTOFORNECEDORES() {
        return new SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFTEMPORELACIONAMENTOFORNECEDORES();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFLOCALIZACAOBASICO }
     * 
     */
    public SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFLOCALIZACAOBASICO createSPCAXMLRESPOSTADEFINERESPOSTADEFLOCALIZACAOBASICO() {
        return new SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFLOCALIZACAOBASICO();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFALERTAFRAUDES }
     * 
     */
    public SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFALERTAFRAUDES createSPCAXMLRESPOSTADEFINERESPOSTADEFALERTAFRAUDES() {
        return new SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFALERTAFRAUDES();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFSEGMENTOEMPRESARIAL.DEFIDENTIFICACAO }
     * 
     */
    public SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFSEGMENTOEMPRESARIAL.DEFIDENTIFICACAO createSPCAXMLRESPOSTADEFINERESPOSTADEFSEGMENTOEMPRESARIALDEFIDENTIFICACAO() {
        return new SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFSEGMENTOEMPRESARIAL.DEFIDENTIFICACAO();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFSEGMENTOEMPRESARIAL.DEFCONSULTASGRUPO }
     * 
     */
    public SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFSEGMENTOEMPRESARIAL.DEFCONSULTASGRUPO createSPCAXMLRESPOSTADEFINERESPOSTADEFSEGMENTOEMPRESARIALDEFCONSULTASGRUPO() {
        return new SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFSEGMENTOEMPRESARIAL.DEFCONSULTASGRUPO();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFSEGMENTOEMPRESARIAL.DEFEMPRESASGRUPOREGISTRANDOSOBRECNPJ.DEFEMPRESAGRUPO }
     * 
     */
    public SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFSEGMENTOEMPRESARIAL.DEFEMPRESASGRUPOREGISTRANDOSOBRECNPJ.DEFEMPRESAGRUPO createSPCAXMLRESPOSTADEFINERESPOSTADEFSEGMENTOEMPRESARIALDEFEMPRESASGRUPOREGISTRANDOSOBRECNPJDEFEMPRESAGRUPO() {
        return new SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFSEGMENTOEMPRESARIAL.DEFEMPRESASGRUPOREGISTRANDOSOBRECNPJ.DEFEMPRESAGRUPO();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFSEGMENTOEMPRESARIAL.DEFCOMPORTAMENTOPAGAMENTOSGRUPO.DEFCOMPROMETIMENTOFUTURO }
     * 
     */
    public SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFSEGMENTOEMPRESARIAL.DEFCOMPORTAMENTOPAGAMENTOSGRUPO.DEFCOMPROMETIMENTOFUTURO createSPCAXMLRESPOSTADEFINERESPOSTADEFSEGMENTOEMPRESARIALDEFCOMPORTAMENTOPAGAMENTOSGRUPODEFCOMPROMETIMENTOFUTURO() {
        return new SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFSEGMENTOEMPRESARIAL.DEFCOMPORTAMENTOPAGAMENTOSGRUPO.DEFCOMPROMETIMENTOFUTURO();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFSEGMENTOEMPRESARIAL.DEFCOMPORTAMENTOPAGAMENTOSGRUPO.DEFMEDIACREDITOCONCEDIDO }
     * 
     */
    public SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFSEGMENTOEMPRESARIAL.DEFCOMPORTAMENTOPAGAMENTOSGRUPO.DEFMEDIACREDITOCONCEDIDO createSPCAXMLRESPOSTADEFINERESPOSTADEFSEGMENTOEMPRESARIALDEFCOMPORTAMENTOPAGAMENTOSGRUPODEFMEDIACREDITOCONCEDIDO() {
        return new SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFSEGMENTOEMPRESARIAL.DEFCOMPORTAMENTOPAGAMENTOSGRUPO.DEFMEDIACREDITOCONCEDIDO();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFSEGMENTOEMPRESARIAL.DEFCOMPORTAMENTOPAGAMENTOSGRUPO.DEFMEDIADIASCOMPORTAMENTO }
     * 
     */
    public SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFSEGMENTOEMPRESARIAL.DEFCOMPORTAMENTOPAGAMENTOSGRUPO.DEFMEDIADIASCOMPORTAMENTO createSPCAXMLRESPOSTADEFINERESPOSTADEFSEGMENTOEMPRESARIALDEFCOMPORTAMENTOPAGAMENTOSGRUPODEFMEDIADIASCOMPORTAMENTO() {
        return new SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFSEGMENTOEMPRESARIAL.DEFCOMPORTAMENTOPAGAMENTOSGRUPO.DEFMEDIADIASCOMPORTAMENTO();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFSEGMENTOEMPRESARIAL.DEFCOMPORTAMENTOPAGAMENTOSGRUPO.DEFDATAATUALMAIS1MES }
     * 
     */
    public SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFSEGMENTOEMPRESARIAL.DEFCOMPORTAMENTOPAGAMENTOSGRUPO.DEFDATAATUALMAIS1MES createSPCAXMLRESPOSTADEFINERESPOSTADEFSEGMENTOEMPRESARIALDEFCOMPORTAMENTOPAGAMENTOSGRUPODEFDATAATUALMAIS1MES() {
        return new SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFSEGMENTOEMPRESARIAL.DEFCOMPORTAMENTOPAGAMENTOSGRUPO.DEFDATAATUALMAIS1MES();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFSEGMENTOEMPRESARIAL.DEFCOMPORTAMENTOPAGAMENTOSGRUPO.DEFDATAATUALMAIS2MESES }
     * 
     */
    public SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFSEGMENTOEMPRESARIAL.DEFCOMPORTAMENTOPAGAMENTOSGRUPO.DEFDATAATUALMAIS2MESES createSPCAXMLRESPOSTADEFINERESPOSTADEFSEGMENTOEMPRESARIALDEFCOMPORTAMENTOPAGAMENTOSGRUPODEFDATAATUALMAIS2MESES() {
        return new SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFSEGMENTOEMPRESARIAL.DEFCOMPORTAMENTOPAGAMENTOSGRUPO.DEFDATAATUALMAIS2MESES();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFSEGMENTOEMPRESARIAL.DEFCOMPORTAMENTOPAGAMENTOSGRUPO.DEFDATAATUALMAIS3MESES }
     * 
     */
    public SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFSEGMENTOEMPRESARIAL.DEFCOMPORTAMENTOPAGAMENTOSGRUPO.DEFDATAATUALMAIS3MESES createSPCAXMLRESPOSTADEFINERESPOSTADEFSEGMENTOEMPRESARIALDEFCOMPORTAMENTOPAGAMENTOSGRUPODEFDATAATUALMAIS3MESES() {
        return new SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFSEGMENTOEMPRESARIAL.DEFCOMPORTAMENTOPAGAMENTOSGRUPO.DEFDATAATUALMAIS3MESES();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFSEGMENTOEMPRESARIAL.DEFCOMPORTAMENTOPAGAMENTOSGRUPO.DEFDATAATUAL.DEFTITULOSPAGOS }
     * 
     */
    public SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFSEGMENTOEMPRESARIAL.DEFCOMPORTAMENTOPAGAMENTOSGRUPO.DEFDATAATUAL.DEFTITULOSPAGOS createSPCAXMLRESPOSTADEFINERESPOSTADEFSEGMENTOEMPRESARIALDEFCOMPORTAMENTOPAGAMENTOSGRUPODEFDATAATUALDEFTITULOSPAGOS() {
        return new SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFSEGMENTOEMPRESARIAL.DEFCOMPORTAMENTOPAGAMENTOSGRUPO.DEFDATAATUAL.DEFTITULOSPAGOS();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFSEGMENTOEMPRESARIAL.DEFCOMPORTAMENTOPAGAMENTOSGRUPO.DEFDATAATUAL.DEFTITULOSEMABERTO }
     * 
     */
    public SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFSEGMENTOEMPRESARIAL.DEFCOMPORTAMENTOPAGAMENTOSGRUPO.DEFDATAATUAL.DEFTITULOSEMABERTO createSPCAXMLRESPOSTADEFINERESPOSTADEFSEGMENTOEMPRESARIALDEFCOMPORTAMENTOPAGAMENTOSGRUPODEFDATAATUALDEFTITULOSEMABERTO() {
        return new SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFSEGMENTOEMPRESARIAL.DEFCOMPORTAMENTOPAGAMENTOSGRUPO.DEFDATAATUAL.DEFTITULOSEMABERTO();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFSEGMENTOEMPRESARIAL.DEFCOMPORTAMENTOPAGAMENTOSGRUPO.DEFDATAATUALMENOS1MES.DEFTITULOSPAGOS }
     * 
     */
    public SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFSEGMENTOEMPRESARIAL.DEFCOMPORTAMENTOPAGAMENTOSGRUPO.DEFDATAATUALMENOS1MES.DEFTITULOSPAGOS createSPCAXMLRESPOSTADEFINERESPOSTADEFSEGMENTOEMPRESARIALDEFCOMPORTAMENTOPAGAMENTOSGRUPODEFDATAATUALMENOS1MESDEFTITULOSPAGOS() {
        return new SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFSEGMENTOEMPRESARIAL.DEFCOMPORTAMENTOPAGAMENTOSGRUPO.DEFDATAATUALMENOS1MES.DEFTITULOSPAGOS();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFSEGMENTOEMPRESARIAL.DEFCOMPORTAMENTOPAGAMENTOSGRUPO.DEFDATAATUALMENOS1MES.DEFTITULOSEMABERTO }
     * 
     */
    public SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFSEGMENTOEMPRESARIAL.DEFCOMPORTAMENTOPAGAMENTOSGRUPO.DEFDATAATUALMENOS1MES.DEFTITULOSEMABERTO createSPCAXMLRESPOSTADEFINERESPOSTADEFSEGMENTOEMPRESARIALDEFCOMPORTAMENTOPAGAMENTOSGRUPODEFDATAATUALMENOS1MESDEFTITULOSEMABERTO() {
        return new SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFSEGMENTOEMPRESARIAL.DEFCOMPORTAMENTOPAGAMENTOSGRUPO.DEFDATAATUALMENOS1MES.DEFTITULOSEMABERTO();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFSEGMENTOEMPRESARIAL.DEFCOMPORTAMENTOPAGAMENTOSGRUPO.DEFDATAATUALMENOS2MESES.DEFTITULOSPAGOS }
     * 
     */
    public SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFSEGMENTOEMPRESARIAL.DEFCOMPORTAMENTOPAGAMENTOSGRUPO.DEFDATAATUALMENOS2MESES.DEFTITULOSPAGOS createSPCAXMLRESPOSTADEFINERESPOSTADEFSEGMENTOEMPRESARIALDEFCOMPORTAMENTOPAGAMENTOSGRUPODEFDATAATUALMENOS2MESESDEFTITULOSPAGOS() {
        return new SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFSEGMENTOEMPRESARIAL.DEFCOMPORTAMENTOPAGAMENTOSGRUPO.DEFDATAATUALMENOS2MESES.DEFTITULOSPAGOS();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFSEGMENTOEMPRESARIAL.DEFCOMPORTAMENTOPAGAMENTOSGRUPO.DEFDATAATUALMENOS2MESES.DEFTITULOSEMABERTO }
     * 
     */
    public SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFSEGMENTOEMPRESARIAL.DEFCOMPORTAMENTOPAGAMENTOSGRUPO.DEFDATAATUALMENOS2MESES.DEFTITULOSEMABERTO createSPCAXMLRESPOSTADEFINERESPOSTADEFSEGMENTOEMPRESARIALDEFCOMPORTAMENTOPAGAMENTOSGRUPODEFDATAATUALMENOS2MESESDEFTITULOSEMABERTO() {
        return new SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFSEGMENTOEMPRESARIAL.DEFCOMPORTAMENTOPAGAMENTOSGRUPO.DEFDATAATUALMENOS2MESES.DEFTITULOSEMABERTO();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFSEGMENTOEMPRESARIAL.DEFCOMPORTAMENTOPAGAMENTOSGRUPO.DEFDATAATUALMENOS3MESES.DEFTITULOSPAGOS }
     * 
     */
    public SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFSEGMENTOEMPRESARIAL.DEFCOMPORTAMENTOPAGAMENTOSGRUPO.DEFDATAATUALMENOS3MESES.DEFTITULOSPAGOS createSPCAXMLRESPOSTADEFINERESPOSTADEFSEGMENTOEMPRESARIALDEFCOMPORTAMENTOPAGAMENTOSGRUPODEFDATAATUALMENOS3MESESDEFTITULOSPAGOS() {
        return new SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFSEGMENTOEMPRESARIAL.DEFCOMPORTAMENTOPAGAMENTOSGRUPO.DEFDATAATUALMENOS3MESES.DEFTITULOSPAGOS();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFSEGMENTOEMPRESARIAL.DEFCOMPORTAMENTOPAGAMENTOSGRUPO.DEFDATAATUALMENOS3MESES.DEFTITULOSEMABERTO }
     * 
     */
    public SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFSEGMENTOEMPRESARIAL.DEFCOMPORTAMENTOPAGAMENTOSGRUPO.DEFDATAATUALMENOS3MESES.DEFTITULOSEMABERTO createSPCAXMLRESPOSTADEFINERESPOSTADEFSEGMENTOEMPRESARIALDEFCOMPORTAMENTOPAGAMENTOSGRUPODEFDATAATUALMENOS3MESESDEFTITULOSEMABERTO() {
        return new SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFSEGMENTOEMPRESARIAL.DEFCOMPORTAMENTOPAGAMENTOSGRUPO.DEFDATAATUALMENOS3MESES.DEFTITULOSEMABERTO();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFSEGMENTOEMPRESARIAL.DEFCOMPORTAMENTOPAGAMENTOSGRUPO.DEFDATAATUALMENOS4MESES.DEFTITULOSPAGOS }
     * 
     */
    public SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFSEGMENTOEMPRESARIAL.DEFCOMPORTAMENTOPAGAMENTOSGRUPO.DEFDATAATUALMENOS4MESES.DEFTITULOSPAGOS createSPCAXMLRESPOSTADEFINERESPOSTADEFSEGMENTOEMPRESARIALDEFCOMPORTAMENTOPAGAMENTOSGRUPODEFDATAATUALMENOS4MESESDEFTITULOSPAGOS() {
        return new SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFSEGMENTOEMPRESARIAL.DEFCOMPORTAMENTOPAGAMENTOSGRUPO.DEFDATAATUALMENOS4MESES.DEFTITULOSPAGOS();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFSEGMENTOEMPRESARIAL.DEFCOMPORTAMENTOPAGAMENTOSGRUPO.DEFDATAATUALMENOS4MESES.DEFTITULOSEMABERTO }
     * 
     */
    public SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFSEGMENTOEMPRESARIAL.DEFCOMPORTAMENTOPAGAMENTOSGRUPO.DEFDATAATUALMENOS4MESES.DEFTITULOSEMABERTO createSPCAXMLRESPOSTADEFINERESPOSTADEFSEGMENTOEMPRESARIALDEFCOMPORTAMENTOPAGAMENTOSGRUPODEFDATAATUALMENOS4MESESDEFTITULOSEMABERTO() {
        return new SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFSEGMENTOEMPRESARIAL.DEFCOMPORTAMENTOPAGAMENTOSGRUPO.DEFDATAATUALMENOS4MESES.DEFTITULOSEMABERTO();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFSEGMENTOEMPRESARIAL.DEFCOMPORTAMENTOPAGAMENTOSGRUPO.DEFDTATUALMENOS5M1ANODTATUALMENOS5M.DEFTITULOSPAGOS }
     * 
     */
    public SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFSEGMENTOEMPRESARIAL.DEFCOMPORTAMENTOPAGAMENTOSGRUPO.DEFDTATUALMENOS5M1ANODTATUALMENOS5M.DEFTITULOSPAGOS createSPCAXMLRESPOSTADEFINERESPOSTADEFSEGMENTOEMPRESARIALDEFCOMPORTAMENTOPAGAMENTOSGRUPODEFDTATUALMENOS5M1ANODTATUALMENOS5MDEFTITULOSPAGOS() {
        return new SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFSEGMENTOEMPRESARIAL.DEFCOMPORTAMENTOPAGAMENTOSGRUPO.DEFDTATUALMENOS5M1ANODTATUALMENOS5M.DEFTITULOSPAGOS();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFSEGMENTOEMPRESARIAL.DEFCOMPORTAMENTOPAGAMENTOSGRUPO.DEFDTATUALMENOS5M1ANODTATUALMENOS5M.DEFTITULOSEMABERTO }
     * 
     */
    public SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFSEGMENTOEMPRESARIAL.DEFCOMPORTAMENTOPAGAMENTOSGRUPO.DEFDTATUALMENOS5M1ANODTATUALMENOS5M.DEFTITULOSEMABERTO createSPCAXMLRESPOSTADEFINERESPOSTADEFSEGMENTOEMPRESARIALDEFCOMPORTAMENTOPAGAMENTOSGRUPODEFDTATUALMENOS5M1ANODTATUALMENOS5MDEFTITULOSEMABERTO() {
        return new SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFSEGMENTOEMPRESARIAL.DEFCOMPORTAMENTOPAGAMENTOSGRUPO.DEFDTATUALMENOS5M1ANODTATUALMENOS5M.DEFTITULOSEMABERTO();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFSEGMENTOEMPRESARIAL.DEFCOMPORTAMENTOPAGAMENTOSGRUPO.DEFMEDIATITULOSCOMPORTAMENTO.DEFTITULOSPAGOS }
     * 
     */
    public SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFSEGMENTOEMPRESARIAL.DEFCOMPORTAMENTOPAGAMENTOSGRUPO.DEFMEDIATITULOSCOMPORTAMENTO.DEFTITULOSPAGOS createSPCAXMLRESPOSTADEFINERESPOSTADEFSEGMENTOEMPRESARIALDEFCOMPORTAMENTOPAGAMENTOSGRUPODEFMEDIATITULOSCOMPORTAMENTODEFTITULOSPAGOS() {
        return new SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFSEGMENTOEMPRESARIAL.DEFCOMPORTAMENTOPAGAMENTOSGRUPO.DEFMEDIATITULOSCOMPORTAMENTO.DEFTITULOSPAGOS();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFSEGMENTOEMPRESARIAL.DEFCOMPORTAMENTOPAGAMENTOSGRUPO.DEFMEDIATITULOSCOMPORTAMENTO.DEFTITULOSEMABERTO }
     * 
     */
    public SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFSEGMENTOEMPRESARIAL.DEFCOMPORTAMENTOPAGAMENTOSGRUPO.DEFMEDIATITULOSCOMPORTAMENTO.DEFTITULOSEMABERTO createSPCAXMLRESPOSTADEFINERESPOSTADEFSEGMENTOEMPRESARIALDEFCOMPORTAMENTOPAGAMENTOSGRUPODEFMEDIATITULOSCOMPORTAMENTODEFTITULOSEMABERTO() {
        return new SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFSEGMENTOEMPRESARIAL.DEFCOMPORTAMENTOPAGAMENTOSGRUPO.DEFMEDIATITULOSCOMPORTAMENTO.DEFTITULOSEMABERTO();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFSEGMENTOEMPRESARIAL.DEFCOMPORTAMENTOPAGAMENTOSGRUPO.DEFTOTALTITULOSCOMPORTAMENTO.DEFTITULOSPAGOS }
     * 
     */
    public SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFSEGMENTOEMPRESARIAL.DEFCOMPORTAMENTOPAGAMENTOSGRUPO.DEFTOTALTITULOSCOMPORTAMENTO.DEFTITULOSPAGOS createSPCAXMLRESPOSTADEFINERESPOSTADEFSEGMENTOEMPRESARIALDEFCOMPORTAMENTOPAGAMENTOSGRUPODEFTOTALTITULOSCOMPORTAMENTODEFTITULOSPAGOS() {
        return new SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFSEGMENTOEMPRESARIAL.DEFCOMPORTAMENTOPAGAMENTOSGRUPO.DEFTOTALTITULOSCOMPORTAMENTO.DEFTITULOSPAGOS();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFSEGMENTOEMPRESARIAL.DEFCOMPORTAMENTOPAGAMENTOSGRUPO.DEFTOTALTITULOSCOMPORTAMENTO.DEFTITULOSEMABERTO }
     * 
     */
    public SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFSEGMENTOEMPRESARIAL.DEFCOMPORTAMENTOPAGAMENTOSGRUPO.DEFTOTALTITULOSCOMPORTAMENTO.DEFTITULOSEMABERTO createSPCAXMLRESPOSTADEFINERESPOSTADEFSEGMENTOEMPRESARIALDEFCOMPORTAMENTOPAGAMENTOSGRUPODEFTOTALTITULOSCOMPORTAMENTODEFTITULOSEMABERTO() {
        return new SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFSEGMENTOEMPRESARIAL.DEFCOMPORTAMENTOPAGAMENTOSGRUPO.DEFTOTALTITULOSCOMPORTAMENTO.DEFTITULOSEMABERTO();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFSEGMENTOEMPRESARIAL.DEFCOMPORTAMENTOPAGAMENTOSGRUPO.DEFTOTALCOMPORTAMENTO.DEFTITULOSPAGOS }
     * 
     */
    public SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFSEGMENTOEMPRESARIAL.DEFCOMPORTAMENTOPAGAMENTOSGRUPO.DEFTOTALCOMPORTAMENTO.DEFTITULOSPAGOS createSPCAXMLRESPOSTADEFINERESPOSTADEFSEGMENTOEMPRESARIALDEFCOMPORTAMENTOPAGAMENTOSGRUPODEFTOTALCOMPORTAMENTODEFTITULOSPAGOS() {
        return new SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFSEGMENTOEMPRESARIAL.DEFCOMPORTAMENTOPAGAMENTOSGRUPO.DEFTOTALCOMPORTAMENTO.DEFTITULOSPAGOS();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFSEGMENTOEMPRESARIAL.DEFCOMPORTAMENTOPAGAMENTOSGRUPO.DEFTOTALCOMPORTAMENTO.DEFTITULOSEMABERTO }
     * 
     */
    public SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFSEGMENTOEMPRESARIAL.DEFCOMPORTAMENTOPAGAMENTOSGRUPO.DEFTOTALCOMPORTAMENTO.DEFTITULOSEMABERTO createSPCAXMLRESPOSTADEFINERESPOSTADEFSEGMENTOEMPRESARIALDEFCOMPORTAMENTOPAGAMENTOSGRUPODEFTOTALCOMPORTAMENTODEFTITULOSEMABERTO() {
        return new SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFSEGMENTOEMPRESARIAL.DEFCOMPORTAMENTOPAGAMENTOSGRUPO.DEFTOTALCOMPORTAMENTO.DEFTITULOSEMABERTO();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFSEGMENTOEMPRESARIAL.DEFCOMPORTAMENTOPAGAMENTOSGRUPO.DEFCLASSIFICACAORANKING.DEFTITULOSEMABERTORANKING }
     * 
     */
    public SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFSEGMENTOEMPRESARIAL.DEFCOMPORTAMENTOPAGAMENTOSGRUPO.DEFCLASSIFICACAORANKING.DEFTITULOSEMABERTORANKING createSPCAXMLRESPOSTADEFINERESPOSTADEFSEGMENTOEMPRESARIALDEFCOMPORTAMENTOPAGAMENTOSGRUPODEFCLASSIFICACAORANKINGDEFTITULOSEMABERTORANKING() {
        return new SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFSEGMENTOEMPRESARIAL.DEFCOMPORTAMENTOPAGAMENTOSGRUPO.DEFCLASSIFICACAORANKING.DEFTITULOSEMABERTORANKING();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFSCORE.DEFSCOREPJ }
     * 
     */
    public SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFSCORE.DEFSCOREPJ createSPCAXMLRESPOSTADEFINERESPOSTADEFSCOREDEFSCOREPJ() {
        return new SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFSCORE.DEFSCOREPJ();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFLOCALIZACAOCOMPLETO.DEFFILIAL.DEFTELEFONEFILIAL }
     * 
     */
    public SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFLOCALIZACAOCOMPLETO.DEFFILIAL.DEFTELEFONEFILIAL createSPCAXMLRESPOSTADEFINERESPOSTADEFLOCALIZACAOCOMPLETODEFFILIALDEFTELEFONEFILIAL() {
        return new SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFLOCALIZACAOCOMPLETO.DEFFILIAL.DEFTELEFONEFILIAL();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFLOCALIZACAOCOMPLETO.DEFMATRIZ.DEFTELEFONEMATRIZ }
     * 
     */
    public SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFLOCALIZACAOCOMPLETO.DEFMATRIZ.DEFTELEFONEMATRIZ createSPCAXMLRESPOSTADEFINERESPOSTADEFLOCALIZACAOCOMPLETODEFMATRIZDEFTELEFONEMATRIZ() {
        return new SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFLOCALIZACAOCOMPLETO.DEFMATRIZ.DEFTELEFONEMATRIZ();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFEXTRASINTEGRA.DEFSINTEGRA }
     * 
     */
    public SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFEXTRASINTEGRA.DEFSINTEGRA createSPCAXMLRESPOSTADEFINERESPOSTADEFEXTRASINTEGRADEFSINTEGRA() {
        return new SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFEXTRASINTEGRA.DEFSINTEGRA();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFIDENTIFICACAOCOMPLETO.DEFRAMOATIVIDADEPRIMARIO }
     * 
     */
    public SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFIDENTIFICACAOCOMPLETO.DEFRAMOATIVIDADEPRIMARIO createSPCAXMLRESPOSTADEFINERESPOSTADEFIDENTIFICACAOCOMPLETODEFRAMOATIVIDADEPRIMARIO() {
        return new SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFIDENTIFICACAOCOMPLETO.DEFRAMOATIVIDADEPRIMARIO();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFIDENTIFICACAOCOMPLETO.DEFRAMOATIVIDADESECUNDARIO }
     * 
     */
    public SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFIDENTIFICACAOCOMPLETO.DEFRAMOATIVIDADESECUNDARIO createSPCAXMLRESPOSTADEFINERESPOSTADEFIDENTIFICACAOCOMPLETODEFRAMOATIVIDADESECUNDARIO() {
        return new SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFIDENTIFICACAOCOMPLETO.DEFRAMOATIVIDADESECUNDARIO();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFIDENTIFICACAOCOMPLETO.DEFDEMAISRAMOSATIVIDADE.DEFRAMOATIVIDADE }
     * 
     */
    public SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFIDENTIFICACAOCOMPLETO.DEFDEMAISRAMOSATIVIDADE.DEFRAMOATIVIDADE createSPCAXMLRESPOSTADEFINERESPOSTADEFIDENTIFICACAOCOMPLETODEFDEMAISRAMOSATIVIDADEDEFRAMOATIVIDADE() {
        return new SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFIDENTIFICACAOCOMPLETO.DEFDEMAISRAMOSATIVIDADE.DEFRAMOATIVIDADE();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFFALENCIASRECUPERACAOJUDICIAL.DEFULTIMASOCORRENCIAS.DEFFALENCIARECUPERACAOJUDICIAL }
     * 
     */
    public SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFFALENCIASRECUPERACAOJUDICIAL.DEFULTIMASOCORRENCIAS.DEFFALENCIARECUPERACAOJUDICIAL createSPCAXMLRESPOSTADEFINERESPOSTADEFFALENCIASRECUPERACAOJUDICIALDEFULTIMASOCORRENCIASDEFFALENCIARECUPERACAOJUDICIAL() {
        return new SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFFALENCIASRECUPERACAOJUDICIAL.DEFULTIMASOCORRENCIAS.DEFFALENCIARECUPERACAOJUDICIAL();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFACOESCIVEIS.DEFULTIMASOCORRENCIAS.DEFACAOCIVEL }
     * 
     */
    public SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFACOESCIVEIS.DEFULTIMASOCORRENCIAS.DEFACAOCIVEL createSPCAXMLRESPOSTADEFINERESPOSTADEFACOESCIVEISDEFULTIMASOCORRENCIASDEFACAOCIVEL() {
        return new SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFACOESCIVEIS.DEFULTIMASOCORRENCIAS.DEFACAOCIVEL();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFPROTESTOS.DEFULTIMASOCORRENCIAS.DEFPROTESTO }
     * 
     */
    public SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFPROTESTOS.DEFULTIMASOCORRENCIAS.DEFPROTESTO createSPCAXMLRESPOSTADEFINERESPOSTADEFPROTESTOSDEFULTIMASOCORRENCIASDEFPROTESTO() {
        return new SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFPROTESTOS.DEFULTIMASOCORRENCIAS.DEFPROTESTO();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFCHEQUESDEVOLVIDOSINFORMADOSUSUARIO.DEFULTIMASOCORRENCIAS.DEFCHEQUEDEVOLVIDOINFORMADOUSUARIO }
     * 
     */
    public SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFCHEQUESDEVOLVIDOSINFORMADOSUSUARIO.DEFULTIMASOCORRENCIAS.DEFCHEQUEDEVOLVIDOINFORMADOUSUARIO createSPCAXMLRESPOSTADEFINERESPOSTADEFCHEQUESDEVOLVIDOSINFORMADOSUSUARIODEFULTIMASOCORRENCIASDEFCHEQUEDEVOLVIDOINFORMADOUSUARIO() {
        return new SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFCHEQUESDEVOLVIDOSINFORMADOSUSUARIO.DEFULTIMASOCORRENCIAS.DEFCHEQUEDEVOLVIDOINFORMADOUSUARIO();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFCHEQUESSUSTADOS.DEFULTIMASOCORRENCIAS.DEFCHEQUESSUSTADO }
     * 
     */
    public SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFCHEQUESSUSTADOS.DEFULTIMASOCORRENCIAS.DEFCHEQUESSUSTADO createSPCAXMLRESPOSTADEFINERESPOSTADEFCHEQUESSUSTADOSDEFULTIMASOCORRENCIASDEFCHEQUESSUSTADO() {
        return new SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFCHEQUESSUSTADOS.DEFULTIMASOCORRENCIAS.DEFCHEQUESSUSTADO();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFCHEQUESSEMFUNDO.DEFULTIMASOCORRENCIAS.DEFCHEQUESEMFUNDO }
     * 
     */
    public SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFCHEQUESSEMFUNDO.DEFULTIMASOCORRENCIAS.DEFCHEQUESEMFUNDO createSPCAXMLRESPOSTADEFINERESPOSTADEFCHEQUESSEMFUNDODEFULTIMASOCORRENCIASDEFCHEQUESEMFUNDO() {
        return new SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFCHEQUESSEMFUNDO.DEFULTIMASOCORRENCIAS.DEFCHEQUESEMFUNDO();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFIDENTIFICACAOBASICO.DEFRAMOATIVIDADE }
     * 
     */
    public SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFIDENTIFICACAOBASICO.DEFRAMOATIVIDADE createSPCAXMLRESPOSTADEFINERESPOSTADEFIDENTIFICACAOBASICODEFRAMOATIVIDADE() {
        return new SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFIDENTIFICACAOBASICO.DEFRAMOATIVIDADE();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFPENDENCIASRESTRICOES.DEFULTIMASOCORRENCIAS.DEFPENDENCIARESTRICAO }
     * 
     */
    public SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFPENDENCIASRESTRICOES.DEFULTIMASOCORRENCIAS.DEFPENDENCIARESTRICAO createSPCAXMLRESPOSTADEFINERESPOSTADEFPENDENCIASRESTRICOESDEFULTIMASOCORRENCIASDEFPENDENCIARESTRICAO() {
        return new SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFPENDENCIASRESTRICOES.DEFULTIMASOCORRENCIAS.DEFPENDENCIARESTRICAO();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFENDERECOTELEFONESAGENCIABANCARIA.DEFENDERECOTELEFONEAGENCIA }
     * 
     */
    public SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFENDERECOTELEFONESAGENCIABANCARIA.DEFENDERECOTELEFONEAGENCIA createSPCAXMLRESPOSTADEFINERESPOSTADEFENDERECOTELEFONESAGENCIABANCARIADEFENDERECOTELEFONEAGENCIA() {
        return new SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFENDERECOTELEFONESAGENCIABANCARIA.DEFENDERECOTELEFONEAGENCIA();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFHISTORICOCONTACORRENTES.DEFHISTORICOCONTACORRENTE }
     * 
     */
    public SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFHISTORICOCONTACORRENTES.DEFHISTORICOCONTACORRENTE createSPCAXMLRESPOSTADEFINERESPOSTADEFHISTORICOCONTACORRENTESDEFHISTORICOCONTACORRENTE() {
        return new SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFHISTORICOCONTACORRENTES.DEFHISTORICOCONTACORRENTE();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFHISTORICOCHEQUEINFORMADOS.DEFHISTORICOCHEQUEINFORMADO }
     * 
     */
    public SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFHISTORICOCHEQUEINFORMADOS.DEFHISTORICOCHEQUEINFORMADO createSPCAXMLRESPOSTADEFINERESPOSTADEFHISTORICOCHEQUEINFORMADOSDEFHISTORICOCHEQUEINFORMADO() {
        return new SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFHISTORICOCHEQUEINFORMADOS.DEFHISTORICOCHEQUEINFORMADO();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFANVISA.DEFPETICOES.DEFPETICAO }
     * 
     */
    public SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFANVISA.DEFPETICOES.DEFPETICAO createSPCAXMLRESPOSTADEFINERESPOSTADEFANVISADEFPETICOESDEFPETICAO() {
        return new SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFANVISA.DEFPETICOES.DEFPETICAO();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFANVISA.DEFDISTRIBUIDORES.DEFAUTORIZACOES.DEFAUTORIZACAO }
     * 
     */
    public SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFANVISA.DEFDISTRIBUIDORES.DEFAUTORIZACOES.DEFAUTORIZACAO createSPCAXMLRESPOSTADEFINERESPOSTADEFANVISADEFDISTRIBUIDORESDEFAUTORIZACOESDEFAUTORIZACAO() {
        return new SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFANVISA.DEFDISTRIBUIDORES.DEFAUTORIZACOES.DEFAUTORIZACAO();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFANVISA.DEFFARMACIADROGARIA.DEFAUTORIZACOES.DEFAUTORIZACAO }
     * 
     */
    public SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFANVISA.DEFFARMACIADROGARIA.DEFAUTORIZACOES.DEFAUTORIZACAO createSPCAXMLRESPOSTADEFINERESPOSTADEFANVISADEFFARMACIADROGARIADEFAUTORIZACOESDEFAUTORIZACAO() {
        return new SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFANVISA.DEFFARMACIADROGARIA.DEFAUTORIZACOES.DEFAUTORIZACAO();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFPRINCIPAISFORNECEDORES.DEFFORNECEDOR.DEFCNAE }
     * 
     */
    public SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFPRINCIPAISFORNECEDORES.DEFFORNECEDOR.DEFCNAE createSPCAXMLRESPOSTADEFINERESPOSTADEFPRINCIPAISFORNECEDORESDEFFORNECEDORDEFCNAE() {
        return new SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFPRINCIPAISFORNECEDORES.DEFFORNECEDOR.DEFCNAE();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFTITULOSAVENCER.DEFTITULOSAVENCERPERIODO }
     * 
     */
    public SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFTITULOSAVENCER.DEFTITULOSAVENCERPERIODO createSPCAXMLRESPOSTADEFINERESPOSTADEFTITULOSAVENCERDEFTITULOSAVENCERPERIODO() {
        return new SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFTITULOSAVENCER.DEFTITULOSAVENCERPERIODO();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFREFERENCIAISNEGOCIOS.DEFULTIMACOMPRA }
     * 
     */
    public SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFREFERENCIAISNEGOCIOS.DEFULTIMACOMPRA createSPCAXMLRESPOSTADEFINERESPOSTADEFREFERENCIAISNEGOCIOSDEFULTIMACOMPRA() {
        return new SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFREFERENCIAISNEGOCIOS.DEFULTIMACOMPRA();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFREFERENCIAISNEGOCIOS.DEFMAIORFATURA }
     * 
     */
    public SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFREFERENCIAISNEGOCIOS.DEFMAIORFATURA createSPCAXMLRESPOSTADEFINERESPOSTADEFREFERENCIAISNEGOCIOSDEFMAIORFATURA() {
        return new SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFREFERENCIAISNEGOCIOS.DEFMAIORFATURA();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFREFERENCIAISNEGOCIOS.DEFMAIORCREDITO }
     * 
     */
    public SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFREFERENCIAISNEGOCIOS.DEFMAIORCREDITO createSPCAXMLRESPOSTADEFINERESPOSTADEFREFERENCIAISNEGOCIOSDEFMAIORCREDITO() {
        return new SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFREFERENCIAISNEGOCIOS.DEFMAIORCREDITO();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFCOMPORTAMENTOPAGAMENTOS.DEFITEM }
     * 
     */
    public SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFCOMPORTAMENTOPAGAMENTOS.DEFITEM createSPCAXMLRESPOSTADEFINERESPOSTADEFCOMPORTAMENTOPAGAMENTOSDEFITEM() {
        return new SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFCOMPORTAMENTOPAGAMENTOS.DEFITEM();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFCOMPORTAMENTOCOMSUAEMPRESA.DEFCONSULTANTE }
     * 
     */
    public SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFCOMPORTAMENTOCOMSUAEMPRESA.DEFCONSULTANTE createSPCAXMLRESPOSTADEFINERESPOSTADEFCOMPORTAMENTOCOMSUAEMPRESADEFCONSULTANTE() {
        return new SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFCOMPORTAMENTOCOMSUAEMPRESA.DEFCONSULTANTE();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFCOMPORTAMENTOCOMSUAEMPRESA.DEFSEGMENTO }
     * 
     */
    public SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFCOMPORTAMENTOCOMSUAEMPRESA.DEFSEGMENTO createSPCAXMLRESPOSTADEFINERESPOSTADEFCOMPORTAMENTOCOMSUAEMPRESADEFSEGMENTO() {
        return new SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFCOMPORTAMENTOCOMSUAEMPRESA.DEFSEGMENTO();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFCOMPORTAMENTOCOMSUAEMPRESA.DEFMERCADO }
     * 
     */
    public SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFCOMPORTAMENTOCOMSUAEMPRESA.DEFMERCADO createSPCAXMLRESPOSTADEFINERESPOSTADEFCOMPORTAMENTOCOMSUAEMPRESADEFMERCADO() {
        return new SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFCOMPORTAMENTOCOMSUAEMPRESA.DEFMERCADO();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFULTIMASCONSULTAS.DEFULTIMACONSULTA }
     * 
     */
    public SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFULTIMASCONSULTAS.DEFULTIMACONSULTA createSPCAXMLRESPOSTADEFINERESPOSTADEFULTIMASCONSULTASDEFULTIMACONSULTA() {
        return new SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFULTIMASCONSULTAS.DEFULTIMACONSULTA();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFCONSULTAS.DEFCONSULTASMES }
     * 
     */
    public SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFCONSULTAS.DEFCONSULTASMES createSPCAXMLRESPOSTADEFINERESPOSTADEFCONSULTASDEFCONSULTASMES() {
        return new SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFCONSULTAS.DEFCONSULTASMES();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFCONSULTAS.DEFULTIMASCONSULTAS.DEFCONSULTA }
     * 
     */
    public SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFCONSULTAS.DEFULTIMASCONSULTAS.DEFCONSULTA createSPCAXMLRESPOSTADEFINERESPOSTADEFCONSULTASDEFULTIMASCONSULTASDEFCONSULTA() {
        return new SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFCONSULTAS.DEFULTIMASCONSULTAS.DEFCONSULTA();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFPARTICIPACOESEMPRESASCONSULTADAS.DEFPARTICIPACAOEMPRESACONSULTADA.DEFRESTRICOESDOCUMENTO.DEFPENDENCIASRESTRICOES }
     * 
     */
    public SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFPARTICIPACOESEMPRESASCONSULTADAS.DEFPARTICIPACAOEMPRESACONSULTADA.DEFRESTRICOESDOCUMENTO.DEFPENDENCIASRESTRICOES createSPCAXMLRESPOSTADEFINERESPOSTADEFPARTICIPACOESEMPRESASCONSULTADASDEFPARTICIPACAOEMPRESACONSULTADADEFRESTRICOESDOCUMENTODEFPENDENCIASRESTRICOES() {
        return new SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFPARTICIPACOESEMPRESASCONSULTADAS.DEFPARTICIPACAOEMPRESACONSULTADA.DEFRESTRICOESDOCUMENTO.DEFPENDENCIASRESTRICOES();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFPARTICIPACOESEMPRESASCONSULTADAS.DEFPARTICIPACAOEMPRESACONSULTADA.DEFRESTRICOESDOCUMENTO.DEFCHEQUESSEMFUNDO }
     * 
     */
    public SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFPARTICIPACOESEMPRESASCONSULTADAS.DEFPARTICIPACAOEMPRESACONSULTADA.DEFRESTRICOESDOCUMENTO.DEFCHEQUESSEMFUNDO createSPCAXMLRESPOSTADEFINERESPOSTADEFPARTICIPACOESEMPRESASCONSULTADASDEFPARTICIPACAOEMPRESACONSULTADADEFRESTRICOESDOCUMENTODEFCHEQUESSEMFUNDO() {
        return new SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFPARTICIPACOESEMPRESASCONSULTADAS.DEFPARTICIPACAOEMPRESACONSULTADA.DEFRESTRICOESDOCUMENTO.DEFCHEQUESSEMFUNDO();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFPARTICIPACOESEMPRESASCONSULTADAS.DEFPARTICIPACAOEMPRESACONSULTADA.DEFRESTRICOESDOCUMENTO.DEFPROTESTOS }
     * 
     */
    public SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFPARTICIPACOESEMPRESASCONSULTADAS.DEFPARTICIPACAOEMPRESACONSULTADA.DEFRESTRICOESDOCUMENTO.DEFPROTESTOS createSPCAXMLRESPOSTADEFINERESPOSTADEFPARTICIPACOESEMPRESASCONSULTADASDEFPARTICIPACAOEMPRESACONSULTADADEFRESTRICOESDOCUMENTODEFPROTESTOS() {
        return new SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFPARTICIPACOESEMPRESASCONSULTADAS.DEFPARTICIPACAOEMPRESACONSULTADA.DEFRESTRICOESDOCUMENTO.DEFPROTESTOS();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFPARTICIPACOESEMPRESASCONSULTADAS.DEFPARTICIPACAOEMPRESACONSULTADA.DEFRESTRICOESDOCUMENTO.DEFACOESJUDICIAIS }
     * 
     */
    public SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFPARTICIPACOESEMPRESASCONSULTADAS.DEFPARTICIPACAOEMPRESACONSULTADA.DEFRESTRICOESDOCUMENTO.DEFACOESJUDICIAIS createSPCAXMLRESPOSTADEFINERESPOSTADEFPARTICIPACOESEMPRESASCONSULTADASDEFPARTICIPACAOEMPRESACONSULTADADEFRESTRICOESDOCUMENTODEFACOESJUDICIAIS() {
        return new SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFPARTICIPACOESEMPRESASCONSULTADAS.DEFPARTICIPACAOEMPRESACONSULTADA.DEFRESTRICOESDOCUMENTO.DEFACOESJUDICIAIS();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFPARTICIPACOESEMPRESASCONSULTADAS.DEFPARTICIPACAOEMPRESACONSULTADA.DEFRESTRICOESDOCUMENTO.DEFFALENCIASRECUPERACAOJUDICIAL }
     * 
     */
    public SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFPARTICIPACOESEMPRESASCONSULTADAS.DEFPARTICIPACAOEMPRESACONSULTADA.DEFRESTRICOESDOCUMENTO.DEFFALENCIASRECUPERACAOJUDICIAL createSPCAXMLRESPOSTADEFINERESPOSTADEFPARTICIPACOESEMPRESASCONSULTADASDEFPARTICIPACAOEMPRESACONSULTADADEFRESTRICOESDOCUMENTODEFFALENCIASRECUPERACAOJUDICIAL() {
        return new SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFPARTICIPACOESEMPRESASCONSULTADAS.DEFPARTICIPACAOEMPRESACONSULTADA.DEFRESTRICOESDOCUMENTO.DEFFALENCIASRECUPERACAOJUDICIAL();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFPARTICIPACOESEMPRESASCONSULTADAS.DEFPARTICIPACAOEMPRESACONSULTADA.DEFRESTRICOESDOCUMENTO.DEFCONSULTAS }
     * 
     */
    public SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFPARTICIPACOESEMPRESASCONSULTADAS.DEFPARTICIPACAOEMPRESACONSULTADA.DEFRESTRICOESDOCUMENTO.DEFCONSULTAS createSPCAXMLRESPOSTADEFINERESPOSTADEFPARTICIPACOESEMPRESASCONSULTADASDEFPARTICIPACAOEMPRESACONSULTADADEFRESTRICOESDOCUMENTODEFCONSULTAS() {
        return new SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFPARTICIPACOESEMPRESASCONSULTADAS.DEFPARTICIPACAOEMPRESACONSULTADA.DEFRESTRICOESDOCUMENTO.DEFCONSULTAS();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFPARTICIPACOESEMPRESASCONSULTADAS.DEFPARTICIPACAOEMPRESACONSULTADA.DEFRESTRICOESDOCUMENTO.DEFTITULOSVENCER }
     * 
     */
    public SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFPARTICIPACOESEMPRESASCONSULTADAS.DEFPARTICIPACAOEMPRESACONSULTADA.DEFRESTRICOESDOCUMENTO.DEFTITULOSVENCER createSPCAXMLRESPOSTADEFINERESPOSTADEFPARTICIPACOESEMPRESASCONSULTADASDEFPARTICIPACAOEMPRESACONSULTADADEFRESTRICOESDOCUMENTODEFTITULOSVENCER() {
        return new SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFPARTICIPACOESEMPRESASCONSULTADAS.DEFPARTICIPACAOEMPRESACONSULTADA.DEFRESTRICOESDOCUMENTO.DEFTITULOSVENCER();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFPARTICIPACOESEMPRESASCONSULTADAS.DEFPARTICIPACAOEMPRESACONSULTADA.DEFRESTRICOESDOCUMENTO.DEFPAGAMENTOS }
     * 
     */
    public SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFPARTICIPACOESEMPRESASCONSULTADAS.DEFPARTICIPACAOEMPRESACONSULTADA.DEFRESTRICOESDOCUMENTO.DEFPAGAMENTOS createSPCAXMLRESPOSTADEFINERESPOSTADEFPARTICIPACOESEMPRESASCONSULTADASDEFPARTICIPACAOEMPRESACONSULTADADEFRESTRICOESDOCUMENTODEFPAGAMENTOS() {
        return new SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFPARTICIPACOESEMPRESASCONSULTADAS.DEFPARTICIPACAOEMPRESACONSULTADA.DEFRESTRICOESDOCUMENTO.DEFPAGAMENTOS();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFPARTICIPACOESSOCIOSADMOUTRASEMPRESAS.DEFSOCIO.DEFSOCIOSPARTICIPANTES.DEFRESTRICOESDOCUMENTO.DEFPENDENCIASRESTRICOES }
     * 
     */
    public SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFPARTICIPACOESSOCIOSADMOUTRASEMPRESAS.DEFSOCIO.DEFSOCIOSPARTICIPANTES.DEFRESTRICOESDOCUMENTO.DEFPENDENCIASRESTRICOES createSPCAXMLRESPOSTADEFINERESPOSTADEFPARTICIPACOESSOCIOSADMOUTRASEMPRESASDEFSOCIODEFSOCIOSPARTICIPANTESDEFRESTRICOESDOCUMENTODEFPENDENCIASRESTRICOES() {
        return new SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFPARTICIPACOESSOCIOSADMOUTRASEMPRESAS.DEFSOCIO.DEFSOCIOSPARTICIPANTES.DEFRESTRICOESDOCUMENTO.DEFPENDENCIASRESTRICOES();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFPARTICIPACOESSOCIOSADMOUTRASEMPRESAS.DEFSOCIO.DEFSOCIOSPARTICIPANTES.DEFRESTRICOESDOCUMENTO.DEFCHEQUESSEMFUNDO }
     * 
     */
    public SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFPARTICIPACOESSOCIOSADMOUTRASEMPRESAS.DEFSOCIO.DEFSOCIOSPARTICIPANTES.DEFRESTRICOESDOCUMENTO.DEFCHEQUESSEMFUNDO createSPCAXMLRESPOSTADEFINERESPOSTADEFPARTICIPACOESSOCIOSADMOUTRASEMPRESASDEFSOCIODEFSOCIOSPARTICIPANTESDEFRESTRICOESDOCUMENTODEFCHEQUESSEMFUNDO() {
        return new SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFPARTICIPACOESSOCIOSADMOUTRASEMPRESAS.DEFSOCIO.DEFSOCIOSPARTICIPANTES.DEFRESTRICOESDOCUMENTO.DEFCHEQUESSEMFUNDO();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFPARTICIPACOESSOCIOSADMOUTRASEMPRESAS.DEFSOCIO.DEFSOCIOSPARTICIPANTES.DEFRESTRICOESDOCUMENTO.DEFPROTESTOS }
     * 
     */
    public SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFPARTICIPACOESSOCIOSADMOUTRASEMPRESAS.DEFSOCIO.DEFSOCIOSPARTICIPANTES.DEFRESTRICOESDOCUMENTO.DEFPROTESTOS createSPCAXMLRESPOSTADEFINERESPOSTADEFPARTICIPACOESSOCIOSADMOUTRASEMPRESASDEFSOCIODEFSOCIOSPARTICIPANTESDEFRESTRICOESDOCUMENTODEFPROTESTOS() {
        return new SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFPARTICIPACOESSOCIOSADMOUTRASEMPRESAS.DEFSOCIO.DEFSOCIOSPARTICIPANTES.DEFRESTRICOESDOCUMENTO.DEFPROTESTOS();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFPARTICIPACOESSOCIOSADMOUTRASEMPRESAS.DEFSOCIO.DEFSOCIOSPARTICIPANTES.DEFRESTRICOESDOCUMENTO.DEFACOESJUDICIAIS }
     * 
     */
    public SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFPARTICIPACOESSOCIOSADMOUTRASEMPRESAS.DEFSOCIO.DEFSOCIOSPARTICIPANTES.DEFRESTRICOESDOCUMENTO.DEFACOESJUDICIAIS createSPCAXMLRESPOSTADEFINERESPOSTADEFPARTICIPACOESSOCIOSADMOUTRASEMPRESASDEFSOCIODEFSOCIOSPARTICIPANTESDEFRESTRICOESDOCUMENTODEFACOESJUDICIAIS() {
        return new SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFPARTICIPACOESSOCIOSADMOUTRASEMPRESAS.DEFSOCIO.DEFSOCIOSPARTICIPANTES.DEFRESTRICOESDOCUMENTO.DEFACOESJUDICIAIS();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFPARTICIPACOESSOCIOSADMOUTRASEMPRESAS.DEFSOCIO.DEFSOCIOSPARTICIPANTES.DEFRESTRICOESDOCUMENTO.DEFFALENCIASRECUPERACAOJUDICIAL }
     * 
     */
    public SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFPARTICIPACOESSOCIOSADMOUTRASEMPRESAS.DEFSOCIO.DEFSOCIOSPARTICIPANTES.DEFRESTRICOESDOCUMENTO.DEFFALENCIASRECUPERACAOJUDICIAL createSPCAXMLRESPOSTADEFINERESPOSTADEFPARTICIPACOESSOCIOSADMOUTRASEMPRESASDEFSOCIODEFSOCIOSPARTICIPANTESDEFRESTRICOESDOCUMENTODEFFALENCIASRECUPERACAOJUDICIAL() {
        return new SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFPARTICIPACOESSOCIOSADMOUTRASEMPRESAS.DEFSOCIO.DEFSOCIOSPARTICIPANTES.DEFRESTRICOESDOCUMENTO.DEFFALENCIASRECUPERACAOJUDICIAL();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFPARTICIPACOESSOCIOSADMOUTRASEMPRESAS.DEFSOCIO.DEFSOCIOSPARTICIPANTES.DEFRESTRICOESDOCUMENTO.DEFCONSULTAS }
     * 
     */
    public SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFPARTICIPACOESSOCIOSADMOUTRASEMPRESAS.DEFSOCIO.DEFSOCIOSPARTICIPANTES.DEFRESTRICOESDOCUMENTO.DEFCONSULTAS createSPCAXMLRESPOSTADEFINERESPOSTADEFPARTICIPACOESSOCIOSADMOUTRASEMPRESASDEFSOCIODEFSOCIOSPARTICIPANTESDEFRESTRICOESDOCUMENTODEFCONSULTAS() {
        return new SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFPARTICIPACOESSOCIOSADMOUTRASEMPRESAS.DEFSOCIO.DEFSOCIOSPARTICIPANTES.DEFRESTRICOESDOCUMENTO.DEFCONSULTAS();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFPARTICIPACOESSOCIOSADMOUTRASEMPRESAS.DEFSOCIO.DEFSOCIOSPARTICIPANTES.DEFRESTRICOESDOCUMENTO.DEFTITULOSVENCER }
     * 
     */
    public SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFPARTICIPACOESSOCIOSADMOUTRASEMPRESAS.DEFSOCIO.DEFSOCIOSPARTICIPANTES.DEFRESTRICOESDOCUMENTO.DEFTITULOSVENCER createSPCAXMLRESPOSTADEFINERESPOSTADEFPARTICIPACOESSOCIOSADMOUTRASEMPRESASDEFSOCIODEFSOCIOSPARTICIPANTESDEFRESTRICOESDOCUMENTODEFTITULOSVENCER() {
        return new SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFPARTICIPACOESSOCIOSADMOUTRASEMPRESAS.DEFSOCIO.DEFSOCIOSPARTICIPANTES.DEFRESTRICOESDOCUMENTO.DEFTITULOSVENCER();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFPARTICIPACOESSOCIOSADMOUTRASEMPRESAS.DEFSOCIO.DEFSOCIOSPARTICIPANTES.DEFRESTRICOESDOCUMENTO.DEFPAGAMENTOS }
     * 
     */
    public SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFPARTICIPACOESSOCIOSADMOUTRASEMPRESAS.DEFSOCIO.DEFSOCIOSPARTICIPANTES.DEFRESTRICOESDOCUMENTO.DEFPAGAMENTOS createSPCAXMLRESPOSTADEFINERESPOSTADEFPARTICIPACOESSOCIOSADMOUTRASEMPRESASDEFSOCIODEFSOCIOSPARTICIPANTESDEFRESTRICOESDOCUMENTODEFPAGAMENTOS() {
        return new SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFPARTICIPACOESSOCIOSADMOUTRASEMPRESAS.DEFSOCIO.DEFSOCIOSPARTICIPANTES.DEFRESTRICOESDOCUMENTO.DEFPAGAMENTOS();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFADMINISTRADORES.DEFADMINISTRADOR.DEFRESTRICOESDOCUMENTO.DEFPENDENCIASRESTRICOES }
     * 
     */
    public SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFADMINISTRADORES.DEFADMINISTRADOR.DEFRESTRICOESDOCUMENTO.DEFPENDENCIASRESTRICOES createSPCAXMLRESPOSTADEFINERESPOSTADEFADMINISTRADORESDEFADMINISTRADORDEFRESTRICOESDOCUMENTODEFPENDENCIASRESTRICOES() {
        return new SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFADMINISTRADORES.DEFADMINISTRADOR.DEFRESTRICOESDOCUMENTO.DEFPENDENCIASRESTRICOES();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFADMINISTRADORES.DEFADMINISTRADOR.DEFRESTRICOESDOCUMENTO.DEFCHEQUESSEMFUNDO }
     * 
     */
    public SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFADMINISTRADORES.DEFADMINISTRADOR.DEFRESTRICOESDOCUMENTO.DEFCHEQUESSEMFUNDO createSPCAXMLRESPOSTADEFINERESPOSTADEFADMINISTRADORESDEFADMINISTRADORDEFRESTRICOESDOCUMENTODEFCHEQUESSEMFUNDO() {
        return new SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFADMINISTRADORES.DEFADMINISTRADOR.DEFRESTRICOESDOCUMENTO.DEFCHEQUESSEMFUNDO();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFADMINISTRADORES.DEFADMINISTRADOR.DEFRESTRICOESDOCUMENTO.DEFPROTESTOS }
     * 
     */
    public SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFADMINISTRADORES.DEFADMINISTRADOR.DEFRESTRICOESDOCUMENTO.DEFPROTESTOS createSPCAXMLRESPOSTADEFINERESPOSTADEFADMINISTRADORESDEFADMINISTRADORDEFRESTRICOESDOCUMENTODEFPROTESTOS() {
        return new SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFADMINISTRADORES.DEFADMINISTRADOR.DEFRESTRICOESDOCUMENTO.DEFPROTESTOS();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFADMINISTRADORES.DEFADMINISTRADOR.DEFRESTRICOESDOCUMENTO.DEFACOESJUDICIAIS }
     * 
     */
    public SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFADMINISTRADORES.DEFADMINISTRADOR.DEFRESTRICOESDOCUMENTO.DEFACOESJUDICIAIS createSPCAXMLRESPOSTADEFINERESPOSTADEFADMINISTRADORESDEFADMINISTRADORDEFRESTRICOESDOCUMENTODEFACOESJUDICIAIS() {
        return new SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFADMINISTRADORES.DEFADMINISTRADOR.DEFRESTRICOESDOCUMENTO.DEFACOESJUDICIAIS();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFADMINISTRADORES.DEFADMINISTRADOR.DEFRESTRICOESDOCUMENTO.DEFFALENCIASRECUPERACAOJUDICIAL }
     * 
     */
    public SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFADMINISTRADORES.DEFADMINISTRADOR.DEFRESTRICOESDOCUMENTO.DEFFALENCIASRECUPERACAOJUDICIAL createSPCAXMLRESPOSTADEFINERESPOSTADEFADMINISTRADORESDEFADMINISTRADORDEFRESTRICOESDOCUMENTODEFFALENCIASRECUPERACAOJUDICIAL() {
        return new SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFADMINISTRADORES.DEFADMINISTRADOR.DEFRESTRICOESDOCUMENTO.DEFFALENCIASRECUPERACAOJUDICIAL();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFADMINISTRADORES.DEFADMINISTRADOR.DEFRESTRICOESDOCUMENTO.DEFCONSULTAS }
     * 
     */
    public SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFADMINISTRADORES.DEFADMINISTRADOR.DEFRESTRICOESDOCUMENTO.DEFCONSULTAS createSPCAXMLRESPOSTADEFINERESPOSTADEFADMINISTRADORESDEFADMINISTRADORDEFRESTRICOESDOCUMENTODEFCONSULTAS() {
        return new SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFADMINISTRADORES.DEFADMINISTRADOR.DEFRESTRICOESDOCUMENTO.DEFCONSULTAS();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFADMINISTRADORES.DEFADMINISTRADOR.DEFRESTRICOESDOCUMENTO.DEFTITULOSVENCER }
     * 
     */
    public SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFADMINISTRADORES.DEFADMINISTRADOR.DEFRESTRICOESDOCUMENTO.DEFTITULOSVENCER createSPCAXMLRESPOSTADEFINERESPOSTADEFADMINISTRADORESDEFADMINISTRADORDEFRESTRICOESDOCUMENTODEFTITULOSVENCER() {
        return new SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFADMINISTRADORES.DEFADMINISTRADOR.DEFRESTRICOESDOCUMENTO.DEFTITULOSVENCER();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFADMINISTRADORES.DEFADMINISTRADOR.DEFRESTRICOESDOCUMENTO.DEFPAGAMENTOS }
     * 
     */
    public SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFADMINISTRADORES.DEFADMINISTRADOR.DEFRESTRICOESDOCUMENTO.DEFPAGAMENTOS createSPCAXMLRESPOSTADEFINERESPOSTADEFADMINISTRADORESDEFADMINISTRADORDEFRESTRICOESDOCUMENTODEFPAGAMENTOS() {
        return new SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFADMINISTRADORES.DEFADMINISTRADOR.DEFRESTRICOESDOCUMENTO.DEFPAGAMENTOS();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFSOCIOS.DEFSOCIO.DEFRESTRICOESDOCUMENTO.DEFPENDENCIASRESTRICOES }
     * 
     */
    public SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFSOCIOS.DEFSOCIO.DEFRESTRICOESDOCUMENTO.DEFPENDENCIASRESTRICOES createSPCAXMLRESPOSTADEFINERESPOSTADEFSOCIOSDEFSOCIODEFRESTRICOESDOCUMENTODEFPENDENCIASRESTRICOES() {
        return new SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFSOCIOS.DEFSOCIO.DEFRESTRICOESDOCUMENTO.DEFPENDENCIASRESTRICOES();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFSOCIOS.DEFSOCIO.DEFRESTRICOESDOCUMENTO.DEFCHEQUESSEMFUNDO }
     * 
     */
    public SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFSOCIOS.DEFSOCIO.DEFRESTRICOESDOCUMENTO.DEFCHEQUESSEMFUNDO createSPCAXMLRESPOSTADEFINERESPOSTADEFSOCIOSDEFSOCIODEFRESTRICOESDOCUMENTODEFCHEQUESSEMFUNDO() {
        return new SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFSOCIOS.DEFSOCIO.DEFRESTRICOESDOCUMENTO.DEFCHEQUESSEMFUNDO();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFSOCIOS.DEFSOCIO.DEFRESTRICOESDOCUMENTO.DEFPROTESTOS }
     * 
     */
    public SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFSOCIOS.DEFSOCIO.DEFRESTRICOESDOCUMENTO.DEFPROTESTOS createSPCAXMLRESPOSTADEFINERESPOSTADEFSOCIOSDEFSOCIODEFRESTRICOESDOCUMENTODEFPROTESTOS() {
        return new SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFSOCIOS.DEFSOCIO.DEFRESTRICOESDOCUMENTO.DEFPROTESTOS();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFSOCIOS.DEFSOCIO.DEFRESTRICOESDOCUMENTO.DEFACOESJUDICIAIS }
     * 
     */
    public SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFSOCIOS.DEFSOCIO.DEFRESTRICOESDOCUMENTO.DEFACOESJUDICIAIS createSPCAXMLRESPOSTADEFINERESPOSTADEFSOCIOSDEFSOCIODEFRESTRICOESDOCUMENTODEFACOESJUDICIAIS() {
        return new SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFSOCIOS.DEFSOCIO.DEFRESTRICOESDOCUMENTO.DEFACOESJUDICIAIS();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFSOCIOS.DEFSOCIO.DEFRESTRICOESDOCUMENTO.DEFFALENCIASRECUPERACAOJUDICIAL }
     * 
     */
    public SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFSOCIOS.DEFSOCIO.DEFRESTRICOESDOCUMENTO.DEFFALENCIASRECUPERACAOJUDICIAL createSPCAXMLRESPOSTADEFINERESPOSTADEFSOCIOSDEFSOCIODEFRESTRICOESDOCUMENTODEFFALENCIASRECUPERACAOJUDICIAL() {
        return new SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFSOCIOS.DEFSOCIO.DEFRESTRICOESDOCUMENTO.DEFFALENCIASRECUPERACAOJUDICIAL();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFSOCIOS.DEFSOCIO.DEFRESTRICOESDOCUMENTO.DEFCONSULTAS }
     * 
     */
    public SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFSOCIOS.DEFSOCIO.DEFRESTRICOESDOCUMENTO.DEFCONSULTAS createSPCAXMLRESPOSTADEFINERESPOSTADEFSOCIOSDEFSOCIODEFRESTRICOESDOCUMENTODEFCONSULTAS() {
        return new SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFSOCIOS.DEFSOCIO.DEFRESTRICOESDOCUMENTO.DEFCONSULTAS();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFSOCIOS.DEFSOCIO.DEFRESTRICOESDOCUMENTO.DEFTITULOSVENCER }
     * 
     */
    public SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFSOCIOS.DEFSOCIO.DEFRESTRICOESDOCUMENTO.DEFTITULOSVENCER createSPCAXMLRESPOSTADEFINERESPOSTADEFSOCIOSDEFSOCIODEFRESTRICOESDOCUMENTODEFTITULOSVENCER() {
        return new SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFSOCIOS.DEFSOCIO.DEFRESTRICOESDOCUMENTO.DEFTITULOSVENCER();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFSOCIOS.DEFSOCIO.DEFRESTRICOESDOCUMENTO.DEFPAGAMENTOS }
     * 
     */
    public SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFSOCIOS.DEFSOCIO.DEFRESTRICOESDOCUMENTO.DEFPAGAMENTOS createSPCAXMLRESPOSTADEFINERESPOSTADEFSOCIOSDEFSOCIODEFRESTRICOESDOCUMENTODEFPAGAMENTOS() {
        return new SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFSOCIOS.DEFSOCIO.DEFRESTRICOESDOCUMENTO.DEFPAGAMENTOS();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFEMPRESASSITUADANOMESMOENDERECO.DEFEMPRESASITUADANOMESMOENDERECO }
     * 
     */
    public SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFEMPRESASSITUADANOMESMOENDERECO.DEFEMPRESASITUADANOMESMOENDERECO createSPCAXMLRESPOSTADEFINERESPOSTADEFEMPRESASSITUADANOMESMOENDERECODEFEMPRESASITUADANOMESMOENDERECO() {
        return new SPCAXML.RESPOSTA.DEFINERESPOSTA.DEFEMPRESASSITUADANOMESMOENDERECO.DEFEMPRESASITUADANOMESMOENDERECO();
    }

    /**
     * Create an instance of {@link SPCAXML.SOLICITACAO.SDEFINEPRODUTO }
     * 
     */
    public SPCAXML.SOLICITACAO.SDEFINEPRODUTO createSPCAXMLSOLICITACAOSDEFINEPRODUTO() {
        return new SPCAXML.SOLICITACAO.SDEFINEPRODUTO();
    }

}
