//
// Este arquivo foi gerado pela Arquitetura JavaTM para Implementação de Referência (JAXB) de Bind XML, v2.2.8-b130911.1802 
// Consulte <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Todas as modificações neste arquivo serão perdidas após a recompilação do esquema de origem. 
// Gerado em: 2018.07.12 às 07:54:34 PM BRT 
//


package br.wsorpec.wscdlrio.pessoalGold;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generated package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SPCAXML }
     * 
     */
    public SPCAXML createSPCAXML() {
        return new SPCAXML();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA }
     * 
     */
    public SPCAXML.RESPOSTA createSPCAXMLRESPOSTA() {
        return new SPCAXML.RESPOSTA();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.REGISTROACSPSPCA }
     * 
     */
    public SPCAXML.RESPOSTA.REGISTROACSPSPCA createSPCAXMLRESPOSTAREGISTROACSPSPCA() {
        return new SPCAXML.RESPOSTA.REGISTROACSPSPCA();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA601SCORECRED }
     * 
     */
    public SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA601SCORECRED createSPCAXMLRESPOSTAREGISTROACSPSPCASPCA601SCORECRED() {
        return new SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA601SCORECRED();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA295RELACAO }
     * 
     */
    public SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA295RELACAO createSPCAXMLRESPOSTAREGISTROACSPSPCASPCA295RELACAO() {
        return new SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA295RELACAO();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA282PARTICIPACAO }
     * 
     */
    public SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA282PARTICIPACAO createSPCAXMLRESPOSTAREGISTROACSPSPCASPCA282PARTICIPACAO() {
        return new SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA282PARTICIPACAO();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA282PARTICIPACAO.SPCA282OUTRAS }
     * 
     */
    public SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA282PARTICIPACAO.SPCA282OUTRAS createSPCAXMLRESPOSTAREGISTROACSPSPCASPCA282PARTICIPACAOSPCA282OUTRAS() {
        return new SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA282PARTICIPACAO.SPCA282OUTRAS();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA268CHDEVOLVIDO }
     * 
     */
    public SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA268CHDEVOLVIDO createSPCAXMLRESPOSTAREGISTROACSPSPCASPCA268CHDEVOLVIDO() {
        return new SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA268CHDEVOLVIDO();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA268CHDEVOLVIDO.SPCA268USUARIOS }
     * 
     */
    public SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA268CHDEVOLVIDO.SPCA268USUARIOS createSPCAXMLRESPOSTAREGISTROACSPSPCASPCA268CHDEVOLVIDOSPCA268USUARIOS() {
        return new SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA268CHDEVOLVIDO.SPCA268USUARIOS();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA248CONSULTA }
     * 
     */
    public SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA248CONSULTA createSPCAXMLRESPOSTAREGISTROACSPSPCASPCA248CONSULTA() {
        return new SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA248CONSULTA();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA248CONSULTA.SPCA248CHEQUE }
     * 
     */
    public SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA248CONSULTA.SPCA248CHEQUE createSPCAXMLRESPOSTAREGISTROACSPSPCASPCA248CONSULTASPCA248CHEQUE() {
        return new SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA248CONSULTA.SPCA248CHEQUE();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA247HISTORICO }
     * 
     */
    public SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA247HISTORICO createSPCAXMLRESPOSTAREGISTROACSPSPCASPCA247HISTORICO() {
        return new SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA247HISTORICO();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA247HISTORICO.SPCA247DACONTA }
     * 
     */
    public SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA247HISTORICO.SPCA247DACONTA createSPCAXMLRESPOSTAREGISTROACSPSPCASPCA247HISTORICOSPCA247DACONTA() {
        return new SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA247HISTORICO.SPCA247DACONTA();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA246HISTORICO }
     * 
     */
    public SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA246HISTORICO createSPCAXMLRESPOSTAREGISTROACSPSPCASPCA246HISTORICO() {
        return new SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA246HISTORICO();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA246HISTORICO.SPCA246CHEQUES }
     * 
     */
    public SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA246HISTORICO.SPCA246CHEQUES createSPCAXMLRESPOSTAREGISTROACSPSPCASPCA246HISTORICOSPCA246CHEQUES() {
        return new SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA246HISTORICO.SPCA246CHEQUES();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA245CHSUSTADO21 }
     * 
     */
    public SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA245CHSUSTADO21 createSPCAXMLRESPOSTAREGISTROACSPSPCASPCA245CHSUSTADO21() {
        return new SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA245CHSUSTADO21();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA245CHSUSTADO21 .SPCA245ALINEA21 }
     * 
     */
    public SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA245CHSUSTADO21 .SPCA245ALINEA21 createSPCAXMLRESPOSTAREGISTROACSPSPCASPCA245CHSUSTADO21SPCA245ALINEA21() {
        return new SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA245CHSUSTADO21 .SPCA245ALINEA21();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA244CHDEVOLUCAO }
     * 
     */
    public SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA244CHDEVOLUCAO createSPCAXMLRESPOSTAREGISTROACSPSPCASPCA244CHDEVOLUCAO() {
        return new SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA244CHDEVOLUCAO();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA244CHDEVOLUCAO.SPCA244PORUSUARIO }
     * 
     */
    public SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA244CHDEVOLUCAO.SPCA244PORUSUARIO createSPCAXMLRESPOSTAREGISTROACSPSPCASPCA244CHDEVOLUCAOSPCA244PORUSUARIO() {
        return new SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA244CHDEVOLUCAO.SPCA244PORUSUARIO();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA243INFORMACAO }
     * 
     */
    public SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA243INFORMACAO createSPCAXMLRESPOSTAREGISTROACSPSPCASPCA243INFORMACAO() {
        return new SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA243INFORMACAO();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA242CCF }
     * 
     */
    public SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA242CCF createSPCAXMLRESPOSTAREGISTROACSPSPCASPCA242CCF() {
        return new SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA242CCF();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA242CCF.SPCA242DEVOLUCOES }
     * 
     */
    public SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA242CCF.SPCA242DEVOLUCOES createSPCAXMLRESPOSTAREGISTROACSPSPCASPCA242CCFSPCA242DEVOLUCOES() {
        return new SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA242CCF.SPCA242DEVOLUCOES();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA227CEP }
     * 
     */
    public SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA227CEP createSPCAXMLRESPOSTAREGISTROACSPSPCASPCA227CEP() {
        return new SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA227CEP();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA224ENDERECODA }
     * 
     */
    public SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA224ENDERECODA createSPCAXMLRESPOSTAREGISTROACSPSPCASPCA224ENDERECODA() {
        return new SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA224ENDERECODA();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA223TELEFONE }
     * 
     */
    public SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA223TELEFONE createSPCAXMLRESPOSTAREGISTROACSPSPCASPCA223TELEFONE() {
        return new SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA223TELEFONE();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA220CONSULTASCH }
     * 
     */
    public SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA220CONSULTASCH createSPCAXMLRESPOSTAREGISTROACSPSPCASPCA220CONSULTASCH() {
        return new SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA220CONSULTASCH();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA220CONSULTASCH.SPCA220RESUMO }
     * 
     */
    public SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA220CONSULTASCH.SPCA220RESUMO createSPCAXMLRESPOSTAREGISTROACSPSPCASPCA220CONSULTASCHSPCA220RESUMO() {
        return new SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA220CONSULTASCH.SPCA220RESUMO();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA214CCFRESUMO }
     * 
     */
    public SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA214CCFRESUMO createSPCAXMLRESPOSTAREGISTROACSPSPCASPCA214CCFRESUMO() {
        return new SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA214CCFRESUMO();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA214CCFRESUMO.SPCA214DEVOLUCOES }
     * 
     */
    public SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA214CCFRESUMO.SPCA214DEVOLUCOES createSPCAXMLRESPOSTAREGISTROACSPSPCASPCA214CCFRESUMOSPCA214DEVOLUCOES() {
        return new SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA214CCFRESUMO.SPCA214DEVOLUCOES();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA211SUSTADO }
     * 
     */
    public SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA211SUSTADO createSPCAXMLRESPOSTAREGISTROACSPSPCASPCA211SUSTADO() {
        return new SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA211SUSTADO();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA211SUSTADO.SPCA211CHQTALAO }
     * 
     */
    public SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA211SUSTADO.SPCA211CHQTALAO createSPCAXMLRESPOSTAREGISTROACSPSPCASPCA211SUSTADOSPCA211CHQTALAO() {
        return new SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA211SUSTADO.SPCA211CHQTALAO();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA137CONSULTA }
     * 
     */
    public SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA137CONSULTA createSPCAXMLRESPOSTAREGISTROACSPSPCASPCA137CONSULTA() {
        return new SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA137CONSULTA();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA137CONSULTA.SPCA137SEGMENTADO }
     * 
     */
    public SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA137CONSULTA.SPCA137SEGMENTADO createSPCAXMLRESPOSTAREGISTROACSPSPCASPCA137CONSULTASPCA137SEGMENTADO() {
        return new SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA137CONSULTA.SPCA137SEGMENTADO();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA137CONSULTA.SPCA137SEGMENTADO.SPCA137DADOS }
     * 
     */
    public SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA137CONSULTA.SPCA137SEGMENTADO.SPCA137DADOS createSPCAXMLRESPOSTAREGISTROACSPSPCASPCA137CONSULTASPCA137SEGMENTADOSPCA137DADOS() {
        return new SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA137CONSULTA.SPCA137SEGMENTADO.SPCA137DADOS();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA136CONSULTA }
     * 
     */
    public SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA136CONSULTA createSPCAXMLRESPOSTAREGISTROACSPSPCASPCA136CONSULTA() {
        return new SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA136CONSULTA();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA136CONSULTA.SPCA136RESUMO }
     * 
     */
    public SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA136CONSULTA.SPCA136RESUMO createSPCAXMLRESPOSTAREGISTROACSPSPCASPCA136CONSULTASPCA136RESUMO() {
        return new SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA136CONSULTA.SPCA136RESUMO();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA131TELEFONE }
     * 
     */
    public SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA131TELEFONE createSPCAXMLRESPOSTAREGISTROACSPSPCASPCA131TELEFONE() {
        return new SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA131TELEFONE();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA125PROTESTO }
     * 
     */
    public SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA125PROTESTO createSPCAXMLRESPOSTAREGISTROACSPSPCASPCA125PROTESTO() {
        return new SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA125PROTESTO();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA124DEBITO }
     * 
     */
    public SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA124DEBITO createSPCAXMLRESPOSTAREGISTROACSPSPCASPCA124DEBITO() {
        return new SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA124DEBITO();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA123INFORMACAO }
     * 
     */
    public SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA123INFORMACAO createSPCAXMLRESPOSTAREGISTROACSPSPCASPCA123INFORMACAO() {
        return new SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA123INFORMACAO();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA111CONSULTA }
     * 
     */
    public SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA111CONSULTA createSPCAXMLRESPOSTAREGISTROACSPSPCASPCA111CONSULTA() {
        return new SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA111CONSULTA();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA111CONSULTA.SPCA111RESUMO }
     * 
     */
    public SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA111CONSULTA.SPCA111RESUMO createSPCAXMLRESPOSTAREGISTROACSPSPCASPCA111CONSULTASPCA111RESUMO() {
        return new SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA111CONSULTA.SPCA111RESUMO();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA109PROTESTOSP }
     * 
     */
    public SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA109PROTESTOSP createSPCAXMLRESPOSTAREGISTROACSPSPCASPCA109PROTESTOSP() {
        return new SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA109PROTESTOSP();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA109PROTESTOSP.SPCA109RESUMO }
     * 
     */
    public SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA109PROTESTOSP.SPCA109RESUMO createSPCAXMLRESPOSTAREGISTROACSPSPCASPCA109PROTESTOSPSPCA109RESUMO() {
        return new SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA109PROTESTOSP.SPCA109RESUMO();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA108DEBITO }
     * 
     */
    public SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA108DEBITO createSPCAXMLRESPOSTAREGISTROACSPSPCASPCA108DEBITO() {
        return new SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA108DEBITO();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA108DEBITO.SPCA108RESUMO }
     * 
     */
    public SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA108DEBITO.SPCA108RESUMO createSPCAXMLRESPOSTAREGISTROACSPSPCASPCA108DEBITOSPCA108RESUMO() {
        return new SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA108DEBITO.SPCA108RESUMO();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA022PROTESTOS }
     * 
     */
    public SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA022PROTESTOS createSPCAXMLRESPOSTAREGISTROACSPSPCASPCA022PROTESTOS() {
        return new SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA022PROTESTOS();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA022PROTESTOS.SPCA022RESUMO }
     * 
     */
    public SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA022PROTESTOS.SPCA022RESUMO createSPCAXMLRESPOSTAREGISTROACSPSPCASPCA022PROTESTOSSPCA022RESUMO() {
        return new SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA022PROTESTOS.SPCA022RESUMO();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA020ACOES }
     * 
     */
    public SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA020ACOES createSPCAXMLRESPOSTAREGISTROACSPSPCASPCA020ACOES() {
        return new SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA020ACOES();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA020ACOES.SPCA020RESUMO }
     * 
     */
    public SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA020ACOES.SPCA020RESUMO createSPCAXMLRESPOSTAREGISTROACSPSPCASPCA020ACOESSPCA020RESUMO() {
        return new SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA020ACOES.SPCA020RESUMO();
    }

    /**
     * Create an instance of {@link SPCAXML.SOLICITACAO }
     * 
     */
    public SPCAXML.SOLICITACAO createSPCAXMLSOLICITACAO() {
        return new SPCAXML.SOLICITACAO();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.RESPOSTARETORNO }
     * 
     */
    public SPCAXML.RESPOSTA.RESPOSTARETORNO createSPCAXMLRESPOSTARESPOSTARETORNO() {
        return new SPCAXML.RESPOSTA.RESPOSTARETORNO();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA000MENSAGEM }
     * 
     */
    public SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA000MENSAGEM createSPCAXMLRESPOSTAREGISTROACSPSPCASPCA000MENSAGEM() {
        return new SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA000MENSAGEM();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA126CONSULTA }
     * 
     */
    public SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA126CONSULTA createSPCAXMLRESPOSTAREGISTROACSPSPCASPCA126CONSULTA() {
        return new SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA126CONSULTA();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA221SINTESE }
     * 
     */
    public SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA221SINTESE createSPCAXMLRESPOSTAREGISTROACSPSPCASPCA221SINTESE() {
        return new SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA221SINTESE();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA500IDENTIFICA }
     * 
     */
    public SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA500IDENTIFICA createSPCAXMLRESPOSTAREGISTROACSPSPCASPCA500IDENTIFICA() {
        return new SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA500IDENTIFICA();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA501LOCALIZACAO }
     * 
     */
    public SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA501LOCALIZACAO createSPCAXMLRESPOSTAREGISTROACSPSPCASPCA501LOCALIZACAO() {
        return new SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA501LOCALIZACAO();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA502GRAFIAS }
     * 
     */
    public SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA502GRAFIAS createSPCAXMLRESPOSTAREGISTROACSPSPCASPCA502GRAFIAS() {
        return new SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA502GRAFIAS();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA603DECISAO }
     * 
     */
    public SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA603DECISAO createSPCAXMLRESPOSTAREGISTROACSPSPCASPCA603DECISAO() {
        return new SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA603DECISAO();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA940MENSAGEM }
     * 
     */
    public SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA940MENSAGEM createSPCAXMLRESPOSTAREGISTROACSPSPCASPCA940MENSAGEM() {
        return new SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA940MENSAGEM();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA601SCORECRED.SPCA601DESCRICAO }
     * 
     */
    public SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA601SCORECRED.SPCA601DESCRICAO createSPCAXMLRESPOSTAREGISTROACSPSPCASPCA601SCORECREDSPCA601DESCRICAO() {
        return new SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA601SCORECRED.SPCA601DESCRICAO();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA601SCORECRED.SPCA601CLASSIFICA }
     * 
     */
    public SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA601SCORECRED.SPCA601CLASSIFICA createSPCAXMLRESPOSTAREGISTROACSPSPCASPCA601SCORECREDSPCA601CLASSIFICA() {
        return new SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA601SCORECRED.SPCA601CLASSIFICA();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA295RELACAO.SPCA295RECFALACAO }
     * 
     */
    public SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA295RELACAO.SPCA295RECFALACAO createSPCAXMLRESPOSTAREGISTROACSPSPCASPCA295RELACAOSPCA295RECFALACAO() {
        return new SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA295RELACAO.SPCA295RECFALACAO();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA282PARTICIPACAO.SPCA282OUTRAS.SPCA282DATA }
     * 
     */
    public SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA282PARTICIPACAO.SPCA282OUTRAS.SPCA282DATA createSPCAXMLRESPOSTAREGISTROACSPSPCASPCA282PARTICIPACAOSPCA282OUTRASSPCA282DATA() {
        return new SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA282PARTICIPACAO.SPCA282OUTRAS.SPCA282DATA();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA268CHDEVOLVIDO.SPCA268USUARIOS.SPCA268DATA }
     * 
     */
    public SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA268CHDEVOLVIDO.SPCA268USUARIOS.SPCA268DATA createSPCAXMLRESPOSTAREGISTROACSPSPCASPCA268CHDEVOLVIDOSPCA268USUARIOSSPCA268DATA() {
        return new SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA268CHDEVOLVIDO.SPCA268USUARIOS.SPCA268DATA();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA248CONSULTA.SPCA248CHEQUE.SPCA248DADOS }
     * 
     */
    public SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA248CONSULTA.SPCA248CHEQUE.SPCA248DADOS createSPCAXMLRESPOSTAREGISTROACSPSPCASPCA248CONSULTASPCA248CHEQUESPCA248DADOS() {
        return new SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA248CONSULTA.SPCA248CHEQUE.SPCA248DADOS();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA247HISTORICO.SPCA247DACONTA.SPCA247CONSULTA }
     * 
     */
    public SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA247HISTORICO.SPCA247DACONTA.SPCA247CONSULTA createSPCAXMLRESPOSTAREGISTROACSPSPCASPCA247HISTORICOSPCA247DACONTASPCA247CONSULTA() {
        return new SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA247HISTORICO.SPCA247DACONTA.SPCA247CONSULTA();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA246HISTORICO.SPCA246CHEQUES.SPCA246CONSULTA }
     * 
     */
    public SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA246HISTORICO.SPCA246CHEQUES.SPCA246CONSULTA createSPCAXMLRESPOSTAREGISTROACSPSPCASPCA246HISTORICOSPCA246CHEQUESSPCA246CONSULTA() {
        return new SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA246HISTORICO.SPCA246CHEQUES.SPCA246CONSULTA();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA245CHSUSTADO21 .SPCA245ALINEA21 .SPCA245CHEQUES }
     * 
     */
    public SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA245CHSUSTADO21 .SPCA245ALINEA21 .SPCA245CHEQUES createSPCAXMLRESPOSTAREGISTROACSPSPCASPCA245CHSUSTADO21SPCA245ALINEA21SPCA245CHEQUES() {
        return new SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA245CHSUSTADO21 .SPCA245ALINEA21 .SPCA245CHEQUES();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA245CHSUSTADO21 .SPCA245ALINEA21 .SPCA245ALINEA }
     * 
     */
    public SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA245CHSUSTADO21 .SPCA245ALINEA21 .SPCA245ALINEA createSPCAXMLRESPOSTAREGISTROACSPSPCASPCA245CHSUSTADO21SPCA245ALINEA21SPCA245ALINEA() {
        return new SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA245CHSUSTADO21 .SPCA245ALINEA21 .SPCA245ALINEA();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA245CHSUSTADO21 .SPCA245ALINEA21 .SPCA245DATA }
     * 
     */
    public SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA245CHSUSTADO21 .SPCA245ALINEA21 .SPCA245DATA createSPCAXMLRESPOSTAREGISTROACSPSPCASPCA245CHSUSTADO21SPCA245ALINEA21SPCA245DATA() {
        return new SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA245CHSUSTADO21 .SPCA245ALINEA21 .SPCA245DATA();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA244CHDEVOLUCAO.SPCA244PORUSUARIO.SPCA244CHEQUES }
     * 
     */
    public SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA244CHDEVOLUCAO.SPCA244PORUSUARIO.SPCA244CHEQUES createSPCAXMLRESPOSTAREGISTROACSPSPCASPCA244CHDEVOLUCAOSPCA244PORUSUARIOSPCA244CHEQUES() {
        return new SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA244CHDEVOLUCAO.SPCA244PORUSUARIO.SPCA244CHEQUES();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA244CHDEVOLUCAO.SPCA244PORUSUARIO.SPCA244ALINEA }
     * 
     */
    public SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA244CHDEVOLUCAO.SPCA244PORUSUARIO.SPCA244ALINEA createSPCAXMLRESPOSTAREGISTROACSPSPCASPCA244CHDEVOLUCAOSPCA244PORUSUARIOSPCA244ALINEA() {
        return new SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA244CHDEVOLUCAO.SPCA244PORUSUARIO.SPCA244ALINEA();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA244CHDEVOLUCAO.SPCA244PORUSUARIO.SPCA244DATA }
     * 
     */
    public SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA244CHDEVOLUCAO.SPCA244PORUSUARIO.SPCA244DATA createSPCAXMLRESPOSTAREGISTROACSPSPCASPCA244CHDEVOLUCAOSPCA244PORUSUARIOSPCA244DATA() {
        return new SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA244CHDEVOLUCAO.SPCA244PORUSUARIO.SPCA244DATA();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA243INFORMACAO.SPCA243COMPLEMENTAR }
     * 
     */
    public SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA243INFORMACAO.SPCA243COMPLEMENTAR createSPCAXMLRESPOSTAREGISTROACSPSPCASPCA243INFORMACAOSPCA243COMPLEMENTAR() {
        return new SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA243INFORMACAO.SPCA243COMPLEMENTAR();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA242CCF.SPCA242DEVOLUCOES.SPCA242MOTIVO12 }
     * 
     */
    public SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA242CCF.SPCA242DEVOLUCOES.SPCA242MOTIVO12 createSPCAXMLRESPOSTAREGISTROACSPSPCASPCA242CCFSPCA242DEVOLUCOESSPCA242MOTIVO12() {
        return new SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA242CCF.SPCA242DEVOLUCOES.SPCA242MOTIVO12();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA242CCF.SPCA242DEVOLUCOES.SPCA242MOTIVO13 }
     * 
     */
    public SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA242CCF.SPCA242DEVOLUCOES.SPCA242MOTIVO13 createSPCAXMLRESPOSTAREGISTROACSPSPCASPCA242CCFSPCA242DEVOLUCOESSPCA242MOTIVO13() {
        return new SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA242CCF.SPCA242DEVOLUCOES.SPCA242MOTIVO13();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA242CCF.SPCA242DEVOLUCOES.SPCA242MOTIVO14 }
     * 
     */
    public SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA242CCF.SPCA242DEVOLUCOES.SPCA242MOTIVO14 createSPCAXMLRESPOSTAREGISTROACSPSPCASPCA242CCFSPCA242DEVOLUCOESSPCA242MOTIVO14() {
        return new SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA242CCF.SPCA242DEVOLUCOES.SPCA242MOTIVO14();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA242CCF.SPCA242DEVOLUCOES.SPCA242MOTIVO99 }
     * 
     */
    public SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA242CCF.SPCA242DEVOLUCOES.SPCA242MOTIVO99 createSPCAXMLRESPOSTAREGISTROACSPSPCASPCA242CCFSPCA242DEVOLUCOESSPCA242MOTIVO99() {
        return new SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA242CCF.SPCA242DEVOLUCOES.SPCA242MOTIVO99();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA227CEP.SPCA227CONFIRMACAO }
     * 
     */
    public SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA227CEP.SPCA227CONFIRMACAO createSPCAXMLRESPOSTAREGISTROACSPSPCASPCA227CEPSPCA227CONFIRMACAO() {
        return new SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA227CEP.SPCA227CONFIRMACAO();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA224ENDERECODA.SPCA224AGBANCARIA }
     * 
     */
    public SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA224ENDERECODA.SPCA224AGBANCARIA createSPCAXMLRESPOSTAREGISTROACSPSPCASPCA224ENDERECODASPCA224AGBANCARIA() {
        return new SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA224ENDERECODA.SPCA224AGBANCARIA();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA223TELEFONE.SPCA223CONFIRMACAO }
     * 
     */
    public SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA223TELEFONE.SPCA223CONFIRMACAO createSPCAXMLRESPOSTAREGISTROACSPSPCASPCA223TELEFONESPCA223CONFIRMACAO() {
        return new SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA223TELEFONE.SPCA223CONFIRMACAO();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA220CONSULTASCH.SPCA220RESUMO.SPCA220DATA }
     * 
     */
    public SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA220CONSULTASCH.SPCA220RESUMO.SPCA220DATA createSPCAXMLRESPOSTAREGISTROACSPSPCASPCA220CONSULTASCHSPCA220RESUMOSPCA220DATA() {
        return new SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA220CONSULTASCH.SPCA220RESUMO.SPCA220DATA();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA214CCFRESUMO.SPCA214DEVOLUCOES.SPCA214DEVOLVIDOS }
     * 
     */
    public SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA214CCFRESUMO.SPCA214DEVOLUCOES.SPCA214DEVOLVIDOS createSPCAXMLRESPOSTAREGISTROACSPSPCASPCA214CCFRESUMOSPCA214DEVOLUCOESSPCA214DEVOLVIDOS() {
        return new SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA214CCFRESUMO.SPCA214DEVOLUCOES.SPCA214DEVOLVIDOS();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA211SUSTADO.SPCA211CHQTALAO.SPCA211ALINEA }
     * 
     */
    public SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA211SUSTADO.SPCA211CHQTALAO.SPCA211ALINEA createSPCAXMLRESPOSTAREGISTROACSPSPCASPCA211SUSTADOSPCA211CHQTALAOSPCA211ALINEA() {
        return new SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA211SUSTADO.SPCA211CHQTALAO.SPCA211ALINEA();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA211SUSTADO.SPCA211CHQTALAO.SPCA211DATA }
     * 
     */
    public SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA211SUSTADO.SPCA211CHQTALAO.SPCA211DATA createSPCAXMLRESPOSTAREGISTROACSPSPCASPCA211SUSTADOSPCA211CHQTALAOSPCA211DATA() {
        return new SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA211SUSTADO.SPCA211CHQTALAO.SPCA211DATA();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA137CONSULTA.SPCA137SEGMENTADO.SPCA137DADOS.SPCA137RAMO }
     * 
     */
    public SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA137CONSULTA.SPCA137SEGMENTADO.SPCA137DADOS.SPCA137RAMO createSPCAXMLRESPOSTAREGISTROACSPSPCASPCA137CONSULTASPCA137SEGMENTADOSPCA137DADOSSPCA137RAMO() {
        return new SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA137CONSULTA.SPCA137SEGMENTADO.SPCA137DADOS.SPCA137RAMO();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA137CONSULTA.SPCA137SEGMENTADO.SPCA137DADOS.SPCA137SEGMENTO }
     * 
     */
    public SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA137CONSULTA.SPCA137SEGMENTADO.SPCA137DADOS.SPCA137SEGMENTO createSPCAXMLRESPOSTAREGISTROACSPSPCASPCA137CONSULTASPCA137SEGMENTADOSPCA137DADOSSPCA137SEGMENTO() {
        return new SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA137CONSULTA.SPCA137SEGMENTADO.SPCA137DADOS.SPCA137SEGMENTO();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA137CONSULTA.SPCA137SEGMENTADO.SPCA137DADOS.SPCA137GRUPO }
     * 
     */
    public SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA137CONSULTA.SPCA137SEGMENTADO.SPCA137DADOS.SPCA137GRUPO createSPCAXMLRESPOSTAREGISTROACSPSPCASPCA137CONSULTASPCA137SEGMENTADOSPCA137DADOSSPCA137GRUPO() {
        return new SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA137CONSULTA.SPCA137SEGMENTADO.SPCA137DADOS.SPCA137GRUPO();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA136CONSULTA.SPCA136RESUMO.SPCA136PERIODO }
     * 
     */
    public SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA136CONSULTA.SPCA136RESUMO.SPCA136PERIODO createSPCAXMLRESPOSTAREGISTROACSPSPCASPCA136CONSULTASPCA136RESUMOSPCA136PERIODO() {
        return new SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA136CONSULTA.SPCA136RESUMO.SPCA136PERIODO();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA136CONSULTA.SPCA136RESUMO.SPCA136ULTIMA }
     * 
     */
    public SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA136CONSULTA.SPCA136RESUMO.SPCA136ULTIMA createSPCAXMLRESPOSTAREGISTROACSPSPCASPCA136CONSULTASPCA136RESUMOSPCA136ULTIMA() {
        return new SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA136CONSULTA.SPCA136RESUMO.SPCA136ULTIMA();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA136CONSULTA.SPCA136RESUMO.SPCA136PENULTIMA }
     * 
     */
    public SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA136CONSULTA.SPCA136RESUMO.SPCA136PENULTIMA createSPCAXMLRESPOSTAREGISTROACSPSPCASPCA136CONSULTASPCA136RESUMOSPCA136PENULTIMA() {
        return new SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA136CONSULTA.SPCA136RESUMO.SPCA136PENULTIMA();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA136CONSULTA.SPCA136RESUMO.SPCA136ANTEPENULTIM }
     * 
     */
    public SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA136CONSULTA.SPCA136RESUMO.SPCA136ANTEPENULTIM createSPCAXMLRESPOSTAREGISTROACSPSPCASPCA136CONSULTASPCA136RESUMOSPCA136ANTEPENULTIM() {
        return new SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA136CONSULTA.SPCA136RESUMO.SPCA136ANTEPENULTIM();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA131TELEFONE.SPCA131DOCVINCULADO }
     * 
     */
    public SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA131TELEFONE.SPCA131DOCVINCULADO createSPCAXMLRESPOSTAREGISTROACSPSPCASPCA131TELEFONESPCA131DOCVINCULADO() {
        return new SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA131TELEFONE.SPCA131DOCVINCULADO();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA125PROTESTO.SPCA125DATA }
     * 
     */
    public SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA125PROTESTO.SPCA125DATA createSPCAXMLRESPOSTAREGISTROACSPSPCASPCA125PROTESTOSPCA125DATA() {
        return new SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA125PROTESTO.SPCA125DATA();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA124DEBITO.SPCA124DATA }
     * 
     */
    public SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA124DEBITO.SPCA124DATA createSPCAXMLRESPOSTAREGISTROACSPSPCASPCA124DEBITOSPCA124DATA() {
        return new SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA124DEBITO.SPCA124DATA();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA123INFORMACAO.SPCA123COMPLEMENTAR }
     * 
     */
    public SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA123INFORMACAO.SPCA123COMPLEMENTAR createSPCAXMLRESPOSTAREGISTROACSPSPCASPCA123INFORMACAOSPCA123COMPLEMENTAR() {
        return new SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA123INFORMACAO.SPCA123COMPLEMENTAR();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA111CONSULTA.SPCA111RESUMO.SPCA111DATA1 }
     * 
     */
    public SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA111CONSULTA.SPCA111RESUMO.SPCA111DATA1 createSPCAXMLRESPOSTAREGISTROACSPSPCASPCA111CONSULTASPCA111RESUMOSPCA111DATA1() {
        return new SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA111CONSULTA.SPCA111RESUMO.SPCA111DATA1();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA111CONSULTA.SPCA111RESUMO.SPCA111DATA2 }
     * 
     */
    public SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA111CONSULTA.SPCA111RESUMO.SPCA111DATA2 createSPCAXMLRESPOSTAREGISTROACSPSPCASPCA111CONSULTASPCA111RESUMOSPCA111DATA2() {
        return new SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA111CONSULTA.SPCA111RESUMO.SPCA111DATA2();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA111CONSULTA.SPCA111RESUMO.SPCA111DATA3 }
     * 
     */
    public SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA111CONSULTA.SPCA111RESUMO.SPCA111DATA3 createSPCAXMLRESPOSTAREGISTROACSPSPCASPCA111CONSULTASPCA111RESUMOSPCA111DATA3() {
        return new SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA111CONSULTA.SPCA111RESUMO.SPCA111DATA3();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA111CONSULTA.SPCA111RESUMO.SPCA111DATA4 }
     * 
     */
    public SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA111CONSULTA.SPCA111RESUMO.SPCA111DATA4 createSPCAXMLRESPOSTAREGISTROACSPSPCASPCA111CONSULTASPCA111RESUMOSPCA111DATA4() {
        return new SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA111CONSULTA.SPCA111RESUMO.SPCA111DATA4();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA109PROTESTOSP.SPCA109RESUMO.SPCA109TOTAL }
     * 
     */
    public SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA109PROTESTOSP.SPCA109RESUMO.SPCA109TOTAL createSPCAXMLRESPOSTAREGISTROACSPSPCASPCA109PROTESTOSPSPCA109RESUMOSPCA109TOTAL() {
        return new SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA109PROTESTOSP.SPCA109RESUMO.SPCA109TOTAL();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA109PROTESTOSP.SPCA109RESUMO.SPCA109PRIMEIROTP }
     * 
     */
    public SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA109PROTESTOSP.SPCA109RESUMO.SPCA109PRIMEIROTP createSPCAXMLRESPOSTAREGISTROACSPSPCASPCA109PROTESTOSPSPCA109RESUMOSPCA109PRIMEIROTP() {
        return new SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA109PROTESTOSP.SPCA109RESUMO.SPCA109PRIMEIROTP();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA109PROTESTOSP.SPCA109RESUMO.SPCA109MAIORPROT }
     * 
     */
    public SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA109PROTESTOSP.SPCA109RESUMO.SPCA109MAIORPROT createSPCAXMLRESPOSTAREGISTROACSPSPCASPCA109PROTESTOSPSPCA109RESUMOSPCA109MAIORPROT() {
        return new SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA109PROTESTOSP.SPCA109RESUMO.SPCA109MAIORPROT();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA108DEBITO.SPCA108RESUMO.SPCA108TOTAL }
     * 
     */
    public SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA108DEBITO.SPCA108RESUMO.SPCA108TOTAL createSPCAXMLRESPOSTAREGISTROACSPSPCASPCA108DEBITOSPCA108RESUMOSPCA108TOTAL() {
        return new SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA108DEBITO.SPCA108RESUMO.SPCA108TOTAL();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA108DEBITO.SPCA108RESUMO.SPCA108PRIMEIRODEB }
     * 
     */
    public SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA108DEBITO.SPCA108RESUMO.SPCA108PRIMEIRODEB createSPCAXMLRESPOSTAREGISTROACSPSPCASPCA108DEBITOSPCA108RESUMOSPCA108PRIMEIRODEB() {
        return new SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA108DEBITO.SPCA108RESUMO.SPCA108PRIMEIRODEB();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA108DEBITO.SPCA108RESUMO.SPCA108MAIORDEB }
     * 
     */
    public SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA108DEBITO.SPCA108RESUMO.SPCA108MAIORDEB createSPCAXMLRESPOSTAREGISTROACSPSPCASPCA108DEBITOSPCA108RESUMOSPCA108MAIORDEB() {
        return new SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA108DEBITO.SPCA108RESUMO.SPCA108MAIORDEB();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA022PROTESTOS.SPCA023REGISTRO }
     * 
     */
    public SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA022PROTESTOS.SPCA023REGISTRO createSPCAXMLRESPOSTAREGISTROACSPSPCASPCA022PROTESTOSSPCA023REGISTRO() {
        return new SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA022PROTESTOS.SPCA023REGISTRO();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA022PROTESTOS.SPCA022RESUMO.SPCA022DATA }
     * 
     */
    public SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA022PROTESTOS.SPCA022RESUMO.SPCA022DATA createSPCAXMLRESPOSTAREGISTROACSPSPCASPCA022PROTESTOSSPCA022RESUMOSPCA022DATA() {
        return new SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA022PROTESTOS.SPCA022RESUMO.SPCA022DATA();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA022PROTESTOS.SPCA022RESUMO.SPCA022VALORES }
     * 
     */
    public SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA022PROTESTOS.SPCA022RESUMO.SPCA022VALORES createSPCAXMLRESPOSTAREGISTROACSPSPCASPCA022PROTESTOSSPCA022RESUMOSPCA022VALORES() {
        return new SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA022PROTESTOS.SPCA022RESUMO.SPCA022VALORES();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA020ACOES.SPCA021REGISTRO }
     * 
     */
    public SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA020ACOES.SPCA021REGISTRO createSPCAXMLRESPOSTAREGISTROACSPSPCASPCA020ACOESSPCA021REGISTRO() {
        return new SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA020ACOES.SPCA021REGISTRO();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA020ACOES.SPCA020RESUMO.SPCA020DATA }
     * 
     */
    public SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA020ACOES.SPCA020RESUMO.SPCA020DATA createSPCAXMLRESPOSTAREGISTROACSPSPCASPCA020ACOESSPCA020RESUMOSPCA020DATA() {
        return new SPCAXML.RESPOSTA.REGISTROACSPSPCA.SPCA020ACOES.SPCA020RESUMO.SPCA020DATA();
    }

}
