//
// Este arquivo foi gerado pela Arquitetura JavaTM para Implementação de Referência (JAXB) de Bind XML, v2.2.8-b130911.1802 
// Consulte <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Todas as modificações neste arquivo serão perdidas após a recompilação do esquema de origem. 
// Gerado em: 2018.07.18 às 02:45:12 PM BRT 
//


package br.wsorpec.wscdlrio.spcnetNacionalCpf;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generated package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SPCAXML }
     * 
     */
    public SPCAXML createSPCAXML() {
        return new SPCAXML();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA }
     * 
     */
    public SPCAXML.RESPOSTA createSPCAXMLRESPOSTA() {
        return new SPCAXML.RESPOSTA();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.REGISTROACSPNET }
     * 
     */
    public SPCAXML.RESPOSTA.REGISTROACSPNET createSPCAXMLRESPOSTAREGISTROACSPNET() {
        return new SPCAXML.RESPOSTA.REGISTROACSPNET();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.REGISTROACSPNET.NET940MENSAGEM }
     * 
     */
    public SPCAXML.RESPOSTA.REGISTROACSPNET.NET940MENSAGEM createSPCAXMLRESPOSTAREGISTROACSPNETNET940MENSAGEM() {
        return new SPCAXML.RESPOSTA.REGISTROACSPNET.NET940MENSAGEM();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.REGISTROACSPNET.NET304CONSANT }
     * 
     */
    public SPCAXML.RESPOSTA.REGISTROACSPNET.NET304CONSANT createSPCAXMLRESPOSTAREGISTROACSPNETNET304CONSANT() {
        return new SPCAXML.RESPOSTA.REGISTROACSPNET.NET304CONSANT();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.REGISTROACSPNET.NET303CONSANTPJ }
     * 
     */
    public SPCAXML.RESPOSTA.REGISTROACSPNET.NET303CONSANTPJ createSPCAXMLRESPOSTAREGISTROACSPNETNET303CONSANTPJ() {
        return new SPCAXML.RESPOSTA.REGISTROACSPNET.NET303CONSANTPJ();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.REGISTROACSPNET.NET268RESUMODEV }
     * 
     */
    public SPCAXML.RESPOSTA.REGISTROACSPNET.NET268RESUMODEV createSPCAXMLRESPOSTAREGISTROACSPNETNET268RESUMODEV() {
        return new SPCAXML.RESPOSTA.REGISTROACSPNET.NET268RESUMODEV();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.REGISTROACSPNET.NET245CHEQUESUS }
     * 
     */
    public SPCAXML.RESPOSTA.REGISTROACSPNET.NET245CHEQUESUS createSPCAXMLRESPOSTAREGISTROACSPNETNET245CHEQUESUS() {
        return new SPCAXML.RESPOSTA.REGISTROACSPNET.NET245CHEQUESUS();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.REGISTROACSPNET.NET244USUARIOS }
     * 
     */
    public SPCAXML.RESPOSTA.REGISTROACSPNET.NET244USUARIOS createSPCAXMLRESPOSTAREGISTROACSPNETNET244USUARIOS() {
        return new SPCAXML.RESPOSTA.REGISTROACSPNET.NET244USUARIOS();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.REGISTROACSPNET.NET242CCF }
     * 
     */
    public SPCAXML.RESPOSTA.REGISTROACSPNET.NET242CCF createSPCAXMLRESPOSTAREGISTROACSPNETNET242CCF() {
        return new SPCAXML.RESPOSTA.REGISTROACSPNET.NET242CCF();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.REGISTROACSPNET.NET227CEP }
     * 
     */
    public SPCAXML.RESPOSTA.REGISTROACSPNET.NET227CEP createSPCAXMLRESPOSTAREGISTROACSPNETNET227CEP() {
        return new SPCAXML.RESPOSTA.REGISTROACSPNET.NET227CEP();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.REGISTROACSPNET.NET224AGENCIABANCO }
     * 
     */
    public SPCAXML.RESPOSTA.REGISTROACSPNET.NET224AGENCIABANCO createSPCAXMLRESPOSTAREGISTROACSPNETNET224AGENCIABANCO() {
        return new SPCAXML.RESPOSTA.REGISTROACSPNET.NET224AGENCIABANCO();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.REGISTROACSPNET.NET223TELEFONE }
     * 
     */
    public SPCAXML.RESPOSTA.REGISTROACSPNET.NET223TELEFONE createSPCAXMLRESPOSTAREGISTROACSPNETNET223TELEFONE() {
        return new SPCAXML.RESPOSTA.REGISTROACSPNET.NET223TELEFONE();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.REGISTROACSPNET.NET216CHEQUESUS21 }
     * 
     */
    public SPCAXML.RESPOSTA.REGISTROACSPNET.NET216CHEQUESUS21 createSPCAXMLRESPOSTAREGISTROACSPNETNET216CHEQUESUS21() {
        return new SPCAXML.RESPOSTA.REGISTROACSPNET.NET216CHEQUESUS21();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.REGISTROACSPNET.NET256CHQSUSTADO21 }
     * 
     */
    public SPCAXML.RESPOSTA.REGISTROACSPNET.NET256CHQSUSTADO21 createSPCAXMLRESPOSTAREGISTROACSPNETNET256CHQSUSTADO21() {
        return new SPCAXML.RESPOSTA.REGISTROACSPNET.NET256CHQSUSTADO21();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.REGISTROACSPNET.NET212OUTROSDOCS }
     * 
     */
    public SPCAXML.RESPOSTA.REGISTROACSPNET.NET212OUTROSDOCS createSPCAXMLRESPOSTAREGISTROACSPNETNET212OUTROSDOCS() {
        return new SPCAXML.RESPOSTA.REGISTROACSPNET.NET212OUTROSDOCS();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.REGISTROACSPNET.NET127CONSULTAANT }
     * 
     */
    public SPCAXML.RESPOSTA.REGISTROACSPNET.NET127CONSULTAANT createSPCAXMLRESPOSTAREGISTROACSPNETNET127CONSULTAANT() {
        return new SPCAXML.RESPOSTA.REGISTROACSPNET.NET127CONSULTAANT();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.REGISTROACSPNET.NET111CONSULTAANT }
     * 
     */
    public SPCAXML.RESPOSTA.REGISTROACSPNET.NET111CONSULTAANT createSPCAXMLRESPOSTAREGISTROACSPNETNET111CONSULTAANT() {
        return new SPCAXML.RESPOSTA.REGISTROACSPNET.NET111CONSULTAANT();
    }

    /**
     * Create an instance of {@link SPCAXML.SOLICITACAO }
     * 
     */
    public SPCAXML.SOLICITACAO createSPCAXMLSOLICITACAO() {
        return new SPCAXML.SOLICITACAO();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.RESPOSTARETORNO }
     * 
     */
    public SPCAXML.RESPOSTA.RESPOSTARETORNO createSPCAXMLRESPOSTARESPOSTARETORNO() {
        return new SPCAXML.RESPOSTA.RESPOSTARETORNO();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.REGISTROACSPNET.NET000MENSAGEM }
     * 
     */
    public SPCAXML.RESPOSTA.REGISTROACSPNET.NET000MENSAGEM createSPCAXMLRESPOSTAREGISTROACSPNETNET000MENSAGEM() {
        return new SPCAXML.RESPOSTA.REGISTROACSPNET.NET000MENSAGEM();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.REGISTROACSPNET.NET123INFOCOMP }
     * 
     */
    public SPCAXML.RESPOSTA.REGISTROACSPNET.NET123INFOCOMP createSPCAXMLRESPOSTAREGISTROACSPNETNET123INFOCOMP() {
        return new SPCAXML.RESPOSTA.REGISTROACSPNET.NET123INFOCOMP();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.REGISTROACSPNET.NET124REGISTROSCPC }
     * 
     */
    public SPCAXML.RESPOSTA.REGISTROACSPNET.NET124REGISTROSCPC createSPCAXMLRESPOSTAREGISTROACSPNETNET124REGISTROSCPC() {
        return new SPCAXML.RESPOSTA.REGISTROACSPNET.NET124REGISTROSCPC();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.REGISTROACSPNET.NET126CONSULTAANT }
     * 
     */
    public SPCAXML.RESPOSTA.REGISTROACSPNET.NET126CONSULTAANT createSPCAXMLRESPOSTAREGISTROACSPNETNET126CONSULTAANT() {
        return new SPCAXML.RESPOSTA.REGISTROACSPNET.NET126CONSULTAANT();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.REGISTROACSPNET.NET141DEBITO }
     * 
     */
    public SPCAXML.RESPOSTA.REGISTROACSPNET.NET141DEBITO createSPCAXMLRESPOSTAREGISTROACSPNETNET141DEBITO() {
        return new SPCAXML.RESPOSTA.REGISTROACSPNET.NET141DEBITO();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.REGISTROACSPNET.NET142TITPROT }
     * 
     */
    public SPCAXML.RESPOSTA.REGISTROACSPNET.NET142TITPROT createSPCAXMLRESPOSTAREGISTROACSPNETNET142TITPROT() {
        return new SPCAXML.RESPOSTA.REGISTROACSPNET.NET142TITPROT();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.REGISTROACSPNET.NET146TITPROT }
     * 
     */
    public SPCAXML.RESPOSTA.REGISTROACSPNET.NET146TITPROT createSPCAXMLRESPOSTAREGISTROACSPNETNET146TITPROT() {
        return new SPCAXML.RESPOSTA.REGISTROACSPNET.NET146TITPROT();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.REGISTROACSPNET.NET211CHEQUESUS }
     * 
     */
    public SPCAXML.RESPOSTA.REGISTROACSPNET.NET211CHEQUESUS createSPCAXMLRESPOSTAREGISTROACSPNETNET211CHEQUESUS() {
        return new SPCAXML.RESPOSTA.REGISTROACSPNET.NET211CHEQUESUS();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.REGISTROACSPNET.NET213CHQSUSTADO }
     * 
     */
    public SPCAXML.RESPOSTA.REGISTROACSPNET.NET213CHQSUSTADO createSPCAXMLRESPOSTAREGISTROACSPNETNET213CHQSUSTADO() {
        return new SPCAXML.RESPOSTA.REGISTROACSPNET.NET213CHQSUSTADO();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.REGISTROACSPNET.NET219HISTCHQCTA }
     * 
     */
    public SPCAXML.RESPOSTA.REGISTROACSPNET.NET219HISTCHQCTA createSPCAXMLRESPOSTAREGISTROACSPNETNET219HISTCHQCTA() {
        return new SPCAXML.RESPOSTA.REGISTROACSPNET.NET219HISTCHQCTA();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.REGISTROACSPNET.NET222SINTESEPJ }
     * 
     */
    public SPCAXML.RESPOSTA.REGISTROACSPNET.NET222SINTESEPJ createSPCAXMLRESPOSTAREGISTROACSPNETNET222SINTESEPJ() {
        return new SPCAXML.RESPOSTA.REGISTROACSPNET.NET222SINTESEPJ();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.REGISTROACSPNET.NET246HISTCHEQUE }
     * 
     */
    public SPCAXML.RESPOSTA.REGISTROACSPNET.NET246HISTCHEQUE createSPCAXMLRESPOSTAREGISTROACSPNETNET246HISTCHEQUE() {
        return new SPCAXML.RESPOSTA.REGISTROACSPNET.NET246HISTCHEQUE();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.REGISTROACSPNET.NET247HISTCONTA }
     * 
     */
    public SPCAXML.RESPOSTA.REGISTROACSPNET.NET247HISTCONTA createSPCAXMLRESPOSTAREGISTROACSPNETNET247HISTCONTA() {
        return new SPCAXML.RESPOSTA.REGISTROACSPNET.NET247HISTCONTA();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.REGISTROACSPNET.NET249SINTESEPF }
     * 
     */
    public SPCAXML.RESPOSTA.REGISTROACSPNET.NET249SINTESEPF createSPCAXMLRESPOSTAREGISTROACSPNETNET249SINTESEPF() {
        return new SPCAXML.RESPOSTA.REGISTROACSPNET.NET249SINTESEPF();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.REGISTROACSPNET.NET254RESUMOCCF }
     * 
     */
    public SPCAXML.RESPOSTA.REGISTROACSPNET.NET254RESUMOCCF createSPCAXMLRESPOSTAREGISTROACSPNETNET254RESUMOCCF() {
        return new SPCAXML.RESPOSTA.REGISTROACSPNET.NET254RESUMOCCF();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.REGISTROACSPNET.NET300TOTDEBITOS }
     * 
     */
    public SPCAXML.RESPOSTA.REGISTROACSPNET.NET300TOTDEBITOS createSPCAXMLRESPOSTAREGISTROACSPNETNET300TOTDEBITOS() {
        return new SPCAXML.RESPOSTA.REGISTROACSPNET.NET300TOTDEBITOS();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.REGISTROACSPNET.NET301RELACAODEB }
     * 
     */
    public SPCAXML.RESPOSTA.REGISTROACSPNET.NET301RELACAODEB createSPCAXMLRESPOSTAREGISTROACSPNETNET301RELACAODEB() {
        return new SPCAXML.RESPOSTA.REGISTROACSPNET.NET301RELACAODEB();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.REGISTROACSPNET.NET601SCORECREDITO }
     * 
     */
    public SPCAXML.RESPOSTA.REGISTROACSPNET.NET601SCORECREDITO createSPCAXMLRESPOSTAREGISTROACSPNETNET601SCORECREDITO() {
        return new SPCAXML.RESPOSTA.REGISTROACSPNET.NET601SCORECREDITO();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.REGISTROACSPNET.NET901MSGALERTA }
     * 
     */
    public SPCAXML.RESPOSTA.REGISTROACSPNET.NET901MSGALERTA createSPCAXMLRESPOSTAREGISTROACSPNETNET901MSGALERTA() {
        return new SPCAXML.RESPOSTA.REGISTROACSPNET.NET901MSGALERTA();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.REGISTROACSPNET.NET999ERRO }
     * 
     */
    public SPCAXML.RESPOSTA.REGISTROACSPNET.NET999ERRO createSPCAXMLRESPOSTAREGISTROACSPNETNET999ERRO() {
        return new SPCAXML.RESPOSTA.REGISTROACSPNET.NET999ERRO();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.REGISTROACSPNET.NET940MENSAGEM.NET940REGISTRO }
     * 
     */
    public SPCAXML.RESPOSTA.REGISTROACSPNET.NET940MENSAGEM.NET940REGISTRO createSPCAXMLRESPOSTAREGISTROACSPNETNET940MENSAGEMNET940REGISTRO() {
        return new SPCAXML.RESPOSTA.REGISTROACSPNET.NET940MENSAGEM.NET940REGISTRO();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.REGISTROACSPNET.NET304CONSANT.NET304PARADOC }
     * 
     */
    public SPCAXML.RESPOSTA.REGISTROACSPNET.NET304CONSANT.NET304PARADOC createSPCAXMLRESPOSTAREGISTROACSPNETNET304CONSANTNET304PARADOC() {
        return new SPCAXML.RESPOSTA.REGISTROACSPNET.NET304CONSANT.NET304PARADOC();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.REGISTROACSPNET.NET303CONSANTPJ.NET303ULT12MES }
     * 
     */
    public SPCAXML.RESPOSTA.REGISTROACSPNET.NET303CONSANTPJ.NET303ULT12MES createSPCAXMLRESPOSTAREGISTROACSPNETNET303CONSANTPJNET303ULT12MES() {
        return new SPCAXML.RESPOSTA.REGISTROACSPNET.NET303CONSANTPJ.NET303ULT12MES();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.REGISTROACSPNET.NET268RESUMODEV.NET268USUARIOS }
     * 
     */
    public SPCAXML.RESPOSTA.REGISTROACSPNET.NET268RESUMODEV.NET268USUARIOS createSPCAXMLRESPOSTAREGISTROACSPNETNET268RESUMODEVNET268USUARIOS() {
        return new SPCAXML.RESPOSTA.REGISTROACSPNET.NET268RESUMODEV.NET268USUARIOS();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.REGISTROACSPNET.NET245CHEQUESUS.NET245ALINEA21 }
     * 
     */
    public SPCAXML.RESPOSTA.REGISTROACSPNET.NET245CHEQUESUS.NET245ALINEA21 createSPCAXMLRESPOSTAREGISTROACSPNETNET245CHEQUESUSNET245ALINEA21() {
        return new SPCAXML.RESPOSTA.REGISTROACSPNET.NET245CHEQUESUS.NET245ALINEA21();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.REGISTROACSPNET.NET244USUARIOS.NET244DEVOLUCOES }
     * 
     */
    public SPCAXML.RESPOSTA.REGISTROACSPNET.NET244USUARIOS.NET244DEVOLUCOES createSPCAXMLRESPOSTAREGISTROACSPNETNET244USUARIOSNET244DEVOLUCOES() {
        return new SPCAXML.RESPOSTA.REGISTROACSPNET.NET244USUARIOS.NET244DEVOLUCOES();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.REGISTROACSPNET.NET242CCF.NET242DEVOLUCOES }
     * 
     */
    public SPCAXML.RESPOSTA.REGISTROACSPNET.NET242CCF.NET242DEVOLUCOES createSPCAXMLRESPOSTAREGISTROACSPNETNET242CCFNET242DEVOLUCOES() {
        return new SPCAXML.RESPOSTA.REGISTROACSPNET.NET242CCF.NET242DEVOLUCOES();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.REGISTROACSPNET.NET227CEP.NET227CONFIRMACAO }
     * 
     */
    public SPCAXML.RESPOSTA.REGISTROACSPNET.NET227CEP.NET227CONFIRMACAO createSPCAXMLRESPOSTAREGISTROACSPNETNET227CEPNET227CONFIRMACAO() {
        return new SPCAXML.RESPOSTA.REGISTROACSPNET.NET227CEP.NET227CONFIRMACAO();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.REGISTROACSPNET.NET224AGENCIABANCO.NET224CONFIRMACAO }
     * 
     */
    public SPCAXML.RESPOSTA.REGISTROACSPNET.NET224AGENCIABANCO.NET224CONFIRMACAO createSPCAXMLRESPOSTAREGISTROACSPNETNET224AGENCIABANCONET224CONFIRMACAO() {
        return new SPCAXML.RESPOSTA.REGISTROACSPNET.NET224AGENCIABANCO.NET224CONFIRMACAO();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.REGISTROACSPNET.NET223TELEFONE.NET223CONFIRMACAO }
     * 
     */
    public SPCAXML.RESPOSTA.REGISTROACSPNET.NET223TELEFONE.NET223CONFIRMACAO createSPCAXMLRESPOSTAREGISTROACSPNETNET223TELEFONENET223CONFIRMACAO() {
        return new SPCAXML.RESPOSTA.REGISTROACSPNET.NET223TELEFONE.NET223CONFIRMACAO();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.REGISTROACSPNET.NET216CHEQUESUS21 .NET216RESUMO }
     * 
     */
    public SPCAXML.RESPOSTA.REGISTROACSPNET.NET216CHEQUESUS21 .NET216RESUMO createSPCAXMLRESPOSTAREGISTROACSPNETNET216CHEQUESUS21NET216RESUMO() {
        return new SPCAXML.RESPOSTA.REGISTROACSPNET.NET216CHEQUESUS21 .NET216RESUMO();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.REGISTROACSPNET.NET256CHQSUSTADO21 .NET256RESUMO }
     * 
     */
    public SPCAXML.RESPOSTA.REGISTROACSPNET.NET256CHQSUSTADO21 .NET256RESUMO createSPCAXMLRESPOSTAREGISTROACSPNETNET256CHQSUSTADO21NET256RESUMO() {
        return new SPCAXML.RESPOSTA.REGISTROACSPNET.NET256CHQSUSTADO21 .NET256RESUMO();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.REGISTROACSPNET.NET212OUTROSDOCS.NET212MESMACONTA }
     * 
     */
    public SPCAXML.RESPOSTA.REGISTROACSPNET.NET212OUTROSDOCS.NET212MESMACONTA createSPCAXMLRESPOSTAREGISTROACSPNETNET212OUTROSDOCSNET212MESMACONTA() {
        return new SPCAXML.RESPOSTA.REGISTROACSPNET.NET212OUTROSDOCS.NET212MESMACONTA();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.REGISTROACSPNET.NET127CONSULTAANT.NET127TELEFONE }
     * 
     */
    public SPCAXML.RESPOSTA.REGISTROACSPNET.NET127CONSULTAANT.NET127TELEFONE createSPCAXMLRESPOSTAREGISTROACSPNETNET127CONSULTAANTNET127TELEFONE() {
        return new SPCAXML.RESPOSTA.REGISTROACSPNET.NET127CONSULTAANT.NET127TELEFONE();
    }

    /**
     * Create an instance of {@link SPCAXML.RESPOSTA.REGISTROACSPNET.NET111CONSULTAANT.NET111RESUMO }
     * 
     */
    public SPCAXML.RESPOSTA.REGISTROACSPNET.NET111CONSULTAANT.NET111RESUMO createSPCAXMLRESPOSTAREGISTROACSPNETNET111CONSULTAANTNET111RESUMO() {
        return new SPCAXML.RESPOSTA.REGISTROACSPNET.NET111CONSULTAANT.NET111RESUMO();
    }

}
